import {NextRequest,NextResponse} from "next/server";
import {createServerSupabaseClient} from "@/lib/supabase/server";

type Category="fish"|"shrimp"|"snail"|"crab"|"crayfish"|"amphibian"|"other";
type Candidate={scientific_name:string;common_name?:string;category:Category;adult_size_cm?:number;min_tank_l?:number;min_group_size?:number;recommended_group_size?:number;temperature_min?:number;temperature_max?:number;ph_min?:number;ph_max?:number;gh_min?:number;gh_max?:number;kh_min?:number;kh_max?:number;temperament?:string;diet?:string;difficulty?:string;shrimp_safe?:boolean;shrimp_safety_note?:string;snail_safe?:boolean;plant_safe?:boolean;notes?:string;source_name?:string;source_url?:string;confidence:"high"|"medium"|"low";match_label?:string;verification_status?:string};
const norm=(s:string)=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
const strip=(s:string)=>s.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim();
const slug=(s:string)=>norm(s).replace(/\s+/g,"-");
function aliases(q:string){const n=norm(q);const out=[q];if(/neritina/.test(n)&&/(natalensis|zebra)/.test(n))out.push("Neritina natalensis","Neritina zebra","Neritina sp. Zebra","Slimák Neritina zebra");return [...new Set(out)]}
function score(name:string,q:string){const a=norm(name),b=norm(q);if(!a||!b)return 0;if(a===b)return 100;if(a.includes(b)||b.includes(a))return 80;const aw=a.split(" "),bw=b.split(" ");return bw.reduce((n,w)=>n+(aw.includes(w)?20:0),0)}
function bestScore(name:string,q:string){return Math.max(...aliases(q).map(v=>score(name,v)))}
function n(v:any){const x=Number(v);return Number.isFinite(x)?x:undefined}
function range(text:string,labels:string){const m=new RegExp(`(?:${labels})[^0-9]{0,60}([0-9]+(?:[.,][0-9]+)?)\\s*(?:-|–|až|to)\\s*([0-9]+(?:[.,][0-9]+)?)`,`i`).exec(text);if(!m)return null;const a=Number(m[1].replace(",",".")),b=Number(m[2].replace(",","."));return a<=b?[a,b] as const:null}
function upper(text:string,labels:string){const m=new RegExp(`(?:${labels})[^0-9]{0,60}(?:do|až do|max\\.?|maximum)?\\s*([0-9]+(?:[.,][0-9]+)?)`,`i`).exec(text);return m?Number(m[1].replace(",",".")):undefined}
function unwrap(raw:string){let u=raw.replace(/&amp;/g,"&");try{const p=new URL(u.startsWith("//")?`https:${u}`:u);const r=p.searchParams.get("uddg")||p.searchParams.get("url");if(r)u=decodeURIComponent(r)}catch{}return u}
function categoryFromName(text:string,fallback:Category):Category{const t=norm(text);if(/neocaridina|caridina|shrimp|krevet/.test(t))return"shrimp";if(/neritina|nerite|clithon|tylomelania|snail|slimak|gastropoda/.test(t))return"snail";if(/cambarellus|cherax|crayfish|rak/.test(t))return"crayfish";if(/geosesarma|crab|krab/.test(t))return"crab";if(/axolotl|triton|newt|amphib/.test(t))return"amphibian";if(/paracheirodon|boraras|tetra|rasbor|corydoras|fish|ryb/.test(t))return"fish";return fallback}
const verified:Candidate[]=[
 {scientific_name:"Paracheirodon axelrodi",common_name:"Neonka červená",category:"fish",adult_size_cm:5,min_tank_l:50,min_group_size:10,temperature_min:23,temperature_max:27,ph_min:6,ph_max:7,gh_min:5,gh_max:10,shrimp_safe:true,shrimp_safety_note:"Vhodná k dospelým a väčším krevetám; veľmi malé čerstvo narodené krevetky môže uloviť.",snail_safe:true,plant_safe:true,confidence:"high",verification_status:"verified",match_label:"Presná alebo veľmi blízka zhoda",notes:"Mierumilovná húfová tetra."},
 {scientific_name:"Neocaridina davidi",common_name:"Neocaridina",category:"shrimp",adult_size_cm:3,temperature_min:18,temperature_max:28,ph_min:6.8,ph_max:8,gh_max:20,kh_max:12,shrimp_safe:true,snail_safe:true,plant_safe:true,confidence:"high",verification_status:"verified",match_label:"Presná alebo veľmi blízka zhoda",notes:"Veľmi pokojná a mierumilovná. GH do 20 °dGH a KH do 12 °dKH sú horné limity, nie optimum od nuly."},
 {scientific_name:"Boraras brigittae",common_name:"Razborka bornejská",category:"fish",min_tank_l:20,min_group_size:10,temperature_min:24,temperature_max:28,ph_min:5.5,ph_max:7.2,gh_min:1,gh_max:12,shrimp_safe:true,shrimp_safety_note:"Vhodná aj ku krevetám; pri veľmi malých mláďatách nemožno úplne vylúčiť predáciu.",snail_safe:true,plant_safe:true,confidence:"high",verification_status:"verified",match_label:"Presná alebo veľmi blízka zhoda",notes:"Pokojná drobná húfová ryba."},
 {scientific_name:"Neritina natalensis",common_name:"Neritina zebra",category:"snail",adult_size_cm:3,min_tank_l:30,temperature_min:20,temperature_max:27,ph_min:7,ph_max:8.5,gh_min:5,gh_max:60,temperament:"veľmi mierumilovné",shrimp_safe:true,snail_safe:true,plant_safe:true,diet:"povlakové riasy, zelené a hnedé riasy; možno prikrmovať zeleninou",confidence:"high",verification_status:"verified",match_label:"Presná alebo veľmi blízka zhoda",notes:"Neritina zebra sa v sladkovodnom akváriu nemnoží a nepožiera zdravé rastliny."}
];
function verifiedMatches(q:string,cat:Category){return verified.filter(x=>(cat==="other"||x.category===cat)&&Math.max(bestScore(x.scientific_name,q),bestScore(x.common_name||"",q))>=40)}
async function fetchJson(url:string,ms=2600){try{const r=await fetch(url,{cache:"no-store",signal:AbortSignal.timeout(ms),headers:{"User-Agent":"Mozilla/5.0"}});return r.ok?await r.json():null}catch{return null}}
async function inaturalist(q:string,requested:Category):Promise<Candidate[]>{const data=await Promise.all(aliases(q).slice(0,2).map(t=>fetchJson(`https://api.inaturalist.org/v1/taxa/autocomplete?q=${encodeURIComponent(t)}&per_page=5`)));const out:Candidate[]=[];for(const j of data)for(const x of(j?.results||[])){const scientific=String(x.name||"").trim(),common=String(x.preferred_common_name||x.english_common_name||"").trim()||undefined;const sc=Math.max(bestScore(scientific,q),bestScore(common||"",q));if(sc<35)continue;const cat=categoryFromName(`${scientific} ${common||""}`,requested);if(requested!=="other"&&cat!==requested)continue;out.push({scientific_name:scientific,common_name:common,category:cat,confidence:sc>=80?"high":"medium",verification_status:"name_confirmed",match_label:sc>=80?"Presná alebo veľmi blízka zhoda":"Možná zhoda",notes:"Taxonomická zhoda názvu. Chovateľské parametre sa dopĺňajú iba z odborných zdrojov."})}return out}
async function fishbase(q:string):Promise<Candidate[]>{const term=aliases(q)[0],words=term.trim().split(/\s+/),urls:string[]=[];if(words.length>=2)urls.push(`https://fishbase.ropensci.org/species?Genus=${encodeURIComponent(words[0])}&Species=${encodeURIComponent(words.slice(1).join(" "))}&limit=6`);urls.push(`https://fishbase.ropensci.org/species?Species=${encodeURIComponent(term)}&limit=6`);const data=await Promise.all(urls.map(u=>fetchJson(u)));const out:Candidate[]=[];for(const j of data)for(const x of(j?.data||[])){const scientific=[x.Genus,x.Species].filter(Boolean).join(" ").trim();if(!scientific||bestScore(scientific,q)<35)continue;out.push({scientific_name:scientific,common_name:x.FBname||x.English||undefined,category:"fish",adult_size_cm:n(x.Length),temperature_min:n(x.TempMin),temperature_max:n(x.TempMax),ph_min:n(x.pHMin),ph_max:n(x.pHMax),gh_min:n(x.dHMin),gh_max:n(x.dHMax),confidence:bestScore(scientific,q)>=80?"high":"medium",verification_status:"online_partial",match_label:bestScore(scientific,q)>=80?"Veľmi blízka zhoda":"Možná zhoda",notes:"Doplnkové biologické údaje."})}return out}
function parsePage(html:string,url:string,q:string,requested:Category):Candidate|null{const text=strip(html),title=strip((/<h1[^>]*>([\s\S]*?)<\/h1>/i.exec(html)?.[1]||/<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1]||q)).replace(/\s*[|–].*$/,'').trim();const sc=Math.max(bestScore(title,q),bestScore(text.slice(0,500),q));if(sc<35)return null;const inferred=categoryFromName(title,requested);if(requested!=="other"&&inferred!==requested)return null;const temp=range(text,"optimálna teplota vody|teplota vody|temperature"),ph=range(text,"požadované pH|pH"),gh=range(text,"celková tvrdosť vody|GH|dGH|hardness"),kh=range(text,"uhličitanová tvrdosť|KH|dKH");const validPh=ph&&ph[0]>=3&&ph[1]<=10?ph:null;const size=upper(text,"max\\.? veľkosť|maximálna veľkosť|adult size|size"),tank=upper(text,"akvárium od|nádrž od|minimálny objem|min\\.? tank"),group=upper(text,"minimálny počet|min\\.? počet|minimálna skupina|skupina od");const shrimpSafe=/bezpečn.{0,25}(?:aj )?(?:ku|k) (?:mladým )?krevet|vhodn.{0,30}(?:ku|k) krevet/i.test(text)?true:/nevhodn.{0,30}(?:ku|k) krevet|lov.{0,30}krevet/i.test(text)?false:undefined;return{scientific_name:title,category:requested==="other"?inferred:requested,adult_size_cm:size,min_tank_l:tank,min_group_size:group,temperature_min:temp?.[0],temperature_max:temp?.[1],ph_min:validPh?.[0],ph_max:validPh?.[1],gh_min:gh?.[0],gh_max:gh?.[1]??upper(text,"celková tvrdosť vody|GH|dGH"),kh_min:kh?.[0],kh_max:kh?.[1]??upper(text,"uhličitanová tvrdosť|KH|dKH"),shrimp_safe:shrimpSafe,shrimp_safety_note:shrimpSafe===true?"Dostupné údaje uvádzajú kompatibilitu s krevetami.":shrimpSafe===false?"Dostupné údaje upozorňujú na riziko pre krevety.":undefined,confidence:"medium",verification_status:"online_partial",match_label:sc>=80?"Presná alebo veľmi blízka zhoda":"Možná zhoda",notes:"Údaje boli dohľadané online. Neznáme hodnoty zostávajú prázdne."}}
async function fetchCandidate(url:string,q:string,cat:Category){try{const r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0"},cache:"no-store",signal:AbortSignal.timeout(2400),redirect:"follow"});if(!r.ok)return null;return parsePage(await r.text(),r.url||url,q,cat)}catch{return null}}
async function webCandidates(q:string,cat:Category){const direct=[`https://www.shrimp.sk/${slug(q)}`,`https://www.invitalshop.sk/${slug(q)}`];if(/neritina/.test(norm(q)))direct.unshift("https://www.shrimp.sk/slimak-neritina-zebra");const directResults=await Promise.all([...new Set(direct)].map(u=>fetchCandidate(u,q,cat)));const searches=[`site:shrimp.sk "${q}"`,`site:invitalshop.sk "${q}" aquarium`];const searchHtml=await Promise.all(searches.map(async sq=>{try{const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(sq)}`,{headers:{"User-Agent":"Mozilla/5.0"},cache:"no-store",signal:AbortSignal.timeout(2200)});return r.ok?await r.text():""}catch{return""}}));const links=[...new Set(searchHtml.flatMap(html=>[...html.matchAll(/class="result__a"[^>]*href="([^"]+)"/gi)].map(m=>unwrap(m[1])).filter(u=>/^https?:/i.test(u)).slice(0,2)))];const pageResults=await Promise.all(links.slice(0,4).map(u=>fetchCandidate(u,q,cat)));return [...directResults,...pageResults].filter(Boolean) as Candidate[]}
function mergeCandidates(list:Candidate[],q:string,requested:Category){const uniq=new Map<string,Candidate>();for(const x of list){if(requested!=="other"&&x.category!==requested)continue;const k=norm(x.scientific_name||x.common_name||"");if(!k)continue;const old=uniq.get(k);if(!old){uniq.set(k,x);continue}const fill:any={...old};for(const[key,val]of Object.entries(x))if((fill[key]===undefined||fill[key]===null||fill[key]==="")&&val!==undefined&&val!==null&&val!=="")fill[key]=val;if(old.confidence!=="high"&&x.confidence==="high")fill.confidence="high";uniq.set(k,fill)}return [...uniq.values()].filter(x=>Math.max(bestScore(x.scientific_name,q),bestScore(x.common_name||"",q))>=35).sort((a,b)=>Math.max(bestScore(b.scientific_name,q),bestScore(b.common_name||"",q))-Math.max(bestScore(a.scientific_name,q),bestScore(a.common_name||"",q))).slice(0,10)}
export async function GET(req:NextRequest){const q=(req.nextUrl.searchParams.get("q")||"").trim();const requested=(req.nextUrl.searchParams.get("category")||"other") as Category;if(q.length<2)return NextResponse.json({items:[]});try{const primary=verifiedMatches(q,requested);if(primary.some(x=>Math.max(bestScore(x.scientific_name,q),bestScore(x.common_name||"",q))>=80))return NextResponse.json({items:primary});const s=await createServerSupabaseClient();const safe=q.replace(/[%(),]/g," ").trim();let {data:catalog}=await s.from("livestock_catalog").select("*").or(`scientific_name.ilike.%${safe}%,common_name.ilike.%${safe}%,variant.ilike.%${safe}%`).limit(12);catalog=(catalog||[]).filter((x:any)=>(requested==="other"||x.category===requested)&&Math.max(bestScore(x.scientific_name||"",q),bestScore(x.common_name||"",q))>=35).map((x:any)=>({...x,confidence:Math.max(bestScore(x.scientific_name||"",q),bestScore(x.common_name||"",q))>=80?"high":"medium",match_label:"Zhoda v katalógu"}));const [taxonomy,online,fish]=await Promise.all([inaturalist(q,requested),webCandidates(q,requested),requested==="fish"||requested==="other"?fishbase(q):Promise.resolve([])]);const items=mergeCandidates([...(catalog as Candidate[]),...primary,...online,...fish,...taxonomy],q,requested);return NextResponse.json({items,message:items.length?undefined:"Nenašla sa dostatočne presná zhoda v zvolenej kategórii."})}catch(e:any){return NextResponse.json({items:[],error:e.message},{status:500})}}
