"use client";
import {useEffect,useState} from "react";
import {MessageCircle,RefreshCw,CheckCircle2} from "lucide-react";

type Row={id:string;user_id:string;email:string|null;category:string;message:string;page:string|null;status:'new'|'in_progress'|'resolved'|'ignored';admin_note:string|null;created_at:string;reviewed_at:string|null;reviewed_by:string|null};
const labels:Record<string,string>={feedback:'Spätná väzba',bug:'Chyba',idea:'Nápad'};
const statusLabels:Record<string,string>={new:'Nový',in_progress:'Rieši sa',resolved:'Vyriešené',ignored:'Ignorované'};

export default function AdminFeedback(){
 const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[showAll,setShowAll]=useState(false),[msg,setMsg]=useState('');
 async function load(){setLoading(true);setMsg('');try{const r=await fetch(`/api/admin/feedback${showAll?'?all=1':''}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'load_failed');setRows(j.items||[])}catch{setMsg('Feedback používateľov sa nepodarilo načítať.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[showAll]);
 async function update(row:Row,status:Row['status'],adminNote?:string){setMsg('');const r=await fetch('/api/admin/feedback',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:row.id,status,adminNote:adminNote??row.admin_note??''})});const j=await r.json().catch(()=>({}));if(!r.ok){setMsg(`Stav feedbacku sa nepodarilo uložiť: ${j.error||'chyba'}`);return}await load()}
 return <section className="card"><div className="section-head"><div><small>ADMIN · FEEDBACK</small><h3><MessageCircle size={18}/> Feedback používateľov</h3></div><button type="button" onClick={()=>load()} disabled={loading}><RefreshCw size={15}/> Obnoviť</button></div><p className="muted">Správy od používateľov z feedback bubliny. Nový feedback zároveň odosiela upozornenie na info@duoakva.sk.</p><label className="settings-check"><input type="checkbox" checked={showAll} onChange={e=>setShowAll(e.target.checked)}/><span>Zobraziť aj vyriešené a ignorované</span></label>{msg&&<div className="notice">{msg}</div>}{loading?<p className="muted">Načítavam…</p>:rows.length===0?<div className="notice"><CheckCircle2 size={16}/> Žiadny {showAll?'feedback':'otvorený feedback'}.</div>:<div style={{display:'grid',gap:10}}>{rows.map(r=><article key={r.id} className="card" style={{margin:0}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div><b>{labels[r.category]||r.category}</b> · <span>{statusLabels[r.status]||r.status}</span><br/><small>{r.email||r.user_id} · sekcia {r.page||'nezadaná'}</small></div><small>{new Date(r.created_at).toLocaleString('sk-SK')}</small></div><p style={{whiteSpace:'pre-wrap',marginBottom:8}}>{r.message}</p><label>Poznámka administrátora<textarea defaultValue={r.admin_note||''} onBlur={e=>{r.admin_note=e.target.value}} placeholder="Interná poznámka k riešeniu…"/></label><div className="form-actions"><button type="button" onClick={()=>update(r,'new')}>Nový</button><button type="button" onClick={()=>update(r,'in_progress')}>Rieši sa</button><button className="primary" type="button" onClick={()=>update(r,'resolved')}>Vyriešené</button><button type="button" onClick={()=>update(r,'ignored')}>Ignorovať</button></div></article>)}</div>}</section>
}
