"use client";
import {useEffect,useState} from "react";
import {AlertTriangle,CheckCircle2,RefreshCw} from "lucide-react";
import {createClient} from "@/lib/supabase/client";

type Row={id:string;severity:string;source:string;module:string;message:string;error_code:string|null;status:string;occurrence_count:number;first_seen_at:string;last_seen_at:string;context:any;admin_note:string|null};
export default function AdminErrorLogs(){
 const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[showResolved,setShowResolved]=useState(false),[msg,setMsg]=useState('');
 async function load(){setLoading(true);setMsg('');let q=createClient().from('application_error_logs').select('id,severity,source,module,message,error_code,status,occurrence_count,first_seen_at,last_seen_at,context,admin_note').order('last_seen_at',{ascending:false}).limit(100);if(!showResolved)q=q.eq('status','open');const{data,error}=await q;setLoading(false);if(error){setMsg('Technické chyby sa nepodarilo načítať.');return}setRows((data||[]) as Row[])}
 useEffect(()=>{void load()},[showResolved]);
 async function setStatus(id:string,status:'resolved'|'ignored'){const s=createClient();const{data:u}=await s.auth.getUser();const{error}=await s.from('application_error_logs').update({status,resolved_at:new Date().toISOString(),resolved_by:u.user?.id||null,updated_at:new Date().toISOString()}).eq('id',id);if(error){setMsg('Stav chyby sa nepodarilo zmeniť.');return}await load()}
 return <section className="card"><div className="section-head"><div><small>ADMIN · DIAGNOSTIKA</small><h3><AlertTriangle size={18}/> Technické chyby aplikácie</h3></div><button type="button" onClick={()=>load()} disabled={loading}><RefreshCw size={15}/> Obnoviť</button></div><label className="settings-check"><input type="checkbox" checked={showResolved} onChange={e=>setShowResolved(e.target.checked)}/><span>Zobraziť aj vyriešené a ignorované</span></label>{msg&&<div className="notice">{msg}</div>}{loading?<p className="muted">Načítavam…</p>:rows.length===0?<div className="notice"><CheckCircle2 size={16}/> Žiadne {showResolved?'zaznamenané':'otvorené'} technické chyby.</div>:<div style={{display:'grid',gap:10}}>{rows.map(r=><article key={r.id} className="card" style={{margin:0}}><div style={{display:'flex',gap:8,justifyContent:'space-between',alignItems:'flex-start',flexWrap:'wrap'}}><div><b>{r.severity==='fatal'?'🔴':r.severity==='warning'?'🟠':'⚠️'} {r.module}</b> <small>{r.error_code||r.source}</small></div><small>{new Date(r.last_seen_at).toLocaleString('sk-SK')} · výskytov {r.occurrence_count}</small></div><p style={{marginBottom:6}}>{r.message}</p><small className="muted">Ref: {r.id.slice(0,8).toUpperCase()} · zdroj {r.source}{r.context?.url?` · ${r.context.url}`:''}</small>{r.status==='open'&&<div className="form-actions"><button className="primary" type="button" onClick={()=>setStatus(r.id,'resolved')}>Označiť vyriešené</button><button type="button" onClick={()=>setStatus(r.id,'ignored')}>Ignorovať</button></div>}</article>)}</div>}</section>
}
