"use client";
import {useState} from "react";
import {Plus,Pencil} from "lucide-react";
import {createClient} from "@/lib/supabase/client";

export type Aquarium={id:string;name:string;net_volume_l:number;aquarium_type:string;water_type:string;water_source?:string;substrate_name?:string;target_temperature_c?:number;height_cm?:number};
const waterSources=["RO (reverzná osmóza)","Vodovodná voda","RO + vodovodná voda","Studničná voda","Destilovaná/demineralizovaná voda","Iný zdroj"];
const commonSubstrates=["INVITAL Japanese Soil Powder","INVITAL Japanese Soil","ADA Aqua Soil Amazonia Ver.2","Tropica Aquarium Soil","Tropica Aquarium Soil Powder","Dennerle Scaper's Soil","JBL ProScape PlantSoil","Seachem Flourite","Inertný štrk","Inertný piesok","Bez substrátu","Iný substrát"];

export default function AquariumsModule({userId,data,setData}:{userId:string;data:Aquarium[];setData:React.Dispatch<React.SetStateAction<Aquarium[]>>}){
 const empty={name:"",net_volume_l:"",height_cm:"",aquarium_type:"planted",water_type:"freshwater",water_source:"RO (reverzná osmóza)",substrate_name:"",target_temperature_c:"24"};
 const[show,setShow]=useState(false);const[busy,setBusy]=useState(false);const[editingId,setEditingId]=useState<string|null>(null);const[waterChoice,setWaterChoice]=useState("RO (reverzná osmóza)");const[substrateChoice,setSubstrateChoice]=useState("");const[form,setForm]=useState(empty);
 function chooseWater(v:string){setWaterChoice(v);setForm({...form,water_source:v==="Iný zdroj"?"":v})}
 function chooseSubstrate(v:string){setSubstrateChoice(v);setForm({...form,substrate_name:v==="Iný substrát"?"":v})}
 function reset(){setEditingId(null);setShow(false);setForm(empty);setWaterChoice("RO (reverzná osmóza)");setSubstrateChoice("")}
 function startEdit(a:Aquarium){setEditingId(a.id);setWaterChoice(waterSources.includes(a.water_source||"")?(a.water_source||""):"Iný zdroj");setSubstrateChoice(commonSubstrates.includes(a.substrate_name||"")?(a.substrate_name||""):"Iný substrát");setForm({name:a.name,net_volume_l:String(a.net_volume_l),height_cm:String(a.height_cm??""),aquarium_type:a.aquarium_type,water_type:a.water_type,water_source:a.water_source||"",substrate_name:a.substrate_name||"",target_temperature_c:String(a.target_temperature_c??24)});setShow(true)}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);const s=createClient();const payload={user_id:userId,name:form.name,net_volume_l:Number(form.net_volume_l),height_cm:form.height_cm?Number(form.height_cm):null,aquarium_type:form.aquarium_type,water_type:form.water_type,water_source:form.water_source,substrate_name:form.substrate_name,target_temperature_c:Number(form.target_temperature_c)};const select="id,name,net_volume_l,aquarium_type,water_type,water_source,substrate_name,target_temperature_c,height_cm";const r=editingId?await s.from("aquariums").update(payload).eq("id",editingId).select(select).single():await s.from("aquariums").insert(payload).select(select).single();setBusy(false);if(r.error)return alert(r.error.message);if(editingId)setData(p=>p.map(x=>x.id===editingId?r.data as Aquarium:x));else setData(p=>[...p,r.data as Aquarium]);reset()}
 return <><div className="toolbar"><p className="muted">Každá nádrž má vlastné merania, techniku, rastliny, osádku, hnojenie a plán údržby.</p><button className="primary" onClick={()=>{reset();setShow(true)}}><Plus size={17}/> Pridať akvárium</button></div>{show&&<section className="card"><h3>{editingId?"Upraviť akvárium":"Nové akvárium"}</h3><form className="form" onSubmit={save}><label>Názov<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Čistý objem (l)<input required type="number" min="1" value={form.net_volume_l} onChange={e=>setForm({...form,net_volume_l:e.target.value})}/></label><label>Výška nádrže (cm)<input type="number" min="1" step="0.1" value={form.height_cm} onChange={e=>setForm({...form,height_cm:e.target.value})}/></label><label>Typ akvária<select value={form.aquarium_type} onChange={e=>setForm({...form,aquarium_type:e.target.value})}><option value="planted">Rastlinné</option><option value="community">Spoločenské</option><option value="shrimp">Krevetkárium</option><option value="biotope">Biotopné</option><option value="marine">Morské</option></select></label><label>Zdroj vody<select value={waterChoice} onChange={e=>chooseWater(e.target.value)}>{waterSources.map(x=><option key={x}>{x}</option>)}</select>{waterChoice==="Iný zdroj"&&<input required value={form.water_source} onChange={e=>setForm({...form,water_source:e.target.value})}/>}</label><label>Substrát<select required value={substrateChoice} onChange={e=>chooseSubstrate(e.target.value)}><option value="">Vyber substrát</option>{commonSubstrates.map(x=><option key={x}>{x}</option>)}</select>{substrateChoice==="Iný substrát"&&<input required value={form.substrate_name} onChange={e=>setForm({...form,substrate_name:e.target.value})}/>}</label><label>Cieľová teplota °C<input type="number" step="0.1" value={form.target_temperature_c} onChange={e=>setForm({...form,target_temperature_c:e.target.value})}/></label><div className="form-actions"><button className="primary" disabled={busy}>{busy?"Ukladám...":"Uložiť"}</button><button type="button" onClick={reset}>Zrušiť</button></div></form></section>}<div className="grid3">{data.map(a=><section className="card" key={a.id}><h3>{a.name}</h3><p><b>{a.net_volume_l} l</b>{a.height_cm?` · výška ${a.height_cm} cm`:""}</p><p>{a.water_source}</p><p className="muted">{a.substrate_name}</p><button onClick={()=>startEdit(a)}><Pencil size={15}/> Upraviť</button></section>)}</div></>
}
