"use client";
import {useEffect,useState} from "react";
import {AlertTriangle,Search,Send,X} from "lucide-react";
import {createPortal} from "react-dom";

type EntityType="fertilizer"|"plant"|"livestock"|"equipment";
type Item=Record<string,any>;
const titles:Record<EntityType,string>={fertilizer:"Nahlásiť chybné dávkovanie",plant:"Nahlásiť nesprávny údaj o rastline",livestock:"Nahlásiť nesprávny údaj o živočíchovi",equipment:"Nahlásiť nesprávny údaj o technike"};
const triggerLabels:Record<EntityType,string>={fertilizer:"Nahlásiť chybné dávkovanie",plant:"Nahlásiť chybný údaj",livestock:"Nahlásiť chybný údaj",equipment:"Nahlásiť chybný údaj"};
function endpoint(t:EntityType,q:string){const p=new URLSearchParams({q,page:"1",pageSize:"12"});if(t==="fertilizer")return`/api/fertilizer-search?${p}`;if(t==="plant")return`/api/plant-search?${p}`;if(t==="livestock")return`/api/livestock-search?${p}`;return`/api/equipment-search?${p}`}
function label(t:EntityType,x:Item){if(t==="fertilizer")return`${x.manufacturer||""} ${x.product_name||""}`.trim();if(t==="plant")return x.scientific_name||x.common_name||"Rastlina";if(t==="livestock")return x.common_name?`${x.common_name} (${x.scientific_name})`:x.scientific_name;return`${x.manufacturer_name||""} ${x.model||""}`.trim()}
function key(t:EntityType,x:Item){if(t==="fertilizer")return`${x.manufacturer||""}|${x.product_name||""}`;if(t==="plant")return x.scientific_name||"";if(t==="livestock")return`${x.scientific_name||""}|${x.variant||""}`;return`${x.category||""}|${x.manufacturer_name||""}|${x.model||""}`}
function current(t:EntityType,x:Item){if(t==="fertilizer"){const effects=Object.entries(x.nutrient_effects||{}).map(([k,v])=>`${k.toUpperCase()} +${v} mg/l`).join(", ");return x.verification_status==="verified"?`${x.reference_dose_ml} ml / ${x.reference_liters} l${effects?` → ${effects}`:""}`:"Dávkovanie nie je označené ako plne overené."}if(t==="plant")return[`svetlo ${x.light_requirement||"—"}`,`CO₂ ${x.co2_requirement||"—"}`,x.ph_min!=null||x.ph_max!=null?`pH ${x.ph_min??"?"}–${x.ph_max??"?"}`:null].filter(Boolean).join(" · ");if(t==="livestock")return[`T ${x.temperature_min??"?"}–${x.temperature_max??"?"} °C`,`pH ${x.ph_min??"?"}–${x.ph_max??"?"}`,`GH ${x.gh_min??"?"}–${x.gh_max??"?"}`].join(" · ");const s=x.specs||{};return Object.keys(s).length?JSON.stringify(s):"Technické parametre zatiaľ nie sú overené."}

export default function CatalogCorrectionPanel({entityType}:{entityType:EntityType}){
 const[open,setOpen]=useState(false),[q,setQ]=useState(""),[items,setItems]=useState<Item[]>([]),[selected,setSelected]=useState<Item|null>(null),[proposed,setProposed]=useState(""),[labelText,setLabelText]=useState(""),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[toolbar,setToolbar]=useState<HTMLElement|null>(null),[mounted,setMounted]=useState(false);
 useEffect(()=>{setMounted(true);const found=document.querySelector("main .toolbar") as HTMLElement|null;setToolbar(found);return()=>setMounted(false)},[entityType]);
 useEffect(()=>{if(!open||q.trim().length<2){setItems([]);return}const t=setTimeout(async()=>{try{const r=await fetch(endpoint(entityType,q.trim()));const j=await r.json();setItems(j.items||[])}catch{setItems([])}},300);return()=>clearTimeout(t)},[q,open,entityType]);
 useEffect(()=>{if(!open)return;const esc=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false)};window.addEventListener("keydown",esc);return()=>window.removeEventListener("keydown",esc)},[open]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!selected||proposed.trim().length<2)return;setBusy(true);setMsg("");try{const r=await fetch("/api/catalog-corrections",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({entityType,entityKey:key(entityType,selected),entityLabel:label(entityType,selected),currentValue:current(entityType,selected),proposedValue:proposed,packageLabelText:labelText,userNote:note})});const j=await r.json();if(!r.ok)throw new Error(j.error);setMsg("Ďakujeme. Hlásenie bolo odoslané administrátorovi na kontrolu.");setProposed("");setLabelText("");setNote("")}catch{setMsg("Hlásenie sa nepodarilo odoslať.")}finally{setBusy(false)}}
 const trigger=<button type="button" onClick={()=>{setOpen(true);setMsg("")}}><AlertTriangle size={16}/>{triggerLabels[entityType]}</button>;
 const modal=open&&mounted?createPortal(<div role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}} style={{position:"fixed",inset:0,zIndex:10000,background:"rgba(9,30,36,.42)",display:"grid",placeItems:"center",padding:16}}><section className="card" role="dialog" aria-modal="true" aria-label={titles[entityType]} style={{width:"min(720px,100%)",maxHeight:"calc(100vh - 32px)",overflowY:"auto",margin:0,boxShadow:"0 24px 70px rgba(0,0,0,.28)"}}><div className="section-head"><div><small>KONTROLA KATALÓGU</small><h3><AlertTriangle size={17}/> {titles[entityType]}</h3></div><button type="button" onClick={()=>setOpen(false)} aria-label="Zavrieť"><X size={18}/></button></div><form className="form one" onSubmit={submit}><label>Vyber položku<div className="searchbox"><Search size={16}/><input value={q} onChange={e=>{setQ(e.target.value);setSelected(null)}} placeholder="Začni písať názov..."/></div></label>{items.length>0&&!selected&&<div className="catalog-results">{items.map((x,i)=><button type="button" className="catalog-result" key={`${key(entityType,x)}-${i}`} onClick={()=>{setSelected(x);setQ(label(entityType,x));setItems([])}}><b>{label(entityType,x)}</b></button>)}</div>}{selected&&<div className="notice"><b>{label(entityType,selected)}</b><p style={{marginBottom:0}}>Aktuálne: {current(entityType,selected)||"—"}</p></div>}<label>{entityType==="fertilizer"?"Správne dávkovanie podľa etikety":"Správny údaj podľa obalu alebo dôveryhodného zdroja"}<input value={proposed} onChange={e=>setProposed(e.target.value)} placeholder={entityType==="fertilizer"?"napr. 5 ml / 125 l = +2 mg/l K":"Zadaj správnu hodnotu"}/></label><label>Presný text z etikety alebo zdroja (voliteľné)<textarea rows={3} value={labelText} onChange={e=>setLabelText(e.target.value)}/></label><label>Poznámka (voliteľné)<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="notice">Hlásenie samo nič v databáze nezmení. Zmenu musí preveriť a schváliť administrátor.</div><div className="form-actions"><button className="primary" disabled={busy||!selected||proposed.trim().length<2}><Send size={15}/>{busy?" Odosielam…":" Odoslať na kontrolu"}</button><button type="button" onClick={()=>setOpen(false)}>Zrušiť</button></div>{msg&&<div className="notice">{msg}</div>}</form></section></div>,document.body):null;
 return <>{mounted&&toolbar?createPortal(trigger,toolbar):trigger}{modal}</>;
}
