"use client";
import {useEffect,useState} from "react";
import {Save,X} from "lucide-react";

type Kind="plant"|"livestock";
type Props={entityType:Kind;entityId:string;entityName:string;initialData?:Record<string,any>|null;onClose:()=>void;onSaved?:()=>void};
const plantLabels:Record<string,string>={common_name:"Bežný názov",difficulty:"Náročnosť",light_requirement:"Nároky na svetlo",co2_requirement:"Nároky na CO₂",growth_rate:"Rýchlosť rastu",placement:"Umiestnenie",ph_min:"pH od",ph_max:"pH do",gh_min:"GH od",gh_max:"GH do",kh_min:"KH od",kh_max:"KH do",temperature_min:"Teplota od (°C)",temperature_max:"Teplota do (°C)",notes:"Poznámka"};
const livestockLabels:Record<string,string>={common_name:"Bežný názov",adult_size_cm:"Dospelá veľkosť (cm)",min_tank_l:"Minimálny objem nádrže (l)",min_group_size:"Minimálna skupina (ks)",recommended_group_size:"Odporúčaná skupina (ks)",temperature_min:"Teplota od (°C)",temperature_max:"Teplota do (°C)",ph_min:"pH od",ph_max:"pH do",gh_min:"GH od",gh_max:"GH do",kh_min:"KH od",kh_max:"KH do",temperament:"Správanie / temperament",swimming_zone:"Zóna plávania",diet:"Potrava",difficulty:"Náročnosť",shrimp_safe:"Bezpečný ku krevetám",snail_safe:"Bezpečný ku slimákom",plant_safe:"Bezpečný k rastlinám",notes:"Poznámka"};
const numeric=new Set(["adult_size_cm","min_tank_l","min_group_size","recommended_group_size","temperature_min","temperature_max","ph_min","ph_max","gh_min","gh_max","kh_min","kh_max"]);
const bools=new Set(["shrimp_safe","snail_safe","plant_safe"]);
export default function CatalogDetailsEditor({entityType,entityId,entityName,initialData,onClose,onSaved}:Props){const[form,setForm]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");const labels=entityType==="plant"?plantLabels:livestockLabels;useEffect(()=>{const next:Record<string,string>={};for(const k of Object.keys(labels)){const v=initialData?.[k];next[k]=typeof v==="boolean"?(v?"true":"false"):v==null?"":String(v)}setForm(next)},[entityId]);async function save(e:React.FormEvent){e.preventDefault();const proposedData:Record<string,any>={};for(const[k,v]of Object.entries(form)){if(v==="")continue;proposedData[k]=numeric.has(k)?Number(v):bools.has(k)?v==="true":v}setBusy(true);setMsg("");try{const r=await fetch("/api/catalog-detail-proposals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({entityType,aquariumEntityId:entityId,entityName,proposedData})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"save_failed");setMsg("Údaje boli uložené pre tvoje akvárium a odoslané administrátorovi na overenie.");onSaved?.()}catch{setMsg("Údaje sa nepodarilo uložiť.")}finally{setBusy(false)}}return <div role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}} style={{position:"fixed",inset:0,zIndex:10000,background:"rgba(9,30,36,.42)",display:"grid",placeItems:"center",padding:16}}><section className="card" role="dialog" aria-modal="true" style={{width:"min(820px,100%)",maxHeight:"calc(100vh - 32px)",overflowY:"auto",margin:0}}><div className="section-head"><div><small>POUŽÍVATEĽSKÉ ÚDAJE</small><h3>Doplniť údaje – {entityName}</h3></div><button type="button" onClick={onClose}><X size={18}/></button></div><form className="form" onSubmit={save}><div className="notice" style={{gridColumn:"1/-1"}}>Vyplň iba údaje, ktoré poznáš. Pre tvoje akvárium sa použijú hneď. Do centrálneho katalógu sa zapíšu až po schválení administrátorom.</div>{Object.entries(labels).map(([k,label])=>bools.has(k)?<label key={k}>{label}<select value={form[k]||""} onChange={e=>setForm(v=>({...v,[k]:e.target.value}))}><option value="">Neuvedené</option><option value="true">Áno</option><option value="false">Nie</option></select></label>:k==="notes"?<label key={k} style={{gridColumn:"1/-1"}}>{label}<textarea rows={3} value={form[k]||""} onChange={e=>setForm(v=>({...v,[k]:e.target.value}))}/></label>:<label key={k}>{label}<input type={numeric.has(k)?"number":"text"} step={numeric.has(k)?"0.1":undefined} min={numeric.has(k)?"0":undefined} value={form[k]||""} onChange={e=>setForm(v=>({...v,[k]:e.target.value}))}/></label>)}<div className="form-actions" style={{gridColumn:"1/-1"}}><button className="primary" disabled={busy}><Save size={15}/>{busy?"Ukladám…":"Uložiť a odoslať na overenie"}</button><button type="button" onClick={onClose}>Zrušiť</button></div>{msg&&<div className="notice" style={{gridColumn:"1/-1"}}>{msg}</div>}</form></section></div>}
