"use client";
import {useEffect,useMemo,useState} from "react";
import {Activity,Bell,Droplets,TriangleAlert,Waves} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import type {Aquarium} from "@/components/AquariumsModule";
type Session={aquarium_id:string;measured_at:string;measurement_values:{parameter_code:string;value:number}[]};
type Task={aquarium_id:string;title:string;due_at:string;completed_at?:string|null};
type Observation={aquarium_id:string;issue_code:string;severity:string;status:string};
const labels:Record<string,string>={ph:'pH',gh:'GH',kh:'KH',no2:'NO₂',no3:'NO₃',po4:'PO₄',fe:'Fe',k:'K',mg:'Mg',tds:'TDS'};
export default function DashboardModule({aquariums}:{aquariums:Aquarium[]}){
 const[sessions,setSessions]=useState<Session[]>([]);const[tasks,setTasks]=useState<Task[]>([]);const[obs,setObs]=useState<Observation[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{if(!aquariums.length){setLoading(false);return}const s=createClient();const ids=aquariums.map(a=>a.id);const[m,o]=await Promise.all([s.from('measurement_sessions').select('aquarium_id,measured_at,measurement_values(parameter_code,value)').in('aquarium_id',ids).order('measured_at',{ascending:false}).limit(30),s.from('aquarium_observations').select('aquarium_id,issue_code,severity,status').in('aquarium_id',ids).neq('status','resolved')]);if(!m.error)setSessions((m.data||[]) as any);if(!o.error)setObs((o.data||[]) as any);const t=await s.from('aquarium_tasks').select('aquarium_id,title,due_at,completed_at').in('aquarium_id',ids).is('completed_at',null).order('due_at',{ascending:true}).limit(20);if(!t.error)setTasks((t.data||[]) as any);setLoading(false)})()},[aquariums]);
 const latest=useMemo(()=>{const map=new Map<string,Session>();for(const s of sessions)if(!map.has(s.aquarium_id))map.set(s.aquarium_id,s);return map},[sessions]);
 const overdue=tasks.filter(t=>new Date(t.due_at).getTime()<Date.now());
 if(!aquariums.length)return <section className="hero"><div><small>INTELIGENTNÝ AKVARISTICKÝ DENNÍK</small><h2>Pridaj svoje prvé akvárium</h2><p>Po vytvorení nádrže tu uvidíš aktuálny stav, merania, úlohy a upozornenia.</p></div><div className="score">DuoAkva</div></section>;
 return <><section className="hero"><div><small>INTELIGENTNÝ AKVARISTICKÝ DENNÍK</small><h2>{aquariums.length===1?'1 aktívne akvárium':`${aquariums.length} aktívne akváriá`}</h2><p>{loading?'Načítavam aktuálny stav…':overdue.length?`Máš ${overdue.length} omeškané ${overdue.length===1?'úlohu':'úlohy'}.`:'Aktuálne údaje sú načítané.'}</p></div><div className="score">DuoAkva</div></section><div className="grid3"><section className="card"><h3><Waves size={18}/> Akváriá</h3>{aquariums.map(a=><p key={a.id}><b>{a.name}</b> · {a.net_volume_l} l</p>)}</section><section className="card"><h3><Bell size={18}/> Úlohy</h3>{tasks.length===0?<p>Žiadne otvorené úlohy.</p>:tasks.slice(0,4).map((t,i)=>{const late=new Date(t.due_at).getTime()<Date.now();return <p key={i}>{late?'🔴':'🟢'} <b>{t.title}</b><br/><span className="muted">{new Date(t.due_at).toLocaleString('sk-SK')}</span></p>})}</section><section className="card"><h3><TriangleAlert size={18}/> Upozornenia</h3>{obs.length===0?<p>🟢 Žiadny aktívny problém.</p>:obs.slice(0,4).map((o,i)=><p key={i}>{o.severity==='strong'?'🔴':o.severity==='moderate'?'🟠':'🟢'} {o.issue_code}</p>)}</section></div><section className="card"><h3><Activity size={18}/> Posledné merania</h3><div className="grid3">{aquariums.map(a=>{const s=latest.get(a.id);const values=(s?.measurement_values||[]).filter(v=>labels[v.parameter_code]).slice(0,6);return <div className="card" key={a.id}><b>{a.name}</b>{!s?<p className="muted">Zatiaľ bez merania.</p>:<><p className="muted">{new Date(s.measured_at).toLocaleString('sk-SK')}</p>{values.map(v=><p key={v.parameter_code}><Droplets size={13}/> {labels[v.parameter_code]}: <b>{Number(v.value)}</b></p>)}</>}</div>})}</div></section></>;
}
