"use client";
import {useEffect,useMemo,useState} from "react";
import {Activity,Bell,Droplets,TriangleAlert,Waves,CheckCircle2,Clock3,Gauge} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import {measurementStatus,measurementStatusLabel} from "@/lib/measurementStatus";
import type {Aquarium} from "@/components/AquariumsModule";
type Session={aquarium_id:string;measured_at:string;measurement_values:{parameter_code:string;value:number}[]};
type Task={aquarium_id:string;title:string;due_at:string;completed_at?:string|null};
type Observation={aquarium_id:string;issue_code:string;severity:string;status:string};
type Alert={aquarium_id:string;level:'red'|'orange';title:string;detail:string};
type AquariumState={label:string;detail:string;cls:string;dot:string;level:'green'|'orange'|'red'};
const labels:Record<string,string>={ph:'pH',gh:'GH',kh:'KH',no2:'NO₂',nh3:'NH₃',nh4:'NH₄',no3:'NO₃',po4:'PO₄',fe:'Fe',k:'K',mg:'Mg',tds:'TDS'};
const units:Record<string,string>={gh:' °dGH',kh:' °dKH',no2:' mg/l',nh3:' mg/l',nh4:' mg/l',no3:' mg/l',po4:' mg/l',fe:' mg/l',k:' mg/l',mg:' mg/l',tds:' ppm'};
const issueLabels:Record<string,string>={bba:'Čierna štetinková riasa BBA',cyanobacteria:'Sinice BGA',cladophora:'Cladophora',brown:'Hnedá riasa',green_dust:'Zelená prachová riasa GDA',green_spot:'Zelená fľekovitá riasa GSA',green_water:'Zelená voda',hair:'Vláknitá riasa',oedogonium:'Oedogonium',rhizoclonium:'Rhizoclonium',spirogyra:'Spirogyry',staghorn:'Staghorn',other:'Iný problém'};
const statusPriority=['no2','nh3','nh4','ph','no3','po4','gh','kh','temperature','o2','tds','ec','fe','k','mg','ca'];
export default function DashboardModule({aquariums}:{aquariums:Aquarium[]}){
 const[sessions,setSessions]=useState<Session[]>([]);const[tasks,setTasks]=useState<Task[]>([]);const[obs,setObs]=useState<Observation[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{if(!aquariums.length){setLoading(false);return}setLoading(true);const s=createClient();const ids=aquariums.map(a=>a.id);const[m,o]=await Promise.all([s.from('measurement_sessions').select('aquarium_id,measured_at,measurement_values(parameter_code,value)').in('aquarium_id',ids).order('measured_at',{ascending:false}).limit(60),s.from('aquarium_observations').select('aquarium_id,issue_code,severity,status').in('aquarium_id',ids).neq('status','resolved')]);if(!m.error)setSessions((m.data||[]) as any);if(!o.error)setObs((o.data||[]) as any);const t=await s.from('aquarium_tasks').select('aquarium_id,title,due_at,completed_at').in('aquarium_id',ids).is('completed_at',null).order('due_at',{ascending:true}).limit(20);if(!t.error)setTasks((t.data||[]) as any);setLoading(false)})()},[aquariums]);
 const aquariumNames=useMemo(()=>Object.fromEntries(aquariums.map(a=>[a.id,a.name])),[aquariums]);
 const latest=useMemo(()=>{const map=new Map<string,Session>();for(const s of sessions)if(!map.has(s.aquarium_id))map.set(s.aquarium_id,s);return map},[sessions]);
 const waterAlerts=useMemo(()=>{const out:Alert[]=[];for(const a of aquariums){const s=latest.get(a.id);if(!s)continue;const v=Object.fromEntries((s.measurement_values||[]).map(x=>[x.parameter_code,Number(x.value)])) as Record<string,number>;let internalScore=0;const why:string[]=[];if((v.no2||0)>0){internalScore+=45;why.push(`NO₂ ${v.no2} mg/l`)}if((v.nh3||0)>0||(v.nh4||0)>0){internalScore+=45;why.push('NH₃/NH₄ je nad nulou')}if((v.no3||0)>=30){internalScore+=25;why.push(`NO₃ ${v.no3} mg/l`)}if((v.po4||0)>=2){internalScore+=12;why.push(`PO₄ ${v.po4} mg/l`)}if(internalScore>=70)out.push({aquarium_id:a.id,level:'red',title:'Urgentná výmena vody',detail:`Odporúčaná výmena približne 45 %. ${why.join(' · ')}`});else if(internalScore>=45)out.push({aquarium_id:a.id,level:'orange',title:'Voda vyžaduje pozornosť',detail:`Odporúčaná výmena približne 35 %. ${why.join(' · ')}`});else if(internalScore>=25)out.push({aquarium_id:a.id,level:'orange',title:'Zváž výmenu vody',detail:`Odporúčaná výmena približne 25 %. ${why.join(' · ')}`})}return out},[aquariums,latest]);
 const observationAlerts=useMemo(()=>obs.map(o=>({aquarium_id:o.aquarium_id,level:(o.severity==='strong'?'red':'orange') as 'red'|'orange',title:issueLabels[o.issue_code]||o.issue_code,detail:o.status==='worsening'?'Výskyt sa zhoršuje.':'Aktívne pozorovanie v údržbe.'})),[obs]);
 const alerts=[...waterAlerts,...observationAlerts];const overdue=tasks.filter(t=>new Date(t.due_at).getTime()<Date.now());
 function stateFor(id:string):AquariumState{
  const ownAlerts=alerts.filter(a=>a.aquarium_id===id);const s=latest.get(id);
  if(!s)return{label:'Vyžaduje pozornosť',detail:'Chýba prvé meranie vody',cls:'status-orange',dot:'🟠',level:'orange'};
  const values=(s.measurement_values||[]).map(v=>({...v,status:measurementStatus(v.parameter_code,Number(v.value))}));
  const sorted=values.slice().sort((a,b)=>statusPriority.indexOf(a.parameter_code)-statusPriority.indexOf(b.parameter_code));
  const bad=sorted.find(v=>v.status==='bad');
  if(bad){const name=labels[bad.parameter_code]||bad.parameter_code.toUpperCase();return{label:`${name} mimo rozsahu`,detail:`${name} ${Number(bad.value)}${units[bad.parameter_code]||''}`,cls:'status-red',dot:'🔴',level:'red'}}
  if(ownAlerts.some(a=>a.level==='red')){const a=ownAlerts.find(a=>a.level==='red')!;return{label:'Vyžaduje zásah',detail:a.title,cls:'status-red',dot:'🔴',level:'red'}}
  const warning=sorted.find(v=>v.status==='warning');
  if(warning){const name=labels[warning.parameter_code]||warning.parameter_code.toUpperCase();return{label:'Vyžaduje pozornosť',detail:`${name} je na hranici odporúčaného rozsahu`,cls:'status-orange',dot:'🟠',level:'orange'}}
  if(ownAlerts.length){return{label:'Vyžaduje pozornosť',detail:ownAlerts[0].title,cls:'status-orange',dot:'🟠',level:'orange'}}
  return{label:'V poriadku',detail:'Posledné dostupné údaje sú v odporúčanom rozsahu',cls:'status-green',dot:'🟢',level:'green'};
 }
 const states=useMemo(()=>Object.fromEntries(aquariums.map(a=>[a.id,stateFor(a.id)])),[aquariums,latest,alerts]);
 const urgent=Object.values(states).filter(s=>s.level==='red').length;const healthy=Object.values(states).filter(s=>s.level==='green').length;
 if(!aquariums.length)return <section className="hero"><div><small>INTELIGENTNÝ AKVARISTICKÝ DENNÍK</small><h2>Pridaj svoje prvé akvárium</h2><p>Po vytvorení nádrže tu uvidíš aktuálny stav, merania, úlohy a upozornenia.</p></div><div className="score">DuoAkva</div></section>;
 return <><section className="hero"><div><small>INTELIGENTNÝ AKVARISTICKÝ DENNÍK</small><h2>{urgent?`${urgent} ${urgent===1?'nádrž vyžaduje':'nádrže vyžadujú'} zásah`:healthy===aquariums.length?'Všetky akváriá sú pod kontrolou':'Prehľad všetkých akvárií'}</h2><p>{loading?'Načítavam aktuálny stav…':urgent?'Najprv skontroluj červené nádrže a ich posledné merania.':overdue.length?`Máš ${overdue.length} omeškané ${overdue.length===1?'úlohu':'úlohy'}.`:'Stav každej nádrže vyhodnocujeme z posledných dostupných meraní a aktívnych pozorovaní.'}</p></div><div className="score">DuoAkva</div></section>
 <div className="summary-grid"><div className="summary-tile"><Waves/><span><b>{aquariums.length}</b><small>aktívne nádrže</small></span></div><div className="summary-tile"><TriangleAlert/><span><b>{urgent}</b><small>vyžadujú zásah</small></span></div><div className="summary-tile"><Clock3/><span><b>{overdue.length}</b><small>omeškané úlohy</small></span></div><div className="summary-tile"><CheckCircle2/><span><b>{healthy}</b><small>v poriadku</small></span></div></div>
 <section className="card"><div className="section-head"><div><small>DASHBOARD VŠETKÝCH AKVÁRIÍ</small><h3><Gauge size={18}/> Aktuálny stav nádrží</h3></div></div><div className="aquarium-status-grid">{aquariums.map(a=>{const s=latest.get(a.id);const st=states[a.id];const key=(s?.measurement_values||[]).filter(v=>['ph','gh','kh','no2','no3'].includes(v.parameter_code));return <article className={`aquarium-status aquarium-status-${st.level}`} key={a.id}><div className="aquarium-status-top"><div><b>{a.name}</b><small>{a.net_volume_l} l</small></div><span className={`status-pill ${st.cls}`}>{st.dot} {st.label}</span></div><p className="aquarium-status-reason">{st.detail}</p>{s?<><div className="parameter-chips">{key.map(v=>{const status=measurementStatus(v.parameter_code,Number(v.value));return <span className={`status-${status}`} title={measurementStatusLabel(status)} key={v.parameter_code}><small>{labels[v.parameter_code]}</small><b>{Number(v.value)}{units[v.parameter_code]||''}</b></span>})}</div><small>Posledné meranie: {new Date(s.measured_at).toLocaleString('sk-SK')}</small></>:<p className="muted">Pridaj prvé meranie, aby DuoAkva Diary vedelo vyhodnotiť stav nádrže.</p>}</article>})}</div></section>
 <div className="dashboard-two"><section className="card"><div className="section-head"><div><small>PRIORITA</small><h3><TriangleAlert size={18}/> Upozornenia</h3></div></div>{alerts.length===0?<div className="empty-good">🟢 <div><b>Žiadny aktívny problém</b><small>Podľa dostupných údajov netreba mimoriadny zásah.</small></div></div>:alerts.slice(0,6).map((a,i)=><div className={`alert-row ${a.level==='red'?'alert-red':'alert-orange'}`} key={i}><span>{a.level==='red'?'🔴':'🟠'}</span><div><small className="aquarium-context-label">Akvárium · <b>{aquariumNames[a.aquarium_id]||'Neznáma nádrž'}</b></small><b>{a.title}</b><small>{a.detail}</small></div></div>)}</section><section className="card"><div className="section-head"><div><small>PLÁN</small><h3><Bell size={18}/> Najbližšie úlohy</h3></div></div>{tasks.length===0?<div className="empty-good">✓ <div><b>Žiadne otvorené úlohy</b><small>Momentálne nemáš nič naplánované.</small></div></div>:tasks.slice(0,6).map((t,i)=>{const late=new Date(t.due_at).getTime()<Date.now();return <div className={`task-row ${late?'task-late':''}`} key={i}><span>{late?'🔴':'🟢'}</span><div><small className="aquarium-context-label">Akvárium · <b>{aquariumNames[t.aquarium_id]||'Neznáma nádrž'}</b></small><b>{t.title}</b><small>{late?'Po termíne · ':''}{new Date(t.due_at).toLocaleString('sk-SK')}</small></div></div>})}</section></div>
 <section className="card"><div className="section-head"><div><small>HISTÓRIA</small><h3><Activity size={18}/> Posledné merania</h3></div></div><div className="grid3">{aquariums.map(a=>{const s=latest.get(a.id);const values=(s?.measurement_values||[]).filter(v=>labels[v.parameter_code]).slice(0,8);return <div className="measurement-card" key={a.id}><b>{a.name}</b>{!s?<p className="muted">Zatiaľ bez merania.</p>:<><small>{new Date(s.measured_at).toLocaleString('sk-SK')}</small><div className="measurement-mini-grid">{values.map(v=>{const status=measurementStatus(v.parameter_code,Number(v.value));return <span className={`status-${status}`} title={measurementStatusLabel(status)} key={v.parameter_code}><Droplets size={12}/><small>{labels[v.parameter_code]}</small><b>{Number(v.value)}{units[v.parameter_code]||''}</b></span>})}</div></>}</div>})}</div></section></>;
}
