"use client";
import {useEffect,useState} from "react";
import {ChevronDown,ChevronUp,ImageIcon,ImagePlus,Trash2} from "lucide-react";
import {createPortal} from "react-dom";
import {createClient} from "@/lib/supabase/client";
import type {Aquarium} from "@/components/AquariumsModule";

type Row={id:string;category:string;manufacturer?:string|null;model:string;specs:any;settings:any;notes?:string|null;user_image_url?:string|null};
function storagePath(url?:string|null){if(!url)return null;const marker='/object/public/entity-photos/';const i=url.indexOf(marker);return i>=0?decodeURIComponent(url.slice(i+marker.length)):null}
function detailRows(r:Row){const s=r.specs||{},v=r.settings||{};const out:Array<[string,string]>=[];const add=(l:string,x:any,u='')=>{if(x!==undefined&&x!==null&&x!=='')out.push([l,`${x}${u}`])};add('Nominálny prietok',s.nominal_flow_lph,' l/h');add('Príkon',s.power_w,' W');add('Výkon svetla',s.light_w,' W');add('Technológia',s.light_technology);add('Spektrum',s.light_spectrum);add('Intenzita',v.intensity_pct,' %');add('Fotoperióda',v.photoperiod_hours,' h/deň');add('PAR pri 100 %',s.par_at_100_umol_m2_s);add('PAR vzdialenosť',s.par_reference_depth_cm,' cm');add('Výkon ohrievača',s.heater_w,' W');add('CO₂ fľaša',s.cylinder_kg,' kg');return out}
export default function EquipmentCardEnhancer({aquariums}:{aquariums:Aquarium[]}){
 const[aquariumId,setAquariumId]=useState(aquariums[0]?.id||'');const[rows,setRows]=useState<Row[]>([]);const[targets,setTargets]=useState<HTMLElement[]>([]);const[expanded,setExpanded]=useState<Record<string,boolean>>({});const[uploading,setUploading]=useState<string|null>(null);
 useEffect(()=>{if(!aquariumId&&aquariums[0])setAquariumId(aquariums[0].id)},[aquariums,aquariumId]);
 useEffect(()=>{if(!aquariumId)return;let active=true;(async()=>{const{data}=await createClient().from('aquarium_equipment').select('id,category,manufacturer,model,specs,settings,notes,user_image_url').eq('aquarium_id',aquariumId).eq('active',true).order('created_at');if(active)setRows((data||[]) as Row[])})();return()=>{active=false}},[aquariumId]);
 useEffect(()=>{const scan=()=>setTargets(Array.from(document.querySelectorAll<HTMLElement>('.v1-equipment .equipment-card')));scan();const root=document.querySelector('.v1-equipment');if(!root)return;const o=new MutationObserver(scan);o.observe(root,{childList:true,subtree:true});return()=>o.disconnect()},[rows.length]);
 async function upload(r:Row,file?:File){if(!file)return;if(!file.type.startsWith('image/'))return alert('Vyber obrázok.');if(file.size>8*1024*1024)return alert('Fotografia môže mať maximálne 8 MB.');setUploading(r.id);const s=createClient();try{const{data:{user}}=await s.auth.getUser();if(!user)throw new Error('Nie si prihlásený.');const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-zA-Z0-9]/g,'').toLowerCase()||'jpg';const path=`${user.id}/equipment/${r.id}/${Date.now()}.${ext}`;const up=await s.storage.from('entity-photos').upload(path,file,{cacheControl:'3600',upsert:false});if(up.error)throw up.error;const{data:pub}=s.storage.from('entity-photos').getPublicUrl(path);const db=await s.from('aquarium_equipment').update({user_image_url:pub.publicUrl}).eq('id',r.id);if(db.error){await s.storage.from('entity-photos').remove([path]);throw db.error}const old=storagePath(r.user_image_url);if(old)await s.storage.from('entity-photos').remove([old]);setRows(v=>v.map(x=>x.id===r.id?{...x,user_image_url:pub.publicUrl}:x))}catch(e:any){alert(e?.message||'Fotografiu sa nepodarilo nahrať.')}finally{setUploading(null)}}
 async function removePhoto(r:Row){if(!r.user_image_url||!confirm('Odstrániť fotografiu zariadenia?'))return;setUploading(r.id);const s=createClient();try{const db=await s.from('aquarium_equipment').update({user_image_url:null}).eq('id',r.id);if(db.error)throw db.error;const p=storagePath(r.user_image_url);if(p)await s.storage.from('entity-photos').remove([p]);setRows(v=>v.map(x=>x.id===r.id?{...x,user_image_url:null}:x))}catch(e:any){alert(e?.message||'Fotografiu sa nepodarilo odstrániť.')}finally{setUploading(null)}}
 return <>{rows.map((r,i)=>targets[i]?createPortal(<div className="equipment-v1-enhance"><div className="equipment-v1-photo">{r.user_image_url?<img src={r.user_image_url} alt={`${r.manufacturer||''} ${r.model}`.trim()}/>:<div className="equipment-v1-photo-empty"><ImageIcon/>TECHNIKA</div>}<label className="equipment-v1-photo-action"><ImagePlus/>{uploading===r.id?'Nahrávam…':r.user_image_url?'Zmeniť foto':'Pridať foto'}<input type="file" accept="image/*" disabled={uploading===r.id} onChange={e=>upload(r,e.target.files?.[0])}/></label>{r.user_image_url&&<button className="equipment-v1-photo-remove" disabled={uploading===r.id} onClick={()=>removePhoto(r)} title="Odstrániť fotografiu"><Trash2/></button>}</div><button className="equipment-v1-expand" type="button" onClick={()=>setExpanded(v=>({...v,[r.id]:!v[r.id]}))}>{expanded[r.id]?'Skryť detail':'Zobraziť detail'}{expanded[r.id]?<ChevronUp/>:<ChevronDown/>}</button>{expanded[r.id]&&<div className="equipment-v1-detail">{detailRows(r).map(([l,v])=><div className="equipment-v1-info" key={l}><small>{l}</small><b>{v}</b></div>)}{r.notes&&<div className="equipment-v1-notes"><small>Poznámka</small><p>{r.notes}</p></div>}</div>}</div>,targets[i],r.id):null)}</>}
