"use client";
import {useState} from "react";
import {MessageCircle,X,Send} from "lucide-react";

export default function FeedbackBubble({userId,email,page}:{userId:string;email:string;page:string}){
 const[open,setOpen]=useState(false);const[category,setCategory]=useState<'feedback'|'bug'|'idea'>('feedback');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();const text=message.trim();if(text.length<3){setMsg('Napíš prosím aspoň krátku správu.');return}setBusy(true);setMsg('');try{const r=await fetch('/api/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({category,message:text,page})});const j=await r.json().catch(()=>({}));if(!r.ok){setMsg('Feedback sa nepodarilo odoslať. Skús to prosím znova.');return}setMessage('');setCategory('feedback');setMsg(j.emailSent===false?'Ďakujeme. Feedback bol uložený.':'Ďakujeme. Feedback bol odoslaný.')}catch{setMsg('Feedback sa nepodarilo odoslať. Skús to prosím znova.')}finally{setBusy(false)}}
 if(!userId)return null;
 return <><button className="feedback-fab" onClick={()=>setOpen(v=>!v)} aria-label="Poslať feedback">{open?<X size={21}/>:<MessageCircle size={21}/>}</button>{open&&<section className="feedback-panel"><div className="section-head"><div><small>DUOAKVA DIARY</small><h3>Feedback</h3></div><button onClick={()=>setOpen(false)} aria-label="Zavrieť"><X size={16}/></button></div><p className="muted">Našiel si chybu alebo máš nápad na zlepšenie? Napíš nám priamo odtiaľto.</p><form className="form one" onSubmit={submit}><label>Typ<select value={category} onChange={e=>setCategory(e.target.value as any)}><option value="feedback">Spätná väzba</option><option value="bug">Nahlásiť chybu</option><option value="idea">Nápad na funkciu</option></select></label><label>Správa<textarea maxLength={2000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Čo by sme mali opraviť alebo zlepšiť?"/></label><small className="muted">Aktuálna sekcia: {page}{email?` · ${email}`:''}</small><button className="primary" disabled={busy}><Send size={15}/>{busy?' Odosielam…':' Odoslať feedback'}</button></form>{msg&&<div className="notice">{msg}</div>}</section>}</>;
}
