"use client";
import {useEffect,useState} from "react";
import {ImageIcon,ImagePlus,Trash2} from "lucide-react";
import {createPortal} from "react-dom";
import {createClient} from "@/lib/supabase/client";
type Aquarium={id:string;name:string};type Row={id:string;custom_name?:string|null;user_image_url?:string|null;fertilizer_catalog?:{manufacturer?:string|null;product_name?:string|null}|null};
function storagePath(url?:string|null){if(!url)return null;const marker='/object/public/entity-photos/';const i=url.indexOf(marker);return i>=0?decodeURIComponent(url.slice(i+marker.length)):null}
function norm(v:string){return v.replace(/\s+/g,' ').trim().toLowerCase()}
function nameOf(r:Row){return r.fertilizer_catalog?`${r.fertilizer_catalog.manufacturer||''} ${r.fertilizer_catalog.product_name||''}`.trim():(r.custom_name||'')}
function targetFor(r:Row,targets:HTMLElement[]){const full=norm(nameOf(r));const product=norm(r.fertilizer_catalog?.product_name||r.custom_name||'');return targets.find(t=>{const text=norm(t.textContent||'');return !!((full&&text.includes(full))||(product&&text.includes(product)))})}
export default function FertilizerPhotoEnhancer({aquariums}:{aquariums:Aquarium[]}){const[aquariumId,setAquariumId]=useState(aquariums[0]?.id||"");const[rows,setRows]=useState<Row[]>([]);const[targets,setTargets]=useState<HTMLElement[]>([]);const[uploadingId,setUploadingId]=useState<string|null>(null);useEffect(()=>{if(!aquariumId&&aquariums[0])setAquariumId(aquariums[0].id)},[aquariums,aquariumId]);useEffect(()=>{const valid=new Set(aquariums.map(a=>a.id));const onChange=(e:Event)=>{const el=e.target as HTMLSelectElement;if(el?.tagName==='SELECT'&&el.closest('.v1-fertilizers')&&valid.has(el.value))setAquariumId(el.value)};document.addEventListener('change',onChange);return()=>document.removeEventListener('change',onChange)},[aquariums]);
 useEffect(()=>{if(!aquariumId)return;let active=true;let timer:number|undefined;const scan=()=>setTargets(Array.from(document.querySelectorAll<HTMLElement>('.v1-fertilizers .grid3 > .card')));const load=async()=>{const{data}=await createClient().from('aquarium_fertilizers').select('id,custom_name,user_image_url,fertilizer_catalog(manufacturer,product_name)').eq('aquarium_id',aquariumId).eq('available',true).order('created_at');if(active){setRows((data||[]) as any);requestAnimationFrame(scan)}};const refresh=()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>{load();scan()},40)};load();scan();const root=document.querySelector('.v1-fertilizers');const mo=root?new MutationObserver(refresh):null;if(root)mo?.observe(root,{childList:true,subtree:true});window.addEventListener('duoakva-fertilizer-data-updated',refresh);return()=>{active=false;window.clearTimeout(timer);mo?.disconnect();window.removeEventListener('duoakva-fertilizer-data-updated',refresh)}},[aquariumId]);
 async function uploadPhoto(r:Row,file?:File){if(!file)return;if(!file.type.startsWith('image/'))return alert('Vyber obrázok.');if(file.size>8*1024*1024)return alert('Fotografia môže mať maximálne 8 MB.');setUploadingId(r.id);const s=createClient();try{const{data:{user}}=await s.auth.getUser();if(!user)throw new Error('Nie si prihlásený.');const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-zA-Z0-9]/g,'').toLowerCase()||'jpg';const path=`${user.id}/fertilizers/${r.id}/${Date.now()}.${ext}`;const up=await s.storage.from('entity-photos').upload(path,file,{cacheControl:'3600',upsert:false});if(up.error)throw up.error;const{data:pub}=s.storage.from('entity-photos').getPublicUrl(path);const url=pub.publicUrl;const db=await s.from('aquarium_fertilizers').update({user_image_url:url}).eq('id',r.id);if(db.error){await s.storage.from('entity-photos').remove([path]);throw db.error}const old=storagePath(r.user_image_url);if(old&&old!==path)await s.storage.from('entity-photos').remove([old]);setRows(v=>v.map(x=>x.id===r.id?{...x,user_image_url:url}:x))}catch(e:any){alert(e?.message||'Fotografiu sa nepodarilo nahrať.')}finally{setUploadingId(null)}}async function removePhoto(r:Row){if(!r.user_image_url||!confirm('Odstrániť fotografiu hnojiva?'))return;setUploadingId(r.id);const s=createClient();try{const db=await s.from('aquarium_fertilizers').update({user_image_url:null}).eq('id',r.id);if(db.error)throw db.error;const path=storagePath(r.user_image_url);if(path)await s.storage.from('entity-photos').remove([path]);setRows(v=>v.map(x=>x.id===r.id?{...x,user_image_url:null}:x))}catch(e:any){alert(e?.message||'Fotografiu sa nepodarilo odstrániť.')}finally{setUploadingId(null)}}if(typeof document==='undefined')return null;return <>{rows.map(r=>{const target=targetFor(r,targets);if(!target)return null;return createPortal(<div className="fertilizer-photo-layer">{r.user_image_url?<img src={r.user_image_url} alt="Fotografia hnojiva"/>:<div className="fertilizer-photo-empty"><ImageIcon/><span>HNOJIVO</span></div>}<label className="fertilizer-photo-action"><ImagePlus/>{uploadingId===r.id?'Nahrávam…':r.user_image_url?'Zmeniť foto':'Pridať foto'}<input type="file" accept="image/*" disabled={uploadingId===r.id} onChange={e=>uploadPhoto(r,e.target.files?.[0])}/></label>{r.user_image_url&&<button type="button" className="fertilizer-photo-remove" disabled={uploadingId===r.id} onClick={()=>removePhoto(r)} title="Odstrániť fotografiu"><Trash2/></button>}</div>,target,r.id)})}</>}
