"use client";
import {useEffect,useMemo,useState} from "react";
import {Droplets,Trash2} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import type {Aquarium} from "@/components/AquariumsModule";

type Assignment={id:string;custom_name?:string|null;fertilizer_catalog?:{manufacturer?:string|null;product_name:string}|null};
type Dose={id:string;aquarium_fertilizer_id:string|null;dose_ml:number;dosed_at:string;notes?:string|null;source_type:string};
const localNow=()=>{const d=new Date();const z=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`};
const nameOf=(a?:Assignment)=>a?.fertilizer_catalog?`${a.fertilizer_catalog.manufacturer||''} ${a.fertilizer_catalog.product_name}`.trim():a?.custom_name||'Hnojivo';

export default function FertilizerDoseMaintenance({aquariums}:{aquariums:Aquarium[]}){
 const[aquariumId,setAquariumId]=useState(aquariums[0]?.id||'');const[assignments,setAssignments]=useState<Assignment[]>([]);const[doses,setDoses]=useState<Dose[]>([]);const[selectedId,setSelectedId]=useState('');const[amount,setAmount]=useState('');const[dosedAt,setDosedAt]=useState(localNow());const[notes,setNotes]=useState('');const[confirmRecent,setConfirmRecent]=useState(false);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
 useEffect(()=>{if(!aquariumId&&aquariums[0])setAquariumId(aquariums[0].id)},[aquariums,aquariumId]);
 useEffect(()=>{if(aquariumId)load()},[aquariumId]);
 async function load(){setMsg('');const s=createClient();const[a,d]=await Promise.all([s.from('aquarium_fertilizers').select('id,custom_name,fertilizer_catalog(manufacturer,product_name)').eq('aquarium_id',aquariumId).eq('available',true).order('created_at'),s.from('fertilizer_doses').select('id,aquarium_fertilizer_id,dose_ml,dosed_at,notes,source_type').eq('aquarium_id',aquariumId).order('dosed_at',{ascending:false}).limit(50)]);if(a.error)setMsg('Hnojivá sa nepodarilo načítať.');else{const list=(a.data||[]) as any as Assignment[];setAssignments(list);setSelectedId(v=>list.some(x=>x.id===v)?v:(list[0]?.id||''))}if(d.error)setMsg('Históriu dávkovania sa nepodarilo načítať.');else setDoses((d.data||[]) as Dose[]);setConfirmRecent(false)}
 const selected=assignments.find(x=>x.id===selectedId);
 const recent=useMemo(()=>{if(!selectedId)return null;const x=doses.find(d=>d.aquarium_fertilizer_id===selectedId);if(!x)return null;const hours=(Date.now()-new Date(x.dosed_at).getTime())/3600000;return hours<24?{...x,hours}:null},[doses,selectedId]);
 async function save(e:React.FormEvent){e.preventDefault();if(!selectedId||!amount||Number(amount)<=0)return setMsg('Vyber hnojivo a zadaj dávku väčšiu ako 0 ml.');if(recent&&!confirmRecent)return setMsg('Rovnaké hnojivo bolo podané pred menej než 24 hodinami. Pred ďalším zápisom potvrď, že dávku naozaj chceš podať.');setBusy(true);setMsg('');const{error}=await createClient().from('fertilizer_doses').insert({aquarium_id:aquariumId,aquarium_fertilizer_id:selectedId,dose_ml:Number(amount),dosed_at:new Date(dosedAt).toISOString(),source_type:'manual',notes:notes.trim()||null});setBusy(false);if(error)return setMsg('Dávku sa nepodarilo uložiť.');setAmount('');setNotes('');setDosedAt(localNow());setConfirmRecent(false);setMsg('Dávka bola zapísaná do údržby.');await load()}
 async function remove(id:string){if(!confirm('Odstrániť tento záznam dávkovania?'))return;const{error}=await createClient().from('fertilizer_doses').delete().eq('id',id);if(error)return setMsg('Záznam sa nepodarilo odstrániť.');await load()}
 if(!aquariums.length)return null;
 return <section className="card"><div className="section-head"><div><small>ÚDRŽBA</small><h3><Droplets size={18}/> Dávkovanie hnojív</h3></div></div><p className="muted">Sem zapisuj skutočne podanú dávku. Odporúčaná dávka sa počíta v časti Hnojenie; tento denník slúži ako evidencia reálne vykonaného zásahu.</p><div className="form one"><label>Akvárium<select value={aquariumId} onChange={e=>setAquariumId(e.target.value)}>{aquariums.map(a=><option key={a.id} value={a.id}>{a.name} · {a.net_volume_l} l</option>)}</select></label></div>{!assignments.length?<div className="notice">Najprv pridaj hnojivo v časti Hnojenie.</div>:<form className="form" onSubmit={save}><label>Hnojivo<select value={selectedId} onChange={e=>{setSelectedId(e.target.value);setConfirmRecent(false)}}>{assignments.map(a=><option key={a.id} value={a.id}>{nameOf(a)}</option>)}</select></label><label>Skutočne podaná dávka (ml)<input type="number" min="0.01" step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Dátum a čas<input type="datetime-local" required value={dosedAt} onChange={e=>setDosedAt(e.target.value)}/></label><label>Poznámka<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="napr. po meraní NO₃/PO₄"/></label>{recent&&<div className="notice"><b>⚠️ {nameOf(selected)} bolo dávkované pred {recent.hours<1?'menej než hodinou':`${Math.floor(recent.hours)} h`}.</b><p>Posledná dávka bola {recent.dose_ml} ml ({new Date(recent.dosed_at).toLocaleString('sk-SK')}). Opakované dávkovanie bez nového merania môže viesť k nepresnej korekcii alebo predávkovaniu.</p><label style={{display:'flex',alignItems:'flex-start',gap:8,fontWeight:400}}><input type="checkbox" checked={confirmRecent} onChange={e=>setConfirmRecent(e.target.checked)}/><span>Rozumiem upozorneniu a potvrdzujem, že túto ďalšiu dávku chcem skutočne podať.</span></label></div>}<div className="form-actions"><button className="primary" disabled={busy||!!recent&&!confirmRecent}>{busy?'Ukladám…':'Zapísať dávku'}</button></div></form>}{msg&&<div className="notice">{msg}</div>}<h4>História dávkovania</h4>{!doses.length?<p className="muted">Zatiaľ nie je evidovaná žiadna dávka.</p>:<div style={{display:'grid',gap:8}}>{doses.map(d=>{const a=assignments.find(x=>x.id===d.aquarium_fertilizer_id);return <div className="measurement-row" key={d.id}><div><b>{nameOf(a)}</b><small>{new Date(d.dosed_at).toLocaleString('sk-SK')}{d.notes?` · ${d.notes}`:''}</small></div><div className="form-actions"><b>{Number(d.dose_ml)} ml</b><button type="button" className="danger" onClick={()=>remove(d.id)}><Trash2 size={14}/> Odstrániť</button></div></div>})}</div>}</section>;
}
