import Link from "next/link";
import {Camera,FlaskConical,Leaf,LineChart,ShieldCheck,Sparkles,Waves} from "lucide-react";

export default function LandingPage(){return <div className="public-site">
 <nav className="public-nav"><Link href="/" className="public-brand"><span className="brand-mark">◉</span><span>DuoAkva <b>Diary</b></span></Link><div className="public-nav-actions"><a href="https://www.duoakva.sk" target="_blank" rel="noreferrer">DuoAkva e-shop</a><Link className="primary" href="/auth">Prihlásenie / registrácia</Link></div></nav>
 <main className="public-main">
  <section className="landing-hero"><div><span className="eyebrow">INTELIGENTNÝ AKVARISTICKÝ DENNÍK</span><h1>Maj svoje akvárium pod kontrolou.</h1><p>DuoAkva Diary spája merania vody, údržbu, techniku, rastliny, osádku, hnojenie a fotodenník na jednom mieste. AI analýza fotografie pomáha sledovať viditeľný vývoj nádrže a dlhodobé trendy.</p><div className="landing-actions"><Link className="primary" href="/auth">Začať používať DuoAkva Diary</Link><a className="link" href="https://www.duoakva.sk" target="_blank" rel="noreferrer">Navštíviť DuoAkva.sk</a></div><small>Free účet obsahuje 1 akvárium a AI analýzu 1× za 30 dní. Premium odomyká viac nádrží, pokročilé trendy a AI analýzu 1× za 4 dni.</small></div><div className="landing-visual"><div className="landing-logo-orb"><Waves size={54}/><strong>DuoAkva</strong><span>Diary</span></div></div></section>
  <section className="landing-features"><article><FlaskConical/><h3>Merania vody</h3><p>História parametrov, stavové hodnotenie a prehľad vývoja.</p></article><article><Camera/><h3>Fotodenník</h3><p>Časová os nádrže, porovnanie Pred / po a vizuálny vývoj.</p></article><article><Sparkles/><h3>AI analýza</h3><p>Analýza fotografie s kontextom reálnych meraní z denníka.</p></article><article><LineChart/><h3>Trendy</h3><p>Rast rastlín, riasy, čírosť a zarastenosť v čase.</p></article><article><Leaf/><h3>Starostlivosť</h3><p>Rastliny, osádka, hnojenie, RO mineralizácia a údržba.</p></article><article><ShieldCheck/><h3>Súkromné údaje</h3><p>Každý účet pristupuje iba k svojim nádržiam a záznamom.</p></article></section>
 </main>
 <footer className="public-footer"><div><b>Prevádzkovateľ:</b> Duo R&amp;M s. r. o., Vinohrady 631/84, 951 35 Veľké Zálužie<br/>IČO: 53658132 | DIČ: 2121449715 | OR OS Nitra, oddiel Sro, vložka 53838/N<br/><a href="mailto:info@duoakva.sk">info@duoakva.sk</a> | <a href="tel:+421940501575">+421 940 501 575</a></div><div className="footer-links"><Link href="/prevadzkovatel">Prevádzkovateľ</Link><Link href="/ochrana-osobnych-udajov">Ochrana osobných údajov</Link><Link href="/cookies">Cookies</Link><Link href="/podmienky-pouzivania">Podmienky používania</Link></div><small>© 2026 Duo R&amp;M s. r. o. · DuoAkva Diary</small></footer>
 </div>}
