"use client";
import {useEffect,useMemo,useState} from "react";
import {Plus,Trash2,Waves,Filter,PanelTop,Scissors,Sparkles,Wrench,NotebookPen,TriangleAlert,Eye} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import type {Aquarium} from "@/components/AquariumsModule";
type MaintenanceType="water_change"|"filter_clean"|"glass_clean"|"substrate_clean"|"plant_trim"|"equipment"|"other";
type Row={id:string;aquarium_id:string;maintenance_type:MaintenanceType;custom_type?:string|null;performed_at:string;water_change_l?:number|null;water_change_percent?:number|null;notes?:string|null;created_at:string};
type Obs={id:string;issue_code:string;severity:"mild"|"moderate"|"strong";locations:string[];status:string;observed_at:string;notes?:string|null};
type Measure={measured_at:string;values:Record<string,number>};
const types:any[]=[['water_change','Výmena vody',Waves],['filter_clean','Čistenie filtra',Filter],['glass_clean','Čistenie skiel',PanelTop],['substrate_clean','Odkalenie / čistenie dna',Sparkles],['plant_trim','Strih rastlín',Scissors],['equipment','Údržba techniky / CO₂',Wrench],['other','Iná údržba',NotebookPen]].map(([value,label,icon])=>({value,label,icon}));
const algae:any={hair:'Zelená vláknitá riasa',bba:'Čierna štetinková / BBA',cyanobacteria:'Sinica',diatoms:'Rozsievky',green_dust:'Zelený prach',green_spot:'Zelené bodky',water_bloom:'Zákal / zelená voda',other:'Iná / neznáma riasa'};
const locs:any={glass:'Sklo',plants:'Rastliny',substrate:'Substrát',decor:'Dekorácie',whole:'Celé akvárium'};
const labelOf=(t:string,c?:string|null)=>t==='other'&&c?c:(types.find(x=>x.value===t)?.label||t);const fmt=(s:string)=>new Date(s).toLocaleString('sk-SK');const days=(s?:string)=>s?Math.max(0,Math.floor((Date.now()-new Date(s).getTime())/86400000)):null;
export default function MaintenanceModule({aquariums}:{aquariums:Aquarium[]}){
 const[aquariumId,setAquariumId]=useState(aquariums[0]?.id||'');const[rows,setRows]=useState<Row[]>([]);const[obs,setObs]=useState<Obs[]>([]);const[measurements,setMeasurements]=useState<Measure[]>([]);const[livestock,setLivestock]=useState(0);const[plants,setPlants]=useState(0);const[show,setShow]=useState(false);const[showObs,setShowObs]=useState(false);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[type,setType]=useState<MaintenanceType>('water_change');const[customType,setCustomType]=useState('');const[date,setDate]=useState(new Date().toISOString().slice(0,16));const[liters,setLiters]=useState('');const[notes,setNotes]=useState('');const[issue,setIssue]=useState('hair');const[severity,setSeverity]=useState<'mild'|'moderate'|'strong'>('mild');const[locations,setLocations]=useState<string[]>([]);const[obsNotes,setObsNotes]=useState('');
 useEffect(()=>{if(!aquariumId&&aquariums[0])setAquariumId(aquariums[0].id)},[aquariums,aquariumId]);useEffect(()=>{if(aquariumId)load()},[aquariumId]);const aq=aquariums.find(a=>a.id===aquariumId);const percent=aq&&+liters>0?Math.min(100,+liters/aq.net_volume_l*100):0;
 async function load(){setMsg('');const s=createClient();const[r,o,m,l,p]=await Promise.all([s.from('aquarium_maintenance').select('*').eq('aquarium_id',aquariumId).order('performed_at',{ascending:false}).limit(200),s.from('aquarium_observations').select('*').eq('aquarium_id',aquariumId).order('observed_at',{ascending:false}).limit(100),s.from('measurement_sessions').select('measured_at,measurement_values(parameter_code,value)').eq('aquarium_id',aquariumId).order('measured_at',{ascending:false}).limit(6),s.from('aquarium_livestock').select('quantity').eq('aquarium_id',aquariumId),s.from('aquarium_plants').select('quantity').eq('aquarium_id',aquariumId)]);if(r.error)setMsg(r.error.message);else setRows((r.data||[]) as any);if(o.error)setMsg(o.error.message);else setObs((o.data||[]) as any);if(!m.error)setMeasurements((m.data||[]).map((x:any)=>({measured_at:x.measured_at,values:Object.fromEntries((x.measurement_values||[]).map((v:any)=>[v.parameter_code,+v.value]))})));if(!l.error)setLivestock((l.data||[]).reduce((a:any,x:any)=>a+(+x.quantity||1),0));if(!p.error)setPlants((p.data||[]).reduce((a:any,x:any)=>a+(+x.quantity||1),0))}
 const latest=useMemo(()=>{const m=new Map<string,Row>();for(const r of rows)if(!m.has(r.maintenance_type))m.set(r.maintenance_type,r);return m},[rows]);const recommendations=useMemo(()=>{let score=0;const why:string[]=[];const last=latest.get('water_change');const d=days(last?.performed_at);if(d==null){score+=35;why.push('výmena vody ešte nie je evidovaná')}else if(d>14){score+=25;why.push(`posledná výmena bola pred ${d} dňami`)}else if(d>7)score+=10;const cur=measurements[0]?.values||{},prev=measurements[1]?.values||{};if((cur.no2||0)>0){score+=45;why.push(`NO₂ je ${cur.no2} mg/l`)}if((cur.nh3||0)>0||(cur.nh4||0)>0){score+=45;why.push('evidovaný je amoniak/amónium')}if((cur.no3||0)>=30){score+=25;why.push(`NO₃ je ${cur.no3} mg/l`)}else if(cur.no3!=null&&prev.no3!=null&&cur.no3>prev.no3*1.25){score+=12;why.push('NO₃ má rastúci trend')}if((cur.po4||0)>=2){score+=12;why.push(`PO₄ je ${cur.po4} mg/l`)}if(aq&&livestock>aq.net_volume_l/5){score+=10;why.push('osádka vytvára vyššie biologické zaťaženie')}if(plants>10&&score<45)score=Math.max(0,score-5);const active=obs.filter(x=>x.status!=='resolved');if(active.some(x=>x.severity==='strong')){score+=15;why.push('evidovaný je silný výskyt riasy/problému')}else if(active.length){score+=7;why.push('evidovaný je aktívny výskyt riasy/problému')}score=Math.min(100,score);let pct=score>=70?45:score>=45?35:score>=25?25:0;const out:any[]=[];if(score>=25)out.push({title:'Výmena vody',score,text:pct?`Odporúčaná výmena približne ${pct} %.`:'Skontroluj stav vody.',why});if(active.some(x=>['hair','bba','cyanobacteria','diatoms','green_dust','green_spot'].includes(x.issue_code)))out.push({title:'Kontrola riasy',score:Math.max(45,score),text:'Odstráň napadnuté časti mechanicky a skontroluj svetlo, CO₂ a živiny. Rozsah zásahu prispôsob aktuálnym meraniam.',why:['v akváriu je aktívne pozorovanie riasy']});return out.sort((a,b)=>b.score-a.score)},[rows,measurements,livestock,plants,obs,aq]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);const water=type==='water_change'&&+liters>0?+liters:null;const{error}=await createClient().from('aquarium_maintenance').insert({aquarium_id:aquariumId,maintenance_type:type,custom_type:type==='other'?(customType.trim()||'Iná údržba'):null,performed_at:new Date(date).toISOString(),water_change_l:water,water_change_percent:water&&aq?+(water/aq.net_volume_l*100).toFixed(1):null,notes:notes.trim()||null});setBusy(false);if(error)return setMsg(error.message);setShow(false);setLiters('');setNotes('');load()}
 async function saveObservation(e:React.FormEvent){e.preventDefault();setBusy(true);const{error}=await createClient().from('aquarium_observations').insert({aquarium_id:aquariumId,observation_type:'algae',issue_code:issue,severity,locations,notes:obsNotes||null});setBusy(false);if(error)return setMsg(error.message);setShowObs(false);setObsNotes('');setLocations([]);load()}
 async function resolveObs(id:string,status:string){const{error}=await createClient().from('aquarium_observations').update({status}).eq('id',id);if(error)return setMsg(error.message);load()}async function remove(id:string){if(!confirm('Odstrániť tento záznam?'))return;await createClient().from('aquarium_maintenance').delete().eq('id',id);load()}
 if(!aquariums.length)return <section className="card"><h3>Údržba</h3><p>Najprv vytvor akvárium.</p></section>;
 return <><div className="toolbar"><label>Akvárium <select value={aquariumId} onChange={e=>setAquariumId(e.target.value)}>{aquariums.map(a=><option key={a.id} value={a.id}>{a.name} · {a.net_volume_l} l</option>)}</select></label><button className="primary" onClick={()=>setShow(true)}><Plus size={17}/> Zapísať údržbu</button><button onClick={()=>setShowObs(true)}><Eye size={17}/> Nahlásiť riasu / problém</button></div>{msg&&<div className="notice">{msg}</div>}
 <section className="card"><h3>Čo teraz potrebuje pozornosť</h3>{recommendations.length===0?<div className="notice">✅ Podľa aktuálne evidovaných údajov nie je potrebný mimoriadny zásah. Pokračuj v sledovaní trendov vody.</div>:<div style={{display:'grid',gap:10}}>{recommendations.map((r,i)=><div className="card" key={i}><b><TriangleAlert size={16}/> {r.title} · priorita {r.score}/100</b><p>{r.text}</p><p className="muted">Dôvod: {r.why.join(' · ')}</p></div>)}</div>}<p className="muted">Odporúčanie sa prepočítava z histórie údržby, posledných meraní, objemu, evidovanej osádky, rastlín a aktívnych pozorovaní.</p></section>
 {showObs&&<section className="card"><h3>Nahlásiť riasu / problém</h3><form className="form" onSubmit={saveObservation}><label>Druh<select value={issue} onChange={e=>setIssue(e.target.value)}>{Object.entries(algae).map(([k,v])=><option key={k} value={k}>{String(v)}</option>)}</select></label><label>Intenzita<select value={severity} onChange={e=>setSeverity(e.target.value as any)}><option value="mild">Slabá</option><option value="moderate">Stredná</option><option value="strong">Silná</option></select></label><label>Výskyt</label><div>{Object.entries(locs).map(([k,v])=><label key={k} style={{marginRight:12}}><input type="checkbox" checked={locations.includes(k)} onChange={e=>setLocations(x=>e.target.checked?[...x,k]:x.filter(y=>y!==k))}/> {String(v)}</label>)}</div><label>Poznámka<textarea value={obsNotes} onChange={e=>setObsNotes(e.target.value)}/></label><div className="form-actions"><button className="primary" disabled={busy}>Uložiť pozorovanie</button><button type="button" onClick={()=>setShowObs(false)}>Zrušiť</button></div></form></section>}
 {show&&<section className="card"><h3>Nový záznam údržby</h3><form className="form" onSubmit={save}><label>Typ<select value={type} onChange={e=>setType(e.target.value as any)}>{types.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>{type==='other'&&<label>Názov<input required value={customType} onChange={e=>setCustomType(e.target.value)}/></label>}<label>Dátum a čas<input type="datetime-local" required value={date} onChange={e=>setDate(e.target.value)}/></label>{type==='water_change'&&<><label>Vymenená voda (l)<input type="number" min="0.1" step="0.1" required value={liters} onChange={e=>setLiters(e.target.value)}/></label>{aq&&+liters>0&&<div className="notice">Približne <b>{percent.toFixed(1)} %</b> z čistého objemu.</div>}</>}<label>Poznámka<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="form-actions"><button className="primary" disabled={busy}>Uložiť</button><button type="button" onClick={()=>setShow(false)}>Zrušiť</button></div></form></section>}
 <section className="card"><h3>Aktívne pozorovania</h3>{obs.filter(x=>x.status!=='resolved').length===0?<p>Žiadny evidovaný problém.</p>:obs.filter(x=>x.status!=='resolved').map(x=><div className="card" key={x.id}><b>{algae[x.issue_code]||x.issue_code}</b> · {x.severity==='strong'?'silná':x.severity==='moderate'?'stredná':'slabá'}<p className="muted">{fmt(x.observed_at)}{x.locations?.length?` · ${x.locations.map(y=>locs[y]||y).join(', ')}`:''}</p>{x.notes&&<p>{x.notes}</p>}<div className="form-actions"><button onClick={()=>resolveObs(x.id,'improving')}>Zlepšuje sa</button><button onClick={()=>resolveObs(x.id,'worsening')}>Zhoršuje sa</button><button onClick={()=>resolveObs(x.id,'resolved')}>Vyriešené</button></div></div>)}</section>
 <section className="card"><h3>História údržby</h3>{rows.length===0?<p>Zatiaľ bez záznamov.</p>:rows.map(r=>{const I=types.find(x=>x.value===r.maintenance_type)?.icon||NotebookPen;return <article className="card" key={r.id} style={{display:'flex',justifyContent:'space-between'}}><div><b><I size={16}/> {labelOf(r.maintenance_type,r.custom_type)}</b><p className="muted">{fmt(r.performed_at)}</p>{r.water_change_l!=null&&<p>{r.water_change_l} l · {Number(r.water_change_percent||0).toFixed(1)} %</p>}{r.notes&&<p>{r.notes}</p>}</div><button className="danger" onClick={()=>remove(r.id)}><Trash2 size={15}/></button></article>})}</section></>;
}