"use client";
import {useEffect,useMemo,useState} from "react";
import {PencilLine,X,Save} from "lucide-react";
import {createPortal} from "react-dom";
import {createClient} from "@/lib/supabase/client";
import type {Aquarium} from "@/components/AquariumsModule";

type Kind="plant"|"livestock";
type Row={id:string;catalogId?:string|null;name:string;data:Record<string,any>};
type Props={entityType:Kind;aquariums:Aquarium[]};
const num=(v:any)=>v==null?"":String(v);
const plantLabels:Record<string,string>={common_name:"Bežný názov",difficulty:"Náročnosť",light_requirement:"Nároky na svetlo",co2_requirement:"Nároky na CO₂",growth_rate:"Rýchlosť rastu",placement:"Umiestnenie",ph_min:"pH od",ph_max:"pH do",gh_min:"GH od",gh_max:"GH do",kh_min:"KH od",kh_max:"KH do",temperature_min:"Teplota od (°C)",temperature_max:"Teplota do (°C)",notes:"Poznámka"};
const livestockLabels:Record<string,string>={common_name:"Bežný názov",adult_size_cm:"Dospelá veľkosť (cm)",min_tank_l:"Minimálny objem nádrže (l)",min_group_size:"Minimálna skupina (ks)",recommended_group_size:"Odporúčaná skupina (ks)",temperature_min:"Teplota od (°C)",temperature_max:"Teplota do (°C)",ph_min:"pH od",ph_max:"pH do",gh_min:"GH od",gh_max:"GH do",kh_min:"KH od",kh_max:"KH do",temperament:"Správanie / temperament",swimming_zone:"Zóna plávania",diet:"Potrava",difficulty:"Náročnosť",shrimp_safe:"Bezpečný ku krevetám",snail_safe:"Bezpečný ku slimákom",plant_safe:"Bezpečný k rastlinám",notes:"Poznámka"};
const numeric=new Set(["adult_size_cm","min_tank_l","min_group_size","recommended_group_size","temperature_min","temperature_max","ph_min","ph_max","gh_min","gh_max","kh_min","kh_max"]);
const bools=new Set(["shrimp_safe","snail_safe","plant_safe"]);
function merged(base:any,local:any){return{...(base||{}),...(local||{})}}

export default function ManualCatalogDetailsPanel({entityType,aquariums}:Props){const[aquariumId,setAquariumId]=useState(aquariums[0]?.id||"");const[items,setItems]=useState<Row[]>([]);const[open,setOpen]=useState(false);const[selectedId,setSelectedId]=useState("");const[form,setForm]=useState<Record<string,string>>({});const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);const[mounted,setMounted]=useState(false);const[toolbar,setToolbar]=useState<HTMLElement|null>(null);
 useEffect(()=>{setMounted(true);return()=>setMounted(false)},[]);
 useEffect(()=>{const root=document.querySelector(`.v1-${entityType==="plant"?"plants":"livestock"}`) as HTMLElement|null;if(!root)return;const sync=()=>{const select=root.querySelector(".toolbar select") as HTMLSelectElement|null;if(select?.value&&select.value!==aquariumId)setAquariumId(select.value);const bar=root.querySelector(".toolbar") as HTMLElement|null;if(bar)setToolbar(bar);for(const b of Array.from(root.querySelectorAll("button")) as HTMLButtonElement[]){const t=(b.textContent||"").trim();if(entityType==="plant"&&/Dohľadať/i.test(t)){const card=b.closest(".plant-v1-card");if(card){b.dataset.manualDetails="1";b.innerHTML="Doplniť údaje"}else{b.style.display="none"}}if(entityType==="livestock"&&/online/i.test(t)){b.style.display="none"}}};sync();const mo=new MutationObserver(sync);mo.observe(root,{childList:true,subtree:true});const onChange=(e:Event)=>{const s=e.target as HTMLSelectElement;if(s.matches(".toolbar select"))setAquariumId(s.value)};root.addEventListener("change",onChange);const onClick=(e:Event)=>{const b=(e.target as HTMLElement).closest("button") as HTMLButtonElement|null;if(!b)return;const text=(b.textContent||"").trim();const intercept=entityType==="livestock"&&text==="Doplniť údaje"||entityType==="plant"&&b.dataset.manualDetails==="1";if(!intercept)return;e.preventDefault();e.stopPropagation();(e as any).stopImmediatePropagation?.();const card=b.closest(".plant-v1-card");const name=(card?.querySelector("h3")?.textContent||"").replace(/\s+/g," ").trim();const hit=items.find(x=>x.name===name)||items.find(x=>name&&x.name.includes(name));openEditor(hit?.id)};root.addEventListener("click",onClick,true);return()=>{mo.disconnect();root.removeEventListener("change",onChange);root.removeEventListener("click",onClick,true)}},[entityType,aquariumId,items]);
 useEffect(()=>{if(aquariumId)load()},[aquariumId,entityType]);
 async function load(){const s=createClient();if(entityType==="plant"){const{data}=await s.from("aquarium_plants").select("id,plant_id,custom_name,user_details,plant_catalog(*)").eq("aquarium_id",aquariumId).order("created_at");setItems((data||[]).map((x:any)=>({id:x.id,catalogId:x.plant_id,name:x.plant_catalog?.scientific_name||x.custom_name||"Rastlina",data:merged(x.plant_catalog,x.user_details)})))}else{const{data}=await s.from("aquarium_livestock").select("id,livestock_id,custom_name,discovery_data,livestock_catalog(*)").eq("aquarium_id",aquariumId).eq("active",true).order("created_at");setItems((data||[]).map((x:any)=>({id:x.id,catalogId:x.livestock_id,name:x.livestock_catalog?.scientific_name||x.discovery_data?.scientific_name||x.custom_name||"Živočích",data:merged(x.livestock_catalog,x.discovery_data)})))}}
 function openEditor(id?:string){const row=items.find(x=>x.id===id)||items[0];setSelectedId(row?.id||"");setMsg("");fill(row);setOpen(true)}
 function fill(row?:Row){const labels=entityType==="plant"?plantLabels:livestockLabels;const next:Record<string,string>={};for(const k of Object.keys(labels)){const v=row?.data?.[k];next[k]=typeof v==="boolean"?(v?"true":"false"):num(v)}setForm(next)}
 const selected=useMemo(()=>items.find(x=>x.id===selectedId),[items,selectedId]);
 async function save(e:React.FormEvent){e.preventDefault();if(!selected)return;const data:Record<string,any>={};for(const[k,v]of Object.entries(form)){if(v==="")continue;if(numeric.has(k))data[k]=Number(v);else if(bools.has(k))data[k]=v==="true";else data[k]=v}setBusy(true);setMsg("");try{const r=await fetch("/api/catalog-detail-proposals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({entityType,aquariumEntityId:selected.id,entityName:selected.name,proposedData:data})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"save_failed");setMsg("Údaje boli uložené pre tvoje akvárium a odoslané administrátorovi na overenie.");await load()}catch{setMsg("Údaje sa nepodarilo uložiť.")}finally{setBusy(false)}}
 const labels=entityType==="plant"?plantLabels:livestockLabels;
 const trigger=<button type="button" className="catalog-correction-trigger" onClick={()=>openEditor()}><PencilLine size={16}/>Doplniť údaje</button>;
 const modal=open&&mounted?createPortal(<div role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}} style={{position:"fixed",inset:0,zIndex:10000,background:"rgba(9,30,36,.42)",display:"grid",placeItems:"center",padding:16}}><section className="card" role="dialog" aria-modal="true" style={{width:"min(820px,100%)",maxHeight:"calc(100vh - 32px)",overflowY:"auto",margin:0}}><div className="section-head"><div><small>POUŽÍVATEĽSKÉ ÚDAJE</small><h3><PencilLine size={18}/> Doplniť údaje – {entityType==="plant"?"rastlina":"živočích"}</h3></div><button type="button" onClick={()=>setOpen(false)}><X size={18}/></button></div>{items.length===0?<div className="notice">Najprv pridaj {entityType==="plant"?"rastlinu":"živočícha"} do akvária.</div>:<form className="form" onSubmit={save}><label>Položka<select value={selectedId} onChange={e=>{setSelectedId(e.target.value);fill(items.find(x=>x.id===e.target.value))}}>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div/><div className="notice" style={{gridColumn:"1/-1"}}>Vyplň iba údaje, ktoré poznáš. Uložia sa pre tvoje akvárium. Do centrálneho katalógu sa dostanú až po kontrole administrátorom.</div>{Object.entries(labels).map(([k,label])=>bools.has(k)?<label key={k}>{label}<select value={form[k]||""} onChange={e=>setForm(v=>({...v,[k]:e.target.value}))}><option value="">Neuvedené</option><option value="true">Áno</option><option value="false">Nie</option></select></label>:k==="notes"?<label key={k} style={{gridColumn:"1/-1"}}>{label}<textarea rows={3} value={form[k]||""} onChange={e=>setForm(v=>({...v,[k]:e.target.value}))}/></label>:<label key={k}>{label}<input type={numeric.has(k)?"number":"text"} step={numeric.has(k)?"0.1":undefined} min={numeric.has(k)?"0":undefined} value={form[k]||""} onChange={e=>setForm(v=>({...v,[k]:e.target.value}))}/></label>)}<div className="form-actions" style={{gridColumn:"1/-1"}}><button className="primary" disabled={busy}><Save size={15}/>{busy?"Ukladám…":"Uložiť a odoslať na overenie"}</button><button type="button" onClick={()=>setOpen(false)}>Zrušiť</button></div>{msg&&<div className="notice" style={{gridColumn:"1/-1"}}>{msg}</div>}</form>}</section></div>,document.body):null;
 return <>{mounted&&toolbar?createPortal(trigger,toolbar):null}{modal}</>}
