"use client";
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {measurementStatus,measurementStatusLabel,type TargetRange} from "@/lib/measurementStatus";
import type {Aquarium} from "@/components/AquariumsModule";

const measurementFields=[['ph','pH',''],['gh','GH','°dGH'],['kh','KH','°dKH'],['no2','NO₂','mg/l'],['no3','NO₃','mg/l'],['nh3','NH₃','mg/l'],['nh4','NH₄','mg/l'],['po4','PO₄','mg/l'],['fe','Fe','mg/l'],['k','K','mg/l'],['mg','Mg','mg/l'],['ca','Ca','mg/l'],['tds','TDS','ppm'],['ec','Vodivosť','µS/cm'],['temperature','Teplota','°C'],['o2','O₂','mg/l']] as const;
type Measurement={id:string;measured_at:string;note?:string;values:Record<string,number>};
type SpeciesData={temperature_min?:number;temperature_max?:number;ph_min?:number;ph_max?:number;gh_min?:number;gh_max?:number;kh_min?:number;kh_max?:number};

function mergedSpecies(row:any):SpeciesData{const c=row?.livestock_catalog||{},d=row?.discovery_data||{};return{temperature_min:c.temperature_min??d.temperature_min,temperature_max:c.temperature_max??d.temperature_max,ph_min:c.ph_min??d.ph_min,ph_max:c.ph_max??d.ph_max,gh_min:c.gh_min??d.gh_min,gh_max:c.gh_max??d.gh_max,kh_min:c.kh_min??d.kh_min,kh_max:c.kh_max??d.kh_max}}
function sharedTargets(rows:any[]){const out:Record<string,TargetRange>={};for(const code of ['temperature','ph','gh','kh']){const mins:number[]=[],maxs:number[]=[];for(const r of rows){const s=mergedSpecies(r) as any;if(typeof s[`${code}_min`]==='number')mins.push(s[`${code}_min`]);if(typeof s[`${code}_max`]==='number')maxs.push(s[`${code}_max`])}if(mins.length&&maxs.length){const min=Math.max(...mins),max=Math.min(...maxs);if(min<=max)out[code]={min,max}}}return out}

export default function MeasurementsModule({aquariums}:{aquariums:Aquarium[]}){
 const[aquariumId,setAquariumId]=useState(aquariums[0]?.id||"");const[items,setItems]=useState<Measurement[]>([]);const[busy,setBusy]=useState(false);const[note,setNote]=useState("");const[form,setForm]=useState<Record<string,string>>({});const[msg,setMsg]=useState('');const[targets,setTargets]=useState<Record<string,TargetRange>>({});
 useEffect(()=>{if(!aquariumId&&aquariums[0])setAquariumId(aquariums[0].id)},[aquariums,aquariumId]);useEffect(()=>{if(aquariumId)load()},[aquariumId]);
 async function load(){const s=createClient();const[m,l]=await Promise.all([s.from("measurement_sessions").select("id,measured_at,note,measurement_values(parameter_code,value)").eq("aquarium_id",aquariumId).order("measured_at",{ascending:false}).limit(30),s.from('aquarium_livestock').select('discovery_data,livestock_catalog(temperature_min,temperature_max,ph_min,ph_max,gh_min,gh_max,kh_min,kh_max)').eq('aquarium_id',aquariumId).eq('active',true)]);if(m.error){setMsg('Merania sa nepodarilo načítať. Skús to prosím znova.');return}setMsg('');setItems((m.data||[]).map((x:any)=>({id:x.id,measured_at:x.measured_at,note:x.note,values:Object.fromEntries((x.measurement_values||[]).map((v:any)=>[v.parameter_code,Number(v.value)]))})));if(!l.error)setTargets(sharedTargets(l.data||[]))}
 async function save(e:React.FormEvent){e.preventDefault();const values=Object.entries(form).filter(([,v])=>v!=="");if(!values.length){setMsg('Zadaj aspoň jeden parameter.');return}setBusy(true);setMsg('');const s=createClient();const{data:session,error}=await s.from("measurement_sessions").insert({aquarium_id:aquariumId,note:note||null}).select("id").single();if(error){setBusy(false);setMsg('Meranie sa nepodarilo uložiť. Skús to prosím znova.');return}const{error:e2}=await s.from("measurement_values").insert(values.map(([parameter_code,value])=>({session_id:session.id,parameter_code,value:Number(value),source_type:"manual"})));setBusy(false);if(e2){setMsg('Hodnoty merania sa nepodarilo uložiť. Skús to prosím znova.');return}setForm({});setNote("");load()}
 if(!aquariums.length)return <section className="card"><h3>Merania</h3><p>Najprv vytvor akvárium.</p></section>;
 return <><section className="card"><h3>Nové meranie</h3>{msg&&<div className="notice">{msg}</div>}<form onSubmit={save}><div className="form"><label>Akvárium<select value={aquariumId} onChange={e=>setAquariumId(e.target.value)}>{aquariums.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>Poznámka<input value={note} onChange={e=>setNote(e.target.value)}/></label>{measurementFields.map(([code,label,unit])=><label key={code}>{label}{unit?` (${unit})`:''}<input type="number" step="any" value={form[code]||""} onChange={e=>setForm({...form,[code]:e.target.value})}/></label>)}</div><button className="primary" disabled={busy}>{busy?'Ukladám…':'Uložiť meranie'}</button></form></section><section className="card"><h3>História meraní</h3>{Object.keys(targets).length>0&&<p className="muted">Farby pH, GH, KH a teploty sa hodnotia podľa spoločného vhodného rozsahu tvojej osádky.</p>}{items.length===0?<div className="notice">Zatiaľ nemáš uložené žiadne meranie.</div>:items.map(m=><div className="measurement-row" key={m.id}><div><b>{new Date(m.measured_at).toLocaleString('sk-SK')}</b>{m.note&&<small>{m.note}</small>}</div><div className="measurement-values">{measurementFields.filter(([c])=>m.values[c]!==undefined).map(([c,l,u])=>{const target=targets[c];const status=measurementStatus(c,m.values[c],target);return <span className={`measurement-value status-${status}`} title={measurementStatusLabel(status,target)} key={c}><b>{l}</b> {m.values[c]} {u}</span>})}</div></div>)}</section></>
}
