"use client";
import {useEffect,useState} from "react";
import {Camera,Images,Trash2,ArrowLeftRight,Sparkles,Clock3,X,Maximize2,TrendingUp,Crown} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import type {Aquarium} from "@/components/AquariumsModule";

type Analysis={summary?:string;condition?:"good"|"watch"|"attention";plant_cover_percent?:number|null;algae_detected?:boolean;algae_types?:string[];algae_severity?:string;water_clarity?:string;glass_cleanliness?:string;plant_condition?:string;observations?:string[];suggested_actions?:string[];confidence?:string;trend?:"improved"|"stable"|"worse"|"unknown";change_summary?:string|null;internal_trend_score?:number|null};
type Photo={id:string;aquarium_id:string;image_path:string;taken_at:string;note?:string|null;analysis_status?:string;analysis_data?:Analysis|null};
const conditionLabel:Record<string,string>={good:"Bez viditeľného problému",watch:"Sledovať vývoj",attention:"Vyžaduje pozornosť"};
const algaeLabel:Record<string,string>={none:"bez viditeľnej riasy",mild:"mierny výskyt",moderate:"stredný výskyt",strong:"silný výskyt",unknown:"neurčené"};
const clarityLabel:Record<string,string>={clear:"číra",slightly_hazy:"mierne zakalená",hazy:"zakalená",unknown:"neurčené"};
const plantLabel:Record<string,string>={good:"dobrá",mixed:"zmiešaná",poor:"slabá",unknown:"neurčené"};
const trendLabel:Record<string,string>={improved:"Vývoj sa zlepšil",stable:"Stav je približne stabilný",worse:"Vývoj sa zhoršil",unknown:"Trend sa nedá spoľahlivo určiť"};
const algaeScore:Record<string,number>={none:0,mild:1,moderate:2,strong:3};
const clarityScore:Record<string,number>={hazy:0,slightly_hazy:1,clear:2};
function fmtNext(s:string|null){if(!s)return'';const d=new Date(s),ms=d.getTime()-Date.now();if(ms<=0)return'Dostupná teraz';const days=Math.floor(ms/86400000),hours=Math.ceil((ms-days*86400000)/3600000);return days>0?`o ${days} d ${hours} h`:`o ${hours} h`}
function dbError(prefix:string,e:any){const parts=[e?.code,e?.message,e?.details,e?.hint].filter(Boolean);return `${prefix}${parts.length?` (${parts.join(' · ')})`:''}`}
function direction(delta:number,threshold=0){return delta>threshold?'↑':delta<-threshold?'↓':'→'}
function dayFromSetup(photo:Photo,aquarium?:Aquarium){if(!aquarium?.setup_date)return new Date(photo.taken_at).toLocaleDateString('sk-SK',{day:'numeric',month:'numeric'});const start=new Date(`${aquarium.setup_date}T00:00:00`).getTime();const current=new Date(photo.taken_at).getTime();return `${Math.max(1,Math.floor((current-start)/86400000)+1)} dní`}

export default function PhotoDiaryModule({aquariums}:{aquariums:Aquarium[]}){
 const[aquariumId,setAquariumId]=useState(aquariums[0]?.id||"");const[items,setItems]=useState<Photo[]>([]);const[file,setFile]=useState<File|null>(null);const[note,setNote]=useState("");const[takenAt,setTakenAt]=useState(new Date().toISOString().slice(0,16));const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);const[urls,setUrls]=useState<Record<string,string>>({});const[left,setLeft]=useState("");const[right,setRight]=useState("");const[analyzing,setAnalyzing]=useState<string|null>(null);const[aiAvailable,setAiAvailable]=useState(false);const[nextAi,setNextAi]=useState<string|null>(null);const[quotaLoaded,setQuotaLoaded]=useState(false);const[premiumActive,setPremiumActive]=useState(false);const[preview,setPreview]=useState<{url:string;title:string}|null>(null);
 useEffect(()=>{if(!aquariumId&&aquariums[0])setAquariumId(aquariums[0].id)},[aquariums,aquariumId]);useEffect(()=>{if(aquariumId)load()},[aquariumId]);useEffect(()=>{loadQuota()},[]);useEffect(()=>{if(!preview)return;const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')setPreview(null)};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[preview]);
 async function loadQuota(){try{const s=createClient();const{data:u}=await s.auth.getUser();if(!u.user)return;const q=await s.from('user_subscriptions').select('premium_until').eq('user_id',u.user.id).maybeSingle();setPremiumActive(!!q.data?.premium_until&&new Date(q.data.premium_until).getTime()>Date.now());const r=await fetch('/api/photo-analysis',{cache:'no-store'});const j=await r.json();if(r.ok){setAiAvailable(!!j.available);setNextAi(j.nextAvailableAt||null)}}finally{setQuotaLoaded(true)}}
 async function load(){const s=createClient();const{data,error}=await s.from('aquarium_photos').select('id,aquarium_id,image_path,taken_at,note,analysis_status,analysis_data').eq('aquarium_id',aquariumId).order('taken_at',{ascending:false});if(error){setMsg(dbError('Fotodenník sa nepodarilo načítať.',error));return}const rows=(data||[]) as Photo[];setItems(rows);setMsg('');const map:Record<string,string>={};await Promise.all(rows.map(async p=>{const r=await s.storage.from('aquarium-diary').createSignedUrl(p.image_path,3600);if(r.data?.signedUrl)map[p.id]=r.data.signedUrl}));setUrls(map);if(rows[0])setRight(v=>v||rows[0].id);if(rows[1])setLeft(v=>v||rows[1].id)}
 async function analyze(photoId:string){setAnalyzing(photoId);setMsg('');try{const r=await fetch('/api/photo-analysis',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({photoId})});const j=await r.json();if(r.status===429){setAiAvailable(false);setNextAi(j.nextAvailableAt||null);setMsg(`AI analýza momentálne nie je dostupná. Ďalšia bude dostupná ${fmtNext(j.nextAvailableAt||null)}.`);return}if(!r.ok)throw new Error(j?.error||'analysis_failed');setAiAvailable(false);setNextAi(j.nextAvailableAt||null);await load()}catch(e:any){setMsg(`Analýza sa nepodarila. Kredit sa nespotreboval. ${e?.message||''}`.trim())}finally{setAnalyzing(null)}}
 async function upload(e:React.FormEvent){e.preventDefault();if(!file)return setMsg('Vyber fotografiu akvária.');if(file.size>10*1024*1024)return setMsg('Fotografia môže mať maximálne 10 MB.');setBusy(true);setMsg('');const s=createClient();const{data:u}=await s.auth.getUser();if(!u.user){setBusy(false);return setMsg('Pre uloženie fotografie sa musíš prihlásiť.')}const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${u.user.id}/${aquariumId}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const up=await s.storage.from('aquarium-diary').upload(path,file,{contentType:file.type||'image/jpeg',upsert:false});if(up.error){setBusy(false);return setMsg(dbError('Fotografiu sa nepodarilo nahrať.',up.error))}const db=await s.from('aquarium_photos').insert({aquarium_id:aquariumId,image_path:path,taken_at:new Date(takenAt).toISOString(),note:note.trim()||null,analysis_status:'not_analyzed'}).select('id').single();if(db.error){await s.storage.from('aquarium-diary').remove([path]);setBusy(false);return setMsg(dbError('Fotografiu sa nepodarilo zapísať do denníka.',db.error))}setFile(null);setNote('');setTakenAt(new Date().toISOString().slice(0,16));setBusy(false);await load();setMsg(aiAvailable?'Fotografia bola uložená. Ak chceš, môžeš na ňu použiť svoju aktuálne dostupnú AI analýzu.':'Fotografia bola uložená do fotodenníka.')}
 async function remove(p:Photo){if(!confirm('Odstrániť túto fotografiu z fotodenníka?'))return;const s=createClient();await s.storage.from('aquarium-diary').remove([p.image_path]);const{error}=await s.from('aquarium_photos').delete().eq('id',p.id);if(error)return setMsg(dbError('Fotografiu sa nepodarilo odstrániť.',error));setItems(v=>v.filter(x=>x.id!==p.id));setUrls(v=>{const n={...v};delete n[p.id];return n})}
 function photoButton(p:Photo,label:string){const url=urls[p.id];return url?<button type="button" className="photo-thumb-button" onClick={()=>setPreview({url,title:`${label} · ${new Date(p.taken_at).toLocaleString('sk-SK')}`})} title="Otvoriť fotografiu v plnej veľkosti"><img src={url} alt={label}/><span className="photo-open"><Maximize2 size={15}/> Zväčšiť</span></button>:<div className="entity-image-placeholder"><Camera size={28}/></div>}
 const leftPhoto=items.find(x=>x.id===left),rightPhoto=items.find(x=>x.id===right),selectedAquarium=aquariums.find(a=>a.id===aquariumId);
 const analyzed=items.filter(p=>p.analysis_status==='completed'&&p.analysis_data).slice().sort((a,b)=>new Date(a.taken_at).getTime()-new Date(b.taken_at).getTime());
 const coverage=analyzed.filter(p=>p.analysis_data?.plant_cover_percent!=null);const firstCoverage=coverage[0]?.analysis_data?.plant_cover_percent??null;const lastCoverage=coverage[coverage.length-1]?.analysis_data?.plant_cover_percent??null;const coverageDelta=firstCoverage!=null&&lastCoverage!=null?lastCoverage-firstCoverage:0;
 const algaePoints=analyzed.map(p=>algaeScore[p.analysis_data?.algae_severity||'']).filter((x):x is number=>x!=null);const algaeDelta=algaePoints.length>=2?algaePoints[algaePoints.length-1]-algaePoints[0]:0;
 const clarityPoints=analyzed.map(p=>clarityScore[p.analysis_data?.water_clarity||'']).filter((x):x is number=>x!=null);const clarityDelta=clarityPoints.length>=2?clarityPoints[clarityPoints.length-1]-clarityPoints[0]:0;
 const latestTrend=analyzed[analyzed.length-1]?.analysis_data?.trend;const plantDirection=coverage.length>=2?direction(coverageDelta,2):(latestTrend==='improved'?'↑':latestTrend==='worse'?'↓':'→');const algaeDirection=algaePoints.length>=2?direction(algaeDelta,0):'→';const clarityDirection=clarityPoints.length>=2?direction(clarityDelta,0):'→';
 if(!aquariums.length)return <section className="card"><h3>Fotodenník</h3><p>Najprv vytvor akvárium.</p></section>;
 return <>
  <div className="toolbar"><label>Akvárium <select value={aquariumId} onChange={e=>{setAquariumId(e.target.value);setLeft('');setRight('')}}>{aquariums.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div>
  <section className="card"><div className="section-head"><div><small>AI FOTODENNÍK</small><h3><Sparkles size={18}/> Analýza fotografie</h3></div>{quotaLoaded&&premiumActive&&<span className="status-pill status-neutral"><Crown size={12}/> PREMIUM</span>}</div>{!quotaLoaded?<p className="muted">Kontrolujem dostupnosť analýzy…</p>:aiAvailable?<div className="notice">🟢 <b>AI analýza je dostupná.</b> {premiumActive?'Premium účet: ďalšia analýza bude dostupná o 7 dní.':'Free účet: ďalšia analýza bude dostupná o 30 dní.'}</div>:<div className="notice"><Clock3 size={15}/> <b>Ďalšia AI analýza {fmtNext(nextAi)}.</b> {premiumActive?'Premium umožňuje AI analýzu raz za 7 dní.':'Free verzia umožňuje AI analýzu raz za 30 dní.'}</div>}<p className="muted">AI hodnotí iba to, čo je na fotografii vizuálne viditeľné. Chemické parametre vody sa vždy riadia skutočnými meraniami.</p></section>
  <section className="card"><div className="section-head"><div><small>VÝVOJ NÁDRŽE</small><h3><Camera size={18}/> Pridať fotografiu</h3></div></div><p className="muted">Pravidelné fotografie vytvoria časovú os vývoja. AI analýzu si vyberáš samostatne, aby sa kredit neminul na nevhodnej fotografii.</p>{msg&&<div className="notice">{msg}</div>}<form className="form" onSubmit={upload}><label>Fotografia<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label>Dátum a čas<input type="datetime-local" value={takenAt} onChange={e=>setTakenAt(e.target.value)}/></label><label>Poznámka<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Napr. po strihaní, pred výmenou vody, 3. týždeň od založenia…"/></label><div className="form-actions"><button className="primary" disabled={busy}>{busy?'Nahrávam…':'Pridať do fotodenníka'}</button></div></form></section>
  <section className="card"><div className="section-head"><div><small>VÝVOJ AKVÁRIA</small><h3><TrendingUp size={18}/> Vývoj nádrže</h3></div>{quotaLoaded&&!premiumActive&&<span className="status-pill status-neutral"><Crown size={12}/> PREMIUM</span>}</div>{!premiumActive?<div className="notice"><b>Pokročilé trendy sú súčasťou Premium.</b><p style={{marginBottom:0}}>Free verzia zachováva fotodenník, AI analýzu raz za 30 dní a porovnanie Pred / po. Premium pridáva pokročilé trendy vývoja a AI analýzu raz za 7 dní.</p></div>:analyzed.length<2?<div className="notice"><b>Zatiaľ zbierame podklady.</b><p style={{marginBottom:0}}>Na spoľahlivý trend potrebujeme aspoň 2 AI-analyzované fotografie tejto nádrže. Aktuálne: {analyzed.length}/2.</p></div>:<><div style={{display:'flex',alignItems:'center',gap:8,flexWrap:'wrap',margin:'4px 0 18px'}}>{analyzed.map((p,i)=><span key={p.id} style={{display:'inline-flex',alignItems:'center',gap:8,fontWeight:800}}><span className="status-pill status-neutral">{dayFromSetup(p,selectedAquarium)}</span>{i<analyzed.length-1&&<span className="muted">→</span>}</span>)}</div><div className="summary-grid"><div className="summary-tile"><span><small>🌿 RAST RASTLÍN</small><b>{plantDirection}</b><small>{plantDirection==='↑'?'rastú':plantDirection==='↓'?'ustupujú':'stabilné'}</small></span></div><div className="summary-tile"><span><small>🦠 RIASY</small><b>{algaeDirection}</b><small>{algaeDirection==='↓'?'ustupujú':algaeDirection==='↑'?'pribúdajú':'stabilné'}</small></span></div><div className="summary-tile"><span><small>💧 ČÍROSŤ</small><b>{clarityDirection}</b><small>{clarityDirection==='↑'?'zlepšuje sa':clarityDirection==='↓'?'zhoršuje sa':'stabilná'}</small></span></div><div className="summary-tile"><span><small>🌱 ZARASTENOSŤ</small><b>{lastCoverage!=null?`${Math.round(lastCoverage)} %`:'—'}</b><small>{firstCoverage!=null&&lastCoverage!=null?`${Math.round(firstCoverage)} % → ${Math.round(lastCoverage)} %`:'nedostatok dát'}</small></span></div></div>{coverage.length>=2&&<div className="notice"><b>Vývoj zarastenosti</b><p style={{marginBottom:0,marginTop:7,fontWeight:750}}>{coverage.map((p,i)=><span key={p.id}>{i>0?' → ':''}{Math.round(p.analysis_data!.plant_cover_percent!)} %</span>)}</p></div>}<small className="muted">Trend sa počíta iba z dokončených AI analýz. Pri ďalšej analyzovanej fotografii sa automaticky aktualizuje.</small></>}</section>
  {items.length>=2&&<section className="card"><div className="section-head"><div><small>POROVNANIE</small><h3><ArrowLeftRight size={18}/> Pred / po</h3></div></div><div className="form"><label>Staršia fotografia<select value={left} onChange={e=>setLeft(e.target.value)}>{items.map(p=><option value={p.id} key={p.id}>{new Date(p.taken_at).toLocaleString('sk-SK')}</option>)}</select></label><label>Novšia fotografia<select value={right} onChange={e=>setRight(e.target.value)}>{items.map(p=><option value={p.id} key={p.id}>{new Date(p.taken_at).toLocaleString('sk-SK')}</option>)}</select></label></div><div className="photo-compare">{leftPhoto&&<figure><div className="compare-label">PRED</div>{photoButton(leftPhoto,'Staršia fotografia akvária')}<figcaption>{new Date(leftPhoto.taken_at).toLocaleString('sk-SK')}</figcaption>{leftPhoto.note&&<small>{leftPhoto.note}</small>}</figure>}{rightPhoto&&<figure><div className="compare-label">PO</div>{photoButton(rightPhoto,'Novšia fotografia akvária')}<figcaption>{new Date(rightPhoto.taken_at).toLocaleString('sk-SK')}</figcaption>{rightPhoto.note&&<small>{rightPhoto.note}</small>}</figure>}</div></section>}
  <section className="card"><div className="section-head"><div><small>ČASOVÁ OS</small><h3><Images size={18}/> Fotografie</h3></div></div>{!items.length?<div className="notice">Zatiaľ tu nie je žiadna fotografia. Pridaj prvú a začne sa vytvárať história vývoja nádrže.</div>:<div className="photo-timeline">{items.map(p=>{const a=p.analysis_data;const state=a?.condition||'watch';return <article className="photo-entry" key={p.id}><div className="photo-entry-image">{photoButton(p,'Fotografia akvária')}</div><div className="photo-entry-body"><div className="photo-entry-head"><div><b>{new Date(p.taken_at).toLocaleString('sk-SK')}</b>{p.note&&<p>{p.note}</p>}</div><button className="danger" onClick={()=>remove(p)} title="Odstrániť"><Trash2 size={15}/></button></div>{(p.analysis_status==='analyzing'||analyzing===p.id)&&<div className="notice"><Sparkles size={15}/> Analyzujem fotografiu…</div>}{p.analysis_status==='completed'&&a?<div className={`photo-analysis analysis-${state}`}><div className="photo-analysis-title"><Sparkles size={16}/><b>{conditionLabel[state]||'Analýza fotografie'}</b><small>Istota: {a.confidence==='high'?'vysoká':a.confidence==='medium'?'stredná':'nižšia'}</small></div><p>{a.summary}</p>{a.change_summary&&<div className="notice"><b>{trendLabel[a.trend||'unknown']}</b><p>{a.change_summary}</p></div>}<div className="analysis-facts">{a.plant_cover_percent!=null&&<span>🌿 Zarastenosť ~{a.plant_cover_percent}%</span>}<span>💧 Voda: {clarityLabel[a.water_clarity||'unknown']}</span><span>🌱 Rastliny: {plantLabel[a.plant_condition||'unknown']}</span>{a.algae_detected&&<span>🦠 Riasy: {algaeLabel[a.algae_severity||'unknown']}{a.algae_types?.length?` · ${a.algae_types.join(', ')}`:''}</span>}</div>{a.observations?.length?<div><b>Viditeľné pozorovania</b><ul>{a.observations.map((x,i)=><li key={i}>{x}</li>)}</ul></div>:null}{a.suggested_actions?.length?<div><b>Odporúčané kroky</b><ul>{a.suggested_actions.map((x,i)=><li key={i}>{x}</li>)}</ul></div>:null}<small className="muted">AI vychádza iba z fotografie a nenahrádza meranie vody.</small></div>:<div className="photo-ai-action">{aiAvailable?<button className="primary" onClick={()=>analyze(p.id)} disabled={!!analyzing}><Sparkles size={15}/>{p.analysis_status==='failed'?' Skúsiť analýzu znova':' Analyzovať fotografiu'}</button>:<small className="muted">AI analýza momentálne nie je dostupná · {fmtNext(nextAi)}</small>}</div>}</div></article>})}</div>}</section>
  {preview&&<div className="photo-lightbox" role="dialog" aria-modal="true" onClick={()=>setPreview(null)}><button type="button" className="photo-lightbox-close" onClick={()=>setPreview(null)} aria-label="Zavrieť"><X size={22}/></button><div className="photo-lightbox-inner" onClick={e=>e.stopPropagation()}><img src={preview.url} alt={preview.title}/><div>{preview.title}</div></div></div>}
 </>;
}