"use client";
import {useEffect,useState} from "react";
import {Camera,Images,Trash2,ArrowLeftRight,Sparkles,RefreshCw} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import type {Aquarium} from "@/components/AquariumsModule";

type Analysis={summary?:string;condition?:"good"|"watch"|"attention";plant_cover_percent?:number|null;algae_detected?:boolean;algae_types?:string[];algae_severity?:string;water_clarity?:string;glass_cleanliness?:string;plant_condition?:string;observations?:string[];suggested_actions?:string[];confidence?:string;internal_trend_score?:number|null};
type Photo={id:string;aquarium_id:string;image_path:string;taken_at:string;note?:string|null;analysis_status:string;analysis_data?:Analysis|null};
const conditionLabel:Record<string,string>={good:"Bez viditeľného problému",watch:"Sledovať vývoj",attention:"Vyžaduje pozornosť"};
const algaeLabel:Record<string,string>={none:"bez viditeľnej riasy",mild:"mierny výskyt",moderate:"stredný výskyt",strong:"silný výskyt",unknown:"neurčené"};
const clarityLabel:Record<string,string>={clear:"číra",slightly_hazy:"mierne zakalená",hazy:"zakalená",unknown:"neurčené"};
const plantLabel:Record<string,string>={good:"dobrá",mixed:"zmiešaná",poor:"slabá",unknown:"neurčené"};

export default function PhotoDiaryModule({aquariums}:{aquariums:Aquarium[]}){
 const[aquariumId,setAquariumId]=useState(aquariums[0]?.id||"");const[items,setItems]=useState<Photo[]>([]);const[file,setFile]=useState<File|null>(null);const[note,setNote]=useState("");const[takenAt,setTakenAt]=useState(new Date().toISOString().slice(0,16));const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);const[urls,setUrls]=useState<Record<string,string>>({});const[left,setLeft]=useState("");const[right,setRight]=useState("");const[analyzing,setAnalyzing]=useState<string|null>(null);
 useEffect(()=>{if(!aquariumId&&aquariums[0])setAquariumId(aquariums[0].id)},[aquariums,aquariumId]);
 useEffect(()=>{if(aquariumId)load()},[aquariumId]);
 async function load(){const s=createClient();const{data,error}=await s.from('aquarium_photos').select('*').eq('aquarium_id',aquariumId).order('taken_at',{ascending:false});if(error){setMsg('Fotodenník ešte potrebuje databázovú migráciu.');return}const rows=(data||[]) as Photo[];setItems(rows);setMsg('');const map:Record<string,string>={};await Promise.all(rows.map(async p=>{const r=await s.storage.from('aquarium-diary').createSignedUrl(p.image_path,3600);if(r.data?.signedUrl)map[p.id]=r.data.signedUrl}));setUrls(map);if(rows[0])setRight(v=>v||rows[0].id);if(rows[1])setLeft(v=>v||rows[1].id)}
 async function analyze(photoId:string){setAnalyzing(photoId);try{const r=await fetch('/api/photo-analysis',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({photoId})});if(!r.ok)throw new Error();await load()}catch{setMsg('Fotka sa uložila, ale automatická analýza sa nepodarila. Môžeš ju spustiť znova.')}finally{setAnalyzing(null)}}
 async function upload(e:React.FormEvent){e.preventDefault();if(!file)return setMsg('Vyber fotografiu akvária.');if(file.size>10*1024*1024)return setMsg('Fotografia môže mať maximálne 10 MB.');setBusy(true);setMsg('');const s=createClient();const{data:u}=await s.auth.getUser();if(!u.user){setBusy(false);return setMsg('Pre uloženie fotografie sa musíš prihlásiť.')}const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${u.user.id}/${aquariumId}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const up=await s.storage.from('aquarium-diary').upload(path,file,{contentType:file.type||'image/jpeg',upsert:false});if(up.error){setBusy(false);return setMsg('Fotografiu sa nepodarilo nahrať. Skús to znova.')}const db=await s.from('aquarium_photos').insert({aquarium_id:aquariumId,image_path:path,taken_at:new Date(takenAt).toISOString(),note:note.trim()||null}).select('id').single();if(db.error){await s.storage.from('aquarium-diary').remove([path]);setBusy(false);return setMsg('Fotografiu sa nepodarilo zapísať do denníka.')}setFile(null);setNote('');setTakenAt(new Date().toISOString().slice(0,16));setBusy(false);await load();await analyze(db.data.id)}
 async function remove(p:Photo){if(!confirm('Odstrániť túto fotografiu z fotodenníka?'))return;const s=createClient();await s.storage.from('aquarium-diary').remove([p.image_path]);const{error}=await s.from('aquarium_photos').delete().eq('id',p.id);if(error)return setMsg('Fotografiu sa nepodarilo odstrániť.');setItems(v=>v.filter(x=>x.id!==p.id));setUrls(v=>{const n={...v};delete n[p.id];return n})}
 const leftPhoto=items.find(x=>x.id===left),rightPhoto=items.find(x=>x.id===right);
 if(!aquariums.length)return <section className="card"><h3>Fotodenník</h3><p>Najprv vytvor akvárium.</p></section>;
 return <>
  <div className="toolbar"><label>Akvárium <select value={aquariumId} onChange={e=>{setAquariumId(e.target.value);setLeft('');setRight('')}}>{aquariums.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div>
  <section className="card"><div className="section-head"><div><small>VÝVOJ NÁDRŽE</small><h3><Camera size={18}/> Pridať fotografiu</h3></div></div><p className="muted">Fotka sa po nahratí automaticky analyzuje a zostane uložená v časovej osi akvária.</p>{msg&&<div className="notice">{msg}</div>}<form className="form" onSubmit={upload}><label>Fotografia<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label>Dátum a čas<input type="datetime-local" value={takenAt} onChange={e=>setTakenAt(e.target.value)}/></label><label>Poznámka<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Napr. po strihaní, pred výmenou vody, 3. týždeň od založenia…"/></label><div className="form-actions"><button className="primary" disabled={busy}>{busy?'Nahrávam…':'Pridať do fotodenníka'}</button></div></form></section>
  {items.length>=2&&<section className="card"><div className="section-head"><div><small>POROVNANIE</small><h3><ArrowLeftRight size={18}/> Pred / po</h3></div></div><div className="form"><label>Staršia fotografia<select value={left} onChange={e=>setLeft(e.target.value)}>{items.map(p=><option value={p.id} key={p.id}>{new Date(p.taken_at).toLocaleString('sk-SK')}</option>)}</select></label><label>Novšia fotografia<select value={right} onChange={e=>setRight(e.target.value)}>{items.map(p=><option value={p.id} key={p.id}>{new Date(p.taken_at).toLocaleString('sk-SK')}</option>)}</select></label></div><div className="photo-compare">{leftPhoto&&<figure><img src={urls[leftPhoto.id]} alt="Staršia fotografia akvária"/><figcaption>{new Date(leftPhoto.taken_at).toLocaleString('sk-SK')}</figcaption></figure>}{rightPhoto&&<figure><img src={urls[rightPhoto.id]} alt="Novšia fotografia akvária"/><figcaption>{new Date(rightPhoto.taken_at).toLocaleString('sk-SK')}</figcaption></figure>}</div></section>}
  <section className="card"><div className="section-head"><div><small>ČASOVÁ OS</small><h3><Images size={18}/> Fotografie</h3></div></div>{!items.length?<div className="notice">Zatiaľ tu nie je žiadna fotografia. Pridaj prvú a začne sa vytvárať história vývoja nádrže.</div>:<div className="photo-timeline">{items.map(p=>{const a=p.analysis_data;const state=a?.condition||'watch';return <article className="photo-entry" key={p.id}><div className="photo-entry-image">{urls[p.id]?<img src={urls[p.id]} alt="Fotografia akvária"/>:<div className="entity-image-placeholder"><Camera size={28}/></div>}</div><div className="photo-entry-body"><div className="photo-entry-head"><div><b>{new Date(p.taken_at).toLocaleString('sk-SK')}</b>{p.note&&<p>{p.note}</p>}</div><button className="danger" onClick={()=>remove(p)} title="Odstrániť"><Trash2 size={15}/></button></div>{(p.analysis_status==='analyzing'||analyzing===p.id)&&<div className="notice"><Sparkles size={15}/> Analyzujem fotografiu…</div>}{p.analysis_status==='failed'&&<div className="notice">Analýza sa nepodarila. <button onClick={()=>analyze(p.id)} disabled={analyzing===p.id}><RefreshCw size={14}/> Skúsiť znova</button></div>}{p.analysis_status==='completed'&&a&&<div className={`photo-analysis analysis-${state}`}><div className="photo-analysis-title"><Sparkles size={16}/><b>{conditionLabel[state]||'Analýza fotografie'}</b><small>Istota: {a.confidence==='high'?'vysoká':a.confidence==='medium'?'stredná':'nižšia'}</small></div><p>{a.summary}</p><div className="analysis-facts">{a.plant_cover_percent!=null&&<span>🌿 Zarastenosť ~{a.plant_cover_percent}%</span>}<span>💧 Voda: {clarityLabel[a.water_clarity||'unknown']}</span><span>🌱 Rastliny: {plantLabel[a.plant_condition||'unknown']}</span>{a.algae_detected&&<span>🦠 Riasy: {algaeLabel[a.algae_severity||'unknown']}{a.algae_types?.length?` · ${a.algae_types.join(', ')}`:''}</span>}</div>{a.observations?.length?<div><b>Viditeľné zmeny / pozorovania</b><ul>{a.observations.map((x,i)=><li key={i}>{x}</li>)}</ul></div>:null}{a.suggested_actions?.length?<div><b>Odporúčané kroky</b><ul>{a.suggested_actions.map((x,i)=><li key={i}>{x}</li>)}</ul></div>:null}<small className="muted">Analýza vychádza iba z fotografie a nenahrádza meranie vody.</small></div>}</div></article>})}</div>}</section>
 </>;
}
