"use client";
import {useEffect,useState} from "react";
import {CalendarDays,Droplets,ShieldCheck} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import {scheduleDoseMl} from "@/lib/fertilizerSchedule";
import type {Aquarium} from "@/components/AquariumsModule";
type Assignment={id:string;custom_name?:string|null;fertilizer_catalog?:{manufacturer?:string|null;product_name:string;reference_dose_ml?:number|null;reference_liters?:number|null;nutrient_effects?:any}|null};
const nameOf=(a:Assignment)=>a.fertilizer_catalog?`${a.fertilizer_catalog.manufacturer||''} ${a.fertilizer_catalog.product_name}`.trim():a.custom_name||'Hnojivo';
export default function RegularFertilizerSchedule({aquariums}:{aquariums:Aquarium[]}){const[aquariumId,setAquariumId]=useState(aquariums[0]?.id||'');const[items,setItems]=useState<Assignment[]>([]);const[equipment,setEquipment]=useState<any[]>([]);useEffect(()=>{if(!aquariumId&&aquariums[0])setAquariumId(aquariums[0].id)},[aquariums,aquariumId]);useEffect(()=>{if(!aquariumId)return;(async()=>{const s=createClient();const[a,e]=await Promise.all([s.from('aquarium_fertilizers').select('id,custom_name,fertilizer_catalog(manufacturer,product_name,reference_dose_ml,reference_liters,nutrient_effects)').eq('aquarium_id',aquariumId).eq('available',true).order('created_at'),s.from('aquarium_equipment').select('category,specs,settings').eq('aquarium_id',aquariumId).eq('active',true)]);setItems((a.data||[]) as any);setEquipment(e.data||[])})()},[aquariumId]);const aq=aquariums.find(x=>x.id===aquariumId),hasCo2=equipment.some(x=>x.category==='co2'),watts=equipment.filter(x=>x.category==='light').reduce((sum,x)=>sum+Number(x.specs?.light_w||x.specs?.power_w||0)*(Number(x.settings?.intensity_pct??100)/100),0),highLight=!!aq&&watts/aq.net_volume_l>=.4;return <><section className="card"><div className="section-head"><div><small>PRAVIDELNÉ HNOJENIE</small><h3><CalendarDays size={18}/> Overený dávkovací režim</h3></div></div><p className="muted">Zobrazujú sa iba režimy, ktorých frekvencia a dávka boli štruktúrovane overené administrátorom. Text popisu ani etikety sa automaticky neinterpretuje.</p><div className="form one"><label>Akvárium<select value={aquariumId} onChange={e=>setAquariumId(e.target.value)}>{aquariums.map(a=><option key={a.id} value={a.id}>{a.name} · {a.net_volume_l} l</option>)}</select></label></div></section><section className="card"><h3><Droplets size={18}/> Odporúčaný pravidelný režim</h3>{!aq?<p>Najprv vytvor akvárium.</p>:items.length===0?<p className="muted">V tomto akváriu zatiaľ nie je pridané žiadne hnojivo.</p>:<div style={{display:'grid',gap:10}}>{items.map(a=>{const c=a.fertilizer_catalog;const s=c?scheduleDoseMl({effects:c.nutrient_effects,referenceDoseMl:Number(c.reference_dose_ml||0),referenceLiters:Number(c.reference_liters||0),liters:aq.net_volume_l,hasCo2,highLight}):null;return <div className="measurement-row" key={a.id}><div><b>{nameOf(a)}</b><small>{s?<><ShieldCheck size={12}/> Overený režim</>:'Pravidelné dávkovanie nie je dostatočne overené.'}</small></div><div>{s?<><b>{s.ml.toFixed(2)} ml</b><small>{s.frequency}</small></>:<span className="muted">Bez automatického režimu</span>}</div></div>})}</div>}<div className="notice" style={{marginTop:12}}>🛡️ Korekčné odporúčanie podľa aktuálneho merania má prednosť pred pravidelným režimom. Ak je niektorá živina už vysoká, pravidelnú dávku nepoužívaj automaticky.</div></section></>}
