"use client";
import {useEffect,useState} from "react";
import {Save,RotateCcw,User,SlidersHorizontal,Crown,KeyRound,CheckCircle2} from "lucide-react";
import {createClient} from "@/lib/supabase/client";

type Props={email:string};
type SettingsState={defaultWaterSource:'tap'|'ro'|'mixed';defaultGh:string;defaultKh:string;confirmDeletes:boolean;compactCards:boolean};
const defaults:SettingsState={defaultWaterSource:'tap',defaultGh:'6',defaultKh:'3',confirmDeletes:true,compactCards:false};
const KEY='duoakva-user-settings-v1';

export default function SettingsModule({email}:Props){
 const[state,setState]=useState<SettingsState>(defaults);const[saved,setSaved]=useState(false);
 const[premiumUntil,setPremiumUntil]=useState<string|null>(null);const[premiumLoaded,setPremiumLoaded]=useState(false);const[code,setCode]=useState('');const[activating,setActivating]=useState(false);const[premiumMsg,setPremiumMsg]=useState('');
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setState({...defaults,...JSON.parse(raw)})}catch{};loadPremium()},[]);
 async function loadPremium(){const s=createClient();const{data:u}=await s.auth.getUser();if(!u.user){setPremiumLoaded(true);return}const{data}=await s.from('user_subscriptions').select('premium_until').eq('user_id',u.user.id).maybeSingle();setPremiumUntil(data?.premium_until||null);setPremiumLoaded(true)}
 function save(){localStorage.setItem(KEY,JSON.stringify(state));setSaved(true);setTimeout(()=>setSaved(false),1800)}
 function reset(){setState(defaults);localStorage.removeItem(KEY);setSaved(true);setTimeout(()=>setSaved(false),1800)}
 async function activatePremium(e:React.FormEvent){e.preventDefault();const clean=code.trim();if(!clean){setPremiumMsg('Zadaj aktivačný kód z objednávky.');return}setActivating(true);setPremiumMsg('');const s=createClient();const{data,error}=await s.rpc('activate_premium_code',{p_code:clean});setActivating(false);if(error){setPremiumMsg('Aktivácia sa nepodarila. Skús to prosím znova.');return}const r=data as any;if(!r?.ok){setPremiumMsg(r?.error==='already_redeemed'?'Tento aktivačný kód už bol použitý.':'Aktivačný kód nie je platný. Skontroluj ho a skús znova.');return}setCode('');setPremiumUntil(r.premium_until||null);setPremiumMsg(`Premium bolo aktivované. Pridaných ${r.days_added} dní.`)}
 const premiumActive=!!premiumUntil&&new Date(premiumUntil).getTime()>Date.now();
 return <>
 <section className="card"><h3><User size={18}/> Účet</h3><p><b>Prihlásený používateľ:</b> {email||'—'}</p><p className="muted">Účet a autentifikáciu spravuje Supabase. Tieto nastavenia sa zatiaľ ukladajú lokálne v tomto zariadení.</p></section>
 <section className="card"><div className="section-head"><div><small>DUOAKVA DIARY</small><h3><Crown size={18}/> Premium</h3></div>{premiumLoaded&&<span className={`status-pill ${premiumActive?'status-green':'status-neutral'}`}>{premiumActive?'⭐ PREMIUM':'FREE'}</span>}</div>{!premiumLoaded?<p className="muted">Načítavam stav licencie…</p>:premiumActive?<div className="notice"><CheckCircle2 size={16}/> <b>Premium je aktívne.</b><p style={{marginBottom:0}}>Platnosť do: <b>{new Date(premiumUntil!).toLocaleDateString('sk-SK')}</b></p></div>:<div className="notice"><b>Používaš bezplatnú verziu DuoAkva Diary.</b><p style={{marginBottom:0}}>Premium odomkne viac akvárií, AI analýzu a pokročilý vývoj nádrže.</p></div>}<form className="form one" onSubmit={activatePremium}><label>Aktivačný kód<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Napr. DUO-PREM-XXXX-XXXX" autoComplete="off"/></label><div className="form-actions"><button className="primary" disabled={activating}><KeyRound size={16}/>{activating?' Aktivujem…':premiumActive?' Predĺžiť Premium':' Aktivovať Premium'}</button></div></form>{premiumMsg&&<div className="notice">{premiumMsg}</div>}<small className="muted">Kód z mesačného produktu pridá 30 dní, ročný kód 365 dní. Ak Premium ešte platí, nový čas sa pripočíta k aktuálnemu dátumu skončenia.</small></section>
 <section className="card"><h3><SlidersHorizontal size={18}/> Predvolené hodnoty</h3><div className="grid3"><label>Predvolený zdroj vody<select value={state.defaultWaterSource} onChange={e=>setState({...state,defaultWaterSource:e.target.value as any})}><option value="tap">Vodovodná</option><option value="ro">Reverzná osmóza (RO)</option><option value="mixed">Mix RO + vodovodná</option></select></label><label>Predvolené cieľové GH<input type="number" step="0.1" min="0" value={state.defaultGh} onChange={e=>setState({...state,defaultGh:e.target.value})}/></label><label>Predvolené cieľové KH<input type="number" step="0.1" min="0" value={state.defaultKh} onChange={e=>setState({...state,defaultKh:e.target.value})}/></label></div><label style={{display:'block',marginTop:12}}><input type="checkbox" checked={state.confirmDeletes} onChange={e=>setState({...state,confirmDeletes:e.target.checked})}/> Potvrdzovať mazanie záznamov</label><label style={{display:'block',marginTop:8}}><input type="checkbox" checked={state.compactCards} onChange={e=>setState({...state,compactCards:e.target.checked})}/> Kompaktnejšie karty</label><div className="form-actions" style={{marginTop:16}}><button className="primary" onClick={save}><Save size={16}/> Uložiť nastavenia</button><button onClick={reset}><RotateCcw size={16}/> Obnoviť predvolené</button></div>{saved&&<div className="notice">✅ Nastavenia boli uložené.</div>}</section>
 </>;
}
