"use client";
import {useEffect,useState} from "react";
import {Save,RotateCcw,User,SlidersHorizontal,Crown,KeyRound,CheckCircle2,ShieldCheck,Trash2,Mail} from "lucide-react";
import {createClient} from "@/lib/supabase/client";

type Props={email:string};
type SettingsState={defaultWaterSource:'tap'|'ro'|'mixed';defaultGh:string;defaultKh:string;confirmDeletes:boolean;compactCards:boolean};
const defaults:SettingsState={defaultWaterSource:'tap',defaultGh:'6',defaultKh:'3',confirmDeletes:true,compactCards:false};
const KEY='duoakva-user-settings-v1';const PREMIUM_TERMS_VERSION='2026-08-24';

export default function SettingsModule({email}:Props){
 const[state,setState]=useState<SettingsState>(defaults);const[saved,setSaved]=useState(false);const[premiumUntil,setPremiumUntil]=useState<string|null>(null);const[premiumLoaded,setPremiumLoaded]=useState(false);const[code,setCode]=useState('');const[activating,setActivating]=useState(false);const[premiumMsg,setPremiumMsg]=useState('');const[legalConsent,setLegalConsent]=useState(false);const[deleting,setDeleting]=useState(false);const[deleteConfirm,setDeleteConfirm]=useState('');const[accountMsg,setAccountMsg]=useState('');const[emailTasks,setEmailTasks]=useState(false);const[emailPrefLoaded,setEmailPrefLoaded]=useState(false);const[emailPrefBusy,setEmailPrefBusy]=useState(false);const[emailPrefMsg,setEmailPrefMsg]=useState('');const[isAdmin,setIsAdmin]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setState({...defaults,...JSON.parse(raw)})}catch{};loadAccountState()},[]);
 async function loadAccountState(){const s=createClient();const{data:u}=await s.auth.getUser();if(!u.user){setPremiumLoaded(true);setEmailPrefLoaded(true);return}const[sub,profile,admin]=await Promise.all([s.from('user_subscriptions').select('premium_until').eq('user_id',u.user.id).maybeSingle(),s.from('profiles').select('email_task_notifications').eq('id',u.user.id).maybeSingle(),s.rpc('is_admin_user',{p_user:u.user.id})]);setPremiumUntil(sub.data?.premium_until||null);setEmailTasks(!!profile.data?.email_task_notifications);setIsAdmin(admin.data===true);setPremiumLoaded(true);setEmailPrefLoaded(true)}
 function save(){localStorage.setItem(KEY,JSON.stringify(state));setSaved(true);setTimeout(()=>setSaved(false),1800)}function reset(){setState(defaults);localStorage.removeItem(KEY);setSaved(true);setTimeout(()=>setSaved(false),1800)}
 async function saveEmailPreference(){const s=createClient();const{data:u}=await s.auth.getUser();if(!u.user)return;setEmailPrefBusy(true);setEmailPrefMsg('');const{error}=await s.from('profiles').upsert({id:u.user.id,email_task_notifications:emailTasks},{onConflict:'id'});setEmailPrefBusy(false);setEmailPrefMsg(error?'Nastavenie sa nepodarilo uložiť.':'Nastavenie e-mailových upozornení bolo uložené.')}
 async function activatePremium(e:React.FormEvent){e.preventDefault();const clean=code.trim();if(!clean){setPremiumMsg('Zadaj aktivačný kód z objednávky.');return}if(!legalConsent){setPremiumMsg('Pred aktiváciou je potrebné potvrdiť žiadosť o okamžité začatie poskytovania Premium.');return}setActivating(true);const s=createClient();const{data,error}=await s.rpc('activate_premium_code',{p_code:clean,p_legal_consent:true,p_terms_version:PREMIUM_TERMS_VERSION});setActivating(false);if(error){setPremiumMsg('Aktivácia sa nepodarila.');return}const r=data as any;if(!r?.ok){setPremiumMsg(r?.error==='already_redeemed'?'Tento aktivačný kód už bol použitý.':'Aktivačný kód nie je platný.');return}setCode('');setLegalConsent(false);setPremiumUntil(r.premium_until||null);setPremiumMsg('Premium bolo aktivované.')}
 async function deleteAccount(){if(deleteConfirm!=='VYMAZAŤ')return;setDeleting(true);const s=createClient();const{error}=await s.functions.invoke('delete-my-account',{body:{confirm:true}});if(error){setDeleting(false);setAccountMsg('Účet sa nepodarilo vymazať.');return}localStorage.removeItem(KEY);await s.auth.signOut();window.location.href='/'}
 const premiumActive=isAdmin||(!!premiumUntil&&new Date(premiumUntil).getTime()>Date.now());
 return <><section className="card"><h3><User size={18}/> Účet</h3><p><b>Prihlásený používateľ:</b> {email||'—'}</p>{isAdmin&&<div className="notice"><b>🛡️ Administrátor</b><p style={{marginBottom:0}}>Tento účet má automaticky všetky Premium oprávnenia bez aktivačného kódu a expirácie.</p></div>}</section>
 <section className="card"><div className="section-head"><div><small>UPOZORNENIA</small><h3><Mail size={18}/> E-mailové upozornenia na úlohy</h3></div></div>{!emailPrefLoaded?<p className="muted">Načítavam nastavenie…</p>:<><label style={{display:'flex',alignItems:'flex-start',gap:10,cursor:'pointer'}}><input type="checkbox" checked={emailTasks} onChange={e=>setEmailTasks(e.target.checked)} style={{width:18,height:18,marginTop:2}}/><span><b>Posielať e-mailové pripomienky úloh</b><br/><small className="muted">Ak máš v daný deň naplánovanú jednu alebo viac otvorených úloh, dostaneš jeden súhrnný e-mail. Funkciu môžeš kedykoľvek vypnúť.</small></span></label><div className="form-actions" style={{marginTop:12}}><button className="primary" type="button" onClick={saveEmailPreference} disabled={emailPrefBusy}>{emailPrefBusy?'Ukladám…':'Uložiť nastavenie upozornení'}</button></div>{emailPrefMsg&&<div className="notice">{emailPrefMsg}</div>}</>}</section>
 <section className="card"><div className="section-head"><div><small>DUOAKVA DIARY</small><h3><Crown size={18}/> Premium</h3></div>{premiumLoaded&&<span className={`status-pill ${premiumActive?'status-green':'status-neutral'}`}>{premiumActive?'⭐ PREMIUM':'FREE'}</span>}</div>{isAdmin?<div className="notice"><CheckCircle2 size={16}/> <b>Admin Premium je aktívne bez obmedzenia.</b></div>:premiumActive?<div className="notice"><CheckCircle2 size={16}/> <b>Premium je aktívne.</b><p style={{marginBottom:0}}>Platnosť do: <b>{new Date(premiumUntil!).toLocaleDateString('sk-SK')}</b></p></div>:<div className="notice"><b>Používaš bezplatnú verziu DuoAkva Diary.</b></div>}{!isAdmin&&<form className="form one" onSubmit={activatePremium}><label>Aktivačný kód<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} autoComplete="off"/></label><div className="notice"><label style={{display:'flex',alignItems:'flex-start',gap:10,fontWeight:400}}><input type="checkbox" checked={legalConsent} onChange={e=>setLegalConsent(e.target.checked)}/><span>Výslovne žiadam o začatie poskytovania DuoAkva Diary Premium pred uplynutím 14-dňovej lehoty na odstúpenie od zmluvy.</span></label></div><button className="primary" disabled={activating||!legalConsent}><KeyRound size={16}/> Aktivovať Premium</button></form>}{premiumMsg&&<div className="notice">{premiumMsg}</div>}</section>
 <section className="card"><h3><SlidersHorizontal size={18}/> Predvolené hodnoty</h3><div className="grid3"><label>Predvolený zdroj vody<select value={state.defaultWaterSource} onChange={e=>setState({...state,defaultWaterSource:e.target.value as any})}><option value="tap">Vodovodná</option><option value="ro">Reverzná osmóza (RO)</option><option value="mixed">Mix RO + vodovodná</option></select></label><label>Predvolené cieľové GH<input type="number" step="0.1" min="0" value={state.defaultGh} onChange={e=>setState({...state,defaultGh:e.target.value})}/></label><label>Predvolené cieľové KH<input type="number" step="0.1" min="0" value={state.defaultKh} onChange={e=>setState({...state,defaultKh:e.target.value})}/></label></div><label style={{display:'block',marginTop:12}}><input type="checkbox" checked={state.confirmDeletes} onChange={e=>setState({...state,confirmDeletes:e.target.checked})}/> Potvrdzovať mazanie záznamov</label><label style={{display:'block',marginTop:8}}><input type="checkbox" checked={state.compactCards} onChange={e=>setState({...state,compactCards:e.target.checked})}/> Kompaktnejšie karty</label><div className="form-actions" style={{marginTop:16}}><button className="primary" onClick={save}><Save size={16}/> Uložiť nastavenia</button><button onClick={reset}><RotateCcw size={16}/> Obnoviť predvolené</button></div>{saved&&<div className="notice">✅ Nastavenia boli uložené.</div>}</section>
 <section className="card"><div className="section-head"><div><small>SÚKROMIE A ÚČET</small><h3><Trash2 size={18}/> Vymazanie účtu</h3></div></div><label>Pre potvrdenie napíš <b>VYMAZAŤ</b><input value={deleteConfirm} onChange={e=>setDeleteConfirm(e.target.value)} placeholder="VYMAZAŤ"/></label><div className="form-actions"><button type="button" onClick={deleteAccount} disabled={deleting||deleteConfirm!=='VYMAZAŤ'}><Trash2 size={16}/>{deleting?' Vymazávam účet…':' Natrvalo vymazať účet'}</button></div>{accountMsg&&<div className="notice">{accountMsg}</div>}</section></>;
}
