"use client";
import {useEffect,useMemo,useState} from "react";
import {Bell,CheckCircle2,Plus,Trash2,Pencil,X} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import type {Aquarium} from "@/components/AquariumsModule";

type Task={id:string;aquarium_id:string;title:string;notes?:string|null;due_at?:string|null;recurrence:string;status:string;completed_at?:string|null;created_at:string};
const recurrenceLabels:Record<string,string>={none:'Jednorazová',daily:'Denne',weekly:'Týždenne',biweekly:'Každé 2 týždne',monthly:'Mesačne'};
const fmt=(s?:string|null)=>s?new Date(s).toLocaleString('sk-SK'):'Bez termínu';
const localDateTime=(iso?:string|null)=>{if(!iso)return'';const d=new Date(iso);const z=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`};
function nextDue(from:string,recurrence:string){const d=new Date(from);if(recurrence==='daily')d.setDate(d.getDate()+1);else if(recurrence==='weekly')d.setDate(d.getDate()+7);else if(recurrence==='biweekly')d.setDate(d.getDate()+14);else if(recurrence==='monthly')d.setMonth(d.getMonth()+1);return d.toISOString()}

export default function TasksModule({aquariums}:{aquariums:Aquarium[]}){
 const[aquariumId,setAquariumId]=useState(aquariums[0]?.id||'');const[tasks,setTasks]=useState<Task[]>([]);const[show,setShow]=useState(false);const[title,setTitle]=useState('');const[notes,setNotes]=useState('');const[due,setDue]=useState('');const[recurrence,setRecurrence]=useState('none');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
 const[editing,setEditing]=useState<Task|null>(null);const[editTitle,setEditTitle]=useState('');const[editNotes,setEditNotes]=useState('');const[editDue,setEditDue]=useState('');const[editRecurrence,setEditRecurrence]=useState('none');
 useEffect(()=>{if(!aquariumId&&aquariums[0])setAquariumId(aquariums[0].id)},[aquariums,aquariumId]);useEffect(()=>{if(aquariumId)load()},[aquariumId]);
 async function load(){const{data,error}=await createClient().from('aquarium_tasks').select('*').eq('aquarium_id',aquariumId).order('status').order('due_at',{ascending:true,nullsFirst:false});if(error){setMsg('Úlohy sa nepodarilo načítať.');return}setTasks((data||[]) as Task[]);setMsg('')}
 async function add(e:React.FormEvent){e.preventDefault();if(!title.trim()){setMsg('Zadaj názov úlohy.');return}if(recurrence!=='none'&&!due){setMsg('Pri opakovanej úlohe zadaj prvý termín.');return}setBusy(true);const{error}=await createClient().from('aquarium_tasks').insert({aquarium_id:aquariumId,title:title.trim(),notes:notes.trim()||null,due_at:due?new Date(due).toISOString():null,recurrence,status:'open'});setBusy(false);if(error){setMsg('Úlohu sa nepodarilo uložiť.');return}setTitle('');setNotes('');setDue('');setRecurrence('none');setShow(false);await load();setMsg('Úloha bola uložená.')}
 function startEdit(t:Task){setEditing(t);setEditTitle(t.title);setEditNotes(t.notes||'');setEditDue(localDateTime(t.due_at));setEditRecurrence(t.recurrence||'none')}
 async function saveEdit(e:React.FormEvent){e.preventDefault();if(!editing)return;if(!editTitle.trim()){setMsg('Zadaj názov úlohy.');return}if(editRecurrence!=='none'&&!editDue){setMsg('Pri opakovanej úlohe zadaj termín.');return}setBusy(true);const{error}=await createClient().from('aquarium_tasks').update({title:editTitle.trim(),notes:editNotes.trim()||null,due_at:editDue?new Date(editDue).toISOString():null,recurrence:editRecurrence}).eq('id',editing.id);setBusy(false);if(error){setMsg('Úlohu sa nepodarilo upraviť.');return}setEditing(null);await load();setMsg('Úloha bola upravená.')}
 async function complete(t:Task){const s=createClient();const now=new Date().toISOString();const{error}=await s.from('aquarium_tasks').update({status:'done',completed_at:now}).eq('id',t.id);if(error){setMsg('Úlohu sa nepodarilo označiť ako dokončenú.');return}if(t.recurrence!=='none'&&t.due_at){const{error:repeatError}=await s.from('aquarium_tasks').insert({aquarium_id:t.aquarium_id,title:t.title,notes:t.notes||null,due_at:nextDue(t.due_at,t.recurrence),recurrence:t.recurrence,status:'open'});if(repeatError){setMsg('Úloha je dokončená, ale ďalší termín sa nepodarilo vytvoriť.');await load();return}}await load()}
 async function remove(id:string){if(!confirm('Odstrániť túto úlohu?'))return;const{error}=await createClient().from('aquarium_tasks').delete().eq('id',id);if(error){setMsg('Úlohu sa nepodarilo odstrániť.');return}if(editing?.id===id)setEditing(null);await load()}
 const open=useMemo(()=>tasks.filter(t=>t.status!=='done'),[tasks]);const done=useMemo(()=>tasks.filter(t=>t.status==='done').slice(0,20),[tasks]);const now=Date.now();
 if(!aquariums.length)return <section className="card"><h3>Úlohy</h3><p>Najprv vytvor akvárium.</p></section>;
 return <><div className="toolbar"><label>Akvárium <select value={aquariumId} onChange={e=>{setAquariumId(e.target.value);setEditing(null)}}>{aquariums.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button className="primary" onClick={()=>{setMsg('');setShow(true)}}><Plus size={17}/> Nová úloha</button></div>{msg&&<div className="notice">{msg}</div>}
 {show&&<section className="card"><h3>Nová úloha</h3><form className="form" onSubmit={add}><label>Názov<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Termín<input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label><label>Opakovanie<select value={recurrence} onChange={e=>setRecurrence(e.target.value)}>{Object.entries(recurrenceLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Poznámka<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="form-actions"><button className="primary" disabled={busy}>Uložiť</button><button type="button" onClick={()=>setShow(false)}>Zrušiť</button></div></form></section>}
 {editing&&<section className="card"><div className="section-head"><h3><Pencil size={17}/> Upraviť úlohu</h3><button type="button" onClick={()=>setEditing(null)}><X size={16}/> Zavrieť</button></div><form className="form" onSubmit={saveEdit}><label>Názov<input required value={editTitle} onChange={e=>setEditTitle(e.target.value)}/></label><label>Termín<input type="datetime-local" value={editDue} onChange={e=>setEditDue(e.target.value)}/></label><label>Opakovanie<select value={editRecurrence} onChange={e=>setEditRecurrence(e.target.value)}>{Object.entries(recurrenceLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Poznámka<textarea value={editNotes} onChange={e=>setEditNotes(e.target.value)}/></label><div className="form-actions"><button className="primary" disabled={busy}>Uložiť zmeny</button><button type="button" onClick={()=>setEditing(null)}>Zrušiť</button></div></form></section>}
 <section className="card"><h3><Bell size={18}/> Aktívne úlohy</h3>{open.length===0?<div className="notice">🟢 Nemáš žiadne otvorené úlohy.</div>:<div style={{display:'grid',gap:10}}>{open.map(t=>{const overdue=!!t.due_at&&new Date(t.due_at).getTime()<now;return <article className="card" key={t.id} style={overdue?{borderColor:'rgba(239,68,68,.45)',background:'rgba(239,68,68,.08)'}:undefined}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><b>{overdue?'🔴 ':t.due_at?'🟠 ':'🟢 '}{t.title}</b><p className="muted">{fmt(t.due_at)} · {recurrenceLabels[t.recurrence]||t.recurrence}</p>{overdue&&<p><b>Po termíne</b></p>}{t.notes&&<p>{t.notes}</p>}</div><div className="form-actions"><button onClick={()=>startEdit(t)}><Pencil size={15}/> Upraviť</button><button onClick={()=>complete(t)}><CheckCircle2 size={15}/> Hotovo</button><button className="danger" onClick={()=>remove(t.id)}><Trash2 size={15}/></button></div></div></article>})}</div>}</section>
 {done.length>0&&<section className="card"><h3>Posledné dokončené</h3>{done.map(t=><div className="notice" key={t.id}><b>✅ {t.title}</b><span className="muted"> · dokončené {fmt(t.completed_at)}</span></div>)}</section>}</>;
}
