"use client";
import {useEffect,useState} from "react";
import {Droplets,Plus,Trash2} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import type {Aquarium} from "@/components/AquariumsModule";
type Catalog={id:string;manufacturer?:string;product_name:string;treatment_type:string;form:string;dose_unit:string;reference_dose:number|null;reference_liters:number|null;gh_increase:number|null;kh_increase:number|null;ca_mg_ratio?:string;notes?:string;verification_status:string};
type Item={id:string;treatment_id?:string;custom_name?:string;custom_data:any;water_treatment_catalog?:Catalog|null};
export default function WaterTreatmentModule({aquariums}:{aquariums:Aquarium[]}){
 const[aquariumId,setAquariumId]=useState(aquariums[0]?.id||'');const[items,setItems]=useState<Item[]>([]);const[catalog,setCatalog]=useState<Catalog[]>([]);const[msg,setMsg]=useState('');const[show,setShow]=useState(false);
 useEffect(()=>{if(!aquariumId&&aquariums[0])setAquariumId(aquariums[0].id)},[aquariums,aquariumId]);useEffect(()=>{if(aquariumId)load()},[aquariumId]);
 async function load(){const s=createClient();const[c,i]=await Promise.all([s.from('water_treatment_catalog').select('*').order('manufacturer'),s.from('aquarium_water_treatments').select('id,treatment_id,custom_name,custom_data,water_treatment_catalog(*)').eq('aquarium_id',aquariumId).eq('available',true).order('created_at')]);if(c.error||i.error){setMsg('Modul úpravy vody ešte potrebuje databázovú migráciu.');return}setCatalog((c.data||[]) as any);setItems((i.data||[]) as any);setMsg('')}
 async function add(c:Catalog){const{error}=await createClient().from('aquarium_water_treatments').insert({aquarium_id:aquariumId,treatment_id:c.id,available:true});if(error)return setMsg(error.message);setShow(false);load()}
 async function remove(id:string){await createClient().from('aquarium_water_treatments').delete().eq('id',id);load()}
 if(!aquariums.length)return null;
 return <section className="card"><h3><Droplets size={18}/> Úprava vody / mineralizácia</h3><p className="muted">Tu si uložíš prípravky pre RO alebo veľmi mäkkú vodu. Dávku pri konkrétnej výmene vody aplikácia vypočíta priamo v karte Údržba.</p><div className="toolbar"><label>Akvárium <select value={aquariumId} onChange={e=>setAquariumId(e.target.value)}>{aquariums.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button onClick={()=>setShow(!show)}><Plus size={16}/> Pridať prípravok</button></div>{msg&&<div className="notice">{msg}</div>}{show&&<div className="card"><h4>Katalóg prípravkov</h4>{catalog.filter(c=>!items.some(i=>i.treatment_id===c.id)).map(c=><div key={c.id} className="notice"><b>{c.manufacturer} {c.product_name}</b><p>{c.reference_dose} {c.dose_unit} / {c.reference_liters} l → GH +{c.gh_increase??0} · KH +{c.kh_increase??0}</p>{c.notes&&<p className="muted">{c.notes}</p>}<button onClick={()=>add(c)}>Pridať</button></div>)}{!catalog.filter(c=>!items.some(i=>i.treatment_id===c.id)).length&&<p>Všetky dostupné prípravky už máš pridané.</p>}</div>}<div style={{display:'grid',gap:8}}>{items.map(x=>{const c=x.water_treatment_catalog;return <div className="notice" key={x.id}><b>{c?`${c.manufacturer||''} ${c.product_name}`:x.custom_name}</b>{c&&<p>{c.reference_dose} {c.dose_unit} / {c.reference_liters} l → GH +{c.gh_increase??0} · KH +{c.kh_increase??0}{c.ca_mg_ratio?` · Ca:Mg ${c.ca_mg_ratio}`:''}</p>}{c?.notes&&<p className="muted">{c.notes}</p>}<button className="danger" onClick={()=>remove(x.id)}><Trash2 size={14}/> Odstrániť</button></div>})}{!items.length&&<p>Zatiaľ nemáš uložený žiadny prípravok na úpravu vody.</p>}</div></section>;
}