import {createServerSupabaseClient} from "@/lib/supabase/server";
import {createClient} from "@supabase/supabase-js";

export const runtime="nodejs";export const dynamic="force-dynamic";
const KIND="catalog_correction_v1";
function service(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("missing_supabase_server_config");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function caller(){const s=await createServerSupabaseClient();const{data}=await s.auth.getUser();return data.user||null}
async function isAdmin(id:string){const s=await createServerSupabaseClient();const{data}=await s.from("profiles").select("role").eq("id",id).maybeSingle();return data?.role==="admin"}
function parse(message:string){try{const v=JSON.parse(message);return v?.kind===KIND?v:null}catch{return null}}

export async function POST(req:Request){const u=await caller();if(!u)return Response.json({ok:false,error:"unauthorized"},{status:401});const body=await req.json().catch(()=>null) as any;if(!body)return Response.json({ok:false,error:"invalid_body"},{status:400});const entityType=String(body.entityType||"");const entityKey=String(body.entityKey||"").trim();const entityLabel=String(body.entityLabel||entityKey).trim();const proposedValue=String(body.proposedValue||"").trim();if(!["fertilizer","plant","livestock","equipment"].includes(entityType)||!entityKey||proposedValue.length<2)return Response.json({ok:false,error:"invalid_report"},{status:400});const payload={kind:KIND,entityType,entityKey,entityLabel,currentValue:String(body.currentValue||"").slice(0,1500)||null,proposedValue:proposedValue.slice(0,1500),packageLabelText:String(body.packageLabelText||"").slice(0,3000)||null,userNote:String(body.userNote||"").slice(0,3000)||null,status:"pending",submittedAt:new Date().toISOString()};const s=service();const{error}=await s.from("user_feedback").insert({user_id:u.id,email:u.email||null,category:"bug",message:JSON.stringify(payload),page:"catalog-correction"});if(error)return Response.json({ok:false,error:error.message},{status:500});return Response.json({ok:true})}

export async function GET(){const u=await caller();if(!u||!await isAdmin(u.id))return Response.json({ok:false,error:"forbidden"},{status:403});const{data,error}=await service().from("user_feedback").select("id,user_id,email,message,created_at").eq("page","catalog-correction").order("created_at",{ascending:false}).limit(500);if(error)return Response.json({ok:false,error:error.message},{status:500});const parsed=(data||[]).flatMap((r:any)=>{const p=parse(r.message);return p?[{id:r.id,userId:r.user_id,email:r.email,createdAt:r.created_at,...p}]:[]});const counts=new Map<string,number>();for(const r of parsed){if(!["pending","needs_review"].includes(r.status))continue;const k=`${r.entityType}|${r.entityKey}|${r.proposedValue}`.toLowerCase();counts.set(k,(counts.get(k)||0)+1)}return Response.json({ok:true,items:parsed.map(r=>({...r,matchingReports:counts.get(`${r.entityType}|${r.entityKey}|${r.proposedValue}`.toLowerCase())||1}))})}

export async function PATCH(req:Request){const u=await caller();if(!u||!await isAdmin(u.id))return Response.json({ok:false,error:"forbidden"},{status:403});const body=await req.json().catch(()=>null) as any;const id=String(body?.id||""),status=String(body?.status||"");if(!id||!["approved","rejected","needs_review"].includes(status))return Response.json({ok:false,error:"invalid_review"},{status:400});const s=service();const{data,error}=await s.from("user_feedback").select("message").eq("id",id).maybeSingle();if(error||!data)return Response.json({ok:false,error:error?.message||"not_found"},{status:404});const p=parse(data.message);if(!p)return Response.json({ok:false,error:"not_catalog_report"},{status:400});const next={...p,status,reviewedAt:new Date().toISOString(),reviewedBy:u.id,reviewNote:String(body.reviewNote||"").slice(0,2000)||null};const{error:e2}=await s.from("user_feedback").update({message:JSON.stringify(next)}).eq("id",id);if(e2)return Response.json({ok:false,error:e2.message},{status:500});return Response.json({ok:true})}
