import {createServerSupabaseClient} from "@/lib/supabase/server";
import {createClient} from "@supabase/supabase-js";

export const runtime="nodejs";export const dynamic="force-dynamic";
const KIND="catalog_correction_v1";
function service(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("missing_supabase_server_config");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function caller(){const s=await createServerSupabaseClient();const{data}=await s.auth.getUser();return data.user||null}
async function isAdmin(id:string){const s=await createServerSupabaseClient();const{data}=await s.from("profiles").select("role").eq("id",id).maybeSingle();return data?.role==="admin"}
function parse(message:string){try{const v=JSON.parse(message);return v?.kind===KIND?v:null}catch{return null}}
const finite=(v:any)=>v===""||v==null?null:Number.isFinite(Number(v))?Number(v):null;

export async function POST(req:Request){const u=await caller();if(!u)return Response.json({ok:false,error:"unauthorized"},{status:401});const body=await req.json().catch(()=>null) as any;if(!body)return Response.json({ok:false,error:"invalid_body"},{status:400});const entityType=String(body.entityType||"");const entityKey=String(body.entityKey||"").trim();const entityLabel=String(body.entityLabel||entityKey).trim();const proposedValue=String(body.proposedValue||"").trim();if(!["fertilizer","plant","livestock","equipment"].includes(entityType)||!entityKey||proposedValue.length<2)return Response.json({ok:false,error:"invalid_report"},{status:400});const payload={kind:KIND,entityType,entityKey,entityLabel,currentValue:String(body.currentValue||"").slice(0,1500)||null,proposedValue:proposedValue.slice(0,1500),packageLabelText:String(body.packageLabelText||"").slice(0,3000)||null,userNote:String(body.userNote||"").slice(0,3000)||null,status:"pending",submittedAt:new Date().toISOString()};const s=service();const{error}=await s.from("user_feedback").insert({user_id:u.id,email:u.email||null,category:"bug",message:JSON.stringify(payload),page:"catalog-correction"});if(error)return Response.json({ok:false,error:error.message},{status:500});return Response.json({ok:true})}

export async function GET(){const u=await caller();if(!u||!await isAdmin(u.id))return Response.json({ok:false,error:"forbidden"},{status:403});const s=service();const{data,error}=await s.from("user_feedback").select("id,user_id,email,message,created_at").eq("page","catalog-correction").order("created_at",{ascending:false}).limit(500);if(error)return Response.json({ok:false,error:error.message},{status:500});const parsed=(data||[]).flatMap((r:any)=>{const p=parse(r.message);return p?[{id:r.id,userId:r.user_id,email:r.email,createdAt:r.created_at,...p}]:[]});const counts=new Map<string,number>();for(const r of parsed){if(!["pending","needs_review"].includes(r.status))continue;const k=`${r.entityType}|${r.entityKey}|${r.proposedValue}`.toLowerCase();counts.set(k,(counts.get(k)||0)+1)}const fertilizerKeys=[...new Set(parsed.filter(r=>r.entityType==="fertilizer").map(r=>r.entityKey))];const catalog=new Map<string,any>();await Promise.all(fertilizerKeys.map(async k=>{const[manufacturer,product_name]=String(k).split("|");if(!manufacturer||!product_name)return;const{data:c}=await s.from("fertilizer_catalog").select("id,manufacturer,product_name,reference_liters,reference_dose_ml,nutrient_effects,dosing_instructions,official_url,source_url,verification_status").eq("manufacturer",manufacturer).eq("product_name",product_name).maybeSingle();if(c)catalog.set(k,c)}));return Response.json({ok:true,items:parsed.map(r=>({...r,matchingReports:counts.get(`${r.entityType}|${r.entityKey}|${r.proposedValue}`.toLowerCase())||1,catalogData:r.entityType==="fertilizer"?catalog.get(r.entityKey)||null:undefined}))})}

export async function PATCH(req:Request){const u=await caller();if(!u||!await isAdmin(u.id))return Response.json({ok:false,error:"forbidden"},{status:403});const body=await req.json().catch(()=>null) as any;const id=String(body?.id||""),status=String(body?.status||"");if(!id||!["approved","rejected","needs_review"].includes(status))return Response.json({ok:false,error:"invalid_review"},{status:400});const s=service();const{data,error}=await s.from("user_feedback").select("message").eq("id",id).maybeSingle();if(error||!data)return Response.json({ok:false,error:error?.message||"not_found"},{status:404});const p=parse(data.message);if(!p)return Response.json({ok:false,error:"not_catalog_report"},{status:400});
 if(status==="approved"&&p.entityType==="fertilizer"&&body.applyFertilizer){const a=body.applyFertilizer||{};const referenceDoseMl=finite(a.referenceDoseMl),referenceLiters=finite(a.referenceLiters);if(!referenceDoseMl||referenceDoseMl<=0||!referenceLiters||referenceLiters<=0)return Response.json({ok:false,error:"invalid_reference_dose"},{status:400});const[manufacturer,product_name]=String(p.entityKey).split("|");if(!manufacturer||!product_name)return Response.json({ok:false,error:"invalid_fertilizer_key"},{status:400});const{data:cat,error:ce}=await s.from("fertilizer_catalog").select("id,nutrient_effects").eq("manufacturer",manufacturer).eq("product_name",product_name).maybeSingle();if(ce||!cat)return Response.json({ok:false,error:ce?.message||"fertilizer_not_found"},{status:404});const effects:any={...(cat.nutrient_effects||{})};for(const code of ["no3","po4","k","fe","mg","ca"]){const v=finite(a.effects?.[code]);if(v==null)delete effects[code];else if(v<0)return Response.json({ok:false,error:`invalid_effect_${code}`},{status:400});else effects[code]=v}const sch=a.schedule||{};if(sch.verified===true){const kind=String(sch.frequencyKind||"");const mode=String(sch.mode||"");if(!["daily","per_week","as_needed"].includes(kind)||!["regular","correction","both"].includes(mode))return Response.json({ok:false,error:"invalid_schedule"},{status:400});const min=finite(sch.timesPerWeekMin),max=finite(sch.timesPerWeekMax);if(kind==="per_week"&&(!min||!max||min<=0||max<min))return Response.json({ok:false,error:"invalid_schedule_frequency"},{status:400});const variant=(x:any)=>{const v=finite(x);return v&&v>0?v:null};effects.__schedule={verified:true,mode,frequency_kind:kind,times_per_week_min:kind==="per_week"?min:null,times_per_week_max:kind==="per_week"?max:null,as_needed:!!sch.asNeeded,source_text:String(a.sourceText||p.packageLabelText||p.proposedValue||"").slice(0,3000)||null,source_url:String(a.sourceUrl||"").slice(0,1000)||null,verified_at:new Date().toISOString(),verified_by:u.id,variants:{no_co2_dose_ml:variant(sch.noCo2DoseMl),co2_low_light_dose_ml:variant(sch.co2LowLightDoseMl),co2_high_light_dose_ml:variant(sch.co2HighLightDoseMl)}}}else delete effects.__schedule;const{error:ue}=await s.from("fertilizer_catalog").update({reference_dose_ml:referenceDoseMl,reference_liters:referenceLiters,nutrient_effects:effects,dosing_instructions:String(a.sourceText||p.packageLabelText||p.proposedValue||"").slice(0,3000)||null,source_url:String(a.sourceUrl||"").slice(0,1000)||null,verification_status:"verified"}).eq("id",cat.id);if(ue)return Response.json({ok:false,error:ue.message},{status:500})}
 const next={...p,status,reviewedAt:new Date().toISOString(),reviewedBy:u.id,reviewNote:String(body.reviewNote||"").slice(0,2000)||null,appliedToCatalog:status==="approved"&&p.entityType==="fertilizer"&&!!body.applyFertilizer};const{error:e2}=await s.from("user_feedback").update({message:JSON.stringify(next)}).eq("id",id);if(e2)return Response.json({ok:false,error:e2.message},{status:500});return Response.json({ok:true})}
