import {NextRequest,NextResponse} from "next/server";
import {createServerSupabaseClient} from "@/lib/supabase/server";
const strip=(s:string)=>s.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim();
const unwrap=(raw:string)=>{let u=raw.replace(/&amp;/g,"&");try{const p=new URL(u.startsWith("//")?`https:${u}`:u);const r=p.searchParams.get("uddg")||p.searchParams.get("url");if(r)u=decodeURIComponent(r)}catch{}return u};
const allowed=(u:string)=>/(invital|shrimp\.sk|aquascaperi\.sk|akvariumonline|seachem\.com|jbl\.de|tropica\.com|easylife\.eu|sera\.de|dennerle\.com|adaeuro|greenleafaquariums)/i.test(u);
function parsePage(html:string,url:string,fallback:string){const text=strip(html);const title=strip(/<h1[^>]*>([\s\S]*?)<\/h1>/i.exec(html)?.[1]||/<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1]||fallback).replace(/\s*[|–-].*$/,'').trim()||fallback;const dosing=(text.match(/(?:dávkování|dávkovanie|dosage|dose|application)[^.]{0,350}\./i)||[])[0]||"";const desc=(text.match(/(?:Popis|Description|Charakteristika)[\s:.-]{0,20}(.{80,700}?)(?:Dávkov|Dosage|Použit|$)/i)?.[1]||text.slice(0,700)).trim();let manufacturer="";const hay=(title+" "+text).toLowerCase();for(const m of ["Seachem","JBL","INVITAL","Tropica","Easy-Life","Sera","Dennerle","ADA"]){if(hay.includes(m.toLowerCase())){manufacturer=m;break}}
 return{product_name:title,manufacturer,description:desc,dosing_instructions:dosing,reference_liters:100,reference_dose_ml:1,nutrient_effects:{},source_url:url,source_name:"Online zdroj",confidence:dosing?"medium":"low",verification_status:"pending"}}
export async function GET(req:NextRequest){const q=(req.nextUrl.searchParams.get("q")||"").trim();if(q.length<2)return NextResponse.json({items:[]});try{const s=await createServerSupabaseClient();const safe=q.replace(/[%(),]/g,"");const{data}=await s.from("fertilizer_catalog").select("id,manufacturer,product_name,reference_liters,reference_dose_ml,nutrient_effects,description,dosing_instructions,source_url,verification_status").or(`product_name.ilike.%${safe}%,manufacturer.ilike.%${safe}%,description.ilike.%${safe}%`).limit(20);if(data?.length)return NextResponse.json({items:data.map(x=>({...x,source_name:"Katalóg",confidence:"high"}))});
 const out:any[]=[];const searches=[`site:invital.sk "${q}"`,`site:invitalshop.sk "${q}"`,`site:shrimp.sk "${q}" hnojivo`,`site:aquascaperi.sk "${q}"`,`"${q}" aquarium fertilizer`,`"${q}" aquarium plant fertilizer dosage`];for(const sq of searches){try{const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(sq)}`,{headers:{"User-Agent":"Mozilla/5.0"},cache:"no-store",signal:AbortSignal.timeout(7000)});if(!r.ok)continue;const html=await r.text();const links=[...html.matchAll(/class="result__a"[^>]*href="([^"]+)"/gi)].map(m=>unwrap(m[1])).filter(u=>/^https?:/i.test(u)&&allowed(u)).slice(0,10);for(const u of links){if(out.some(x=>x.source_url===u))continue;try{const p=await fetch(u,{headers:{"User-Agent":"Mozilla/5.0"},cache:"no-store",signal:AbortSignal.timeout(7000)});if(!p.ok)continue;out.push(parsePage(await p.text(),u,q));if(out.length>=8)break}catch{}}}catch{}if(out.length>=8)break}
 if(!out.length)return NextResponse.json({items:[],message:"Produkt sa nepodarilo automaticky dohľadať vo verejne dostupných zdrojoch. Skús presnejší názov produktu alebo výrobcu."});return NextResponse.json({items:out.slice(0,8)})}catch(e:any){return NextResponse.json({items:[],error:e.message},{status:500})}}
