import {NextRequest,NextResponse} from "next/server";
import {createServerSupabaseClient} from "@/lib/supabase/server";
const strip=(s:string)=>s.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim();
const norm=(s:string)=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
const unwrap=(raw:string)=>{let u=raw.replace(/&amp;/g,"&");try{const p=new URL(u.startsWith("//")?`https:${u}`:u);const r=p.searchParams.get("uddg")||p.searchParams.get("url");if(r)u=decodeURIComponent(r)}catch{}return u};
const allowed=(u:string)=>/(invital|shrimp\.sk|aquascaperi\.sk|akvariumonline|seachem\.com|seachem\.zendesk\.com|jbl\.de|tropica\.com|easylife\.eu|sera\.de|dennerle\.com|adaeuro|greenleafaquariums|aquasabi\.(com|de)|plantica\.pl|zoobox\.de)/i.test(u);
const jblFamily=[
 {manufacturer:'JBL',product_name:'PROSCAPE Fe +MICROELEMENTS',description:'Základné hnojivo s Fe a mikroprvkami. Zloženie sa musí potvrdiť z deklarácie výrobcu.',dosing_instructions:'Denné/týždenné dávkovanie závisí od svetla, CO₂ a spotreby.',reference_liters:100,reference_dose_ml:1,nutrient_effects:{},verification_status:'pending'},
 {manufacturer:'JBL',product_name:'PROSCAPE NPK MACROELEMENTS',description:'Makro hnojivo s dusíkom ako nitrát, fosforom ako fosfát, draslíkom a horčíkom.',dosing_instructions:'Silné svetlo + CO₂: 6 ml/100 l denne; silné svetlo bez CO₂: 2 ml/100 l 3× týždenne; slabšie svetlo + CO₂: 2 ml/100 l denne; slabšie svetlo bez CO₂: 2 ml/100 l týždenne.',reference_liters:100,reference_dose_ml:1,nutrient_effects:{},verification_status:'partial'},
 {manufacturer:'JBL',product_name:'PROSCAPE N MACROELEMENTS',description:'Jednozložkové makro hnojivo radu PROSCAPE; presný účinok sa musí potvrdiť z deklarácie výrobcu.',dosing_instructions:'Dávkovanie podľa údajov výrobcu a spotreby.',reference_liters:100,reference_dose_ml:1,nutrient_effects:{},verification_status:'pending'},
 {manufacturer:'JBL',product_name:'PROSCAPE P MACROELEMENTS',description:'Jednozložkové makro hnojivo radu PROSCAPE; presný účinok sa musí potvrdiť z deklarácie výrobcu.',dosing_instructions:'Dávkovanie podľa údajov výrobcu a spotreby.',reference_liters:100,reference_dose_ml:1,nutrient_effects:{},verification_status:'pending'},
 {manufacturer:'JBL',product_name:'PROSCAPE K MACROELEMENTS',description:'Jednozložkové makro hnojivo radu PROSCAPE; presný účinok sa musí potvrdiť z deklarácie výrobcu.',dosing_instructions:'Dávkovanie podľa údajov výrobcu a spotreby.',reference_liters:100,reference_dose_ml:1,nutrient_effects:{},verification_status:'pending'},
 {manufacturer:'JBL',product_name:'PROSCAPE Mg MACROELEMENTS',description:'Doplnkové horčíkové hnojivo. 1 ml obsahuje 12,5 mg horčíka.',dosing_instructions:'Silné svetlo + CO₂: 6 ml/100 l denne; slabšie svetlo + CO₂: 2 ml/100 l denne; silné svetlo bez CO₂: 2 ml/100 l 3× týždenne; slabšie svetlo bez CO₂: 2 ml/100 l týždenne. 5 ml/100 l zvýši Mg približne o 0,625 mg/l.',reference_liters:100,reference_dose_ml:5,nutrient_effects:{mg:.625},verification_status:'verified'}
];
const explicitEffects=(text:string)=>{const e:any={};const patterns:[string,RegExp][]=[['no3',/(?:NO.?3|nitrate)[^0-9]{0,80}(?:increase|raise|zvýš|adds?)[^0-9]{0,30}([0-9]+(?:[.,][0-9]+)?)\s*mg\/?l/i],['po4',/(?:PO.?4|phosphate)[^0-9]{0,80}(?:increase|raise|zvýš|adds?)[^0-9]{0,30}([0-9]+(?:[.,][0-9]+)?)\s*mg\/?l/i],['k',/(?:potassium|draslík|\bK\b)[^0-9]{0,80}(?:increase|raise|zvýš|adds?)[^0-9]{0,30}([0-9]+(?:[.,][0-9]+)?)\s*mg\/?l/i],['fe',/(?:iron|železo|\bFe\b)[^0-9]{0,80}(?:increase|raise|zvýš|adds?)[^0-9]{0,30}([0-9]+(?:[.,][0-9]+)?)\s*mg\/?l/i],['mg',/(?:magnesium|horčík|\bMg\b)[^0-9]{0,80}(?:increase|raise|zvýš|adds?)[^0-9]{0,30}([0-9]+(?:[.,][0-9]+)?)\s*mg\/?l/i]];for(const[k,r]of patterns){const m=r.exec(text);if(m)e[k]=Number(m[1].replace(',','.'))}return e};
function parsePage(html:string,url:string,fallback:string){const text=strip(html);const title=strip(/<h1[^>]*>([\s\S]*?)<\/h1>/i.exec(html)?.[1]||/<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1]||fallback).replace(/\s*[|–].*$/,'').trim()||fallback;const dosing=(text.match(/(?:dávkování|dávkovanie|dosage|directions|dose|application|anwendung|dosierung)[^.]{0,650}\./i)||[])[0]||'';let manufacturer='';const hay=(title+' '+text).toLowerCase();for(const m of ['Seachem','JBL','INVITAL','Tropica','Easy-Life','Sera','Dennerle','ADA'])if(hay.includes(m.toLowerCase())){manufacturer=m;break}const effects=explicitEffects(text);const composition=(text.match(/(?:guaranteed analysis|declaration|zloženie|složen[ií]|obsahuje|contains)[\s\S]{0,900}/i)||[])[0]||'';return{product_name:title,manufacturer,description:(composition||text).slice(0,1000),dosing_instructions:dosing,reference_liters:100,reference_dose_ml:1,nutrient_effects:effects,source_url:url,source_name:'Online zdroj',confidence:Object.keys(effects).length?'high':'medium',verification_status:Object.keys(effects).length?'verified':'partial'}}
export async function GET(req:NextRequest){const q=(req.nextUrl.searchParams.get('q')||'').trim();if(q.length<3)return NextResponse.json({items:[]});try{const s=await createServerSupabaseClient();const safe=q.replace(/[%(),]/g,'');const out:any[]=[];const seen=new Set<string>();const add=(x:any)=>{const key=norm(`${x.manufacturer||''} ${x.product_name||''}`);if(!key||seen.has(key))return;seen.add(key);out.push(x)};const words=norm(q).split(' ').filter(w=>w.length>=2);const matches=(x:any)=>{const h=norm(`${x.manufacturer||''} ${x.product_name||''} ${x.description||''}`);return words.every(w=>h.includes(w))};
 const{data}=await s.from('fertilizer_catalog').select('id,manufacturer,product_name,reference_liters,reference_dose_ml,nutrient_effects,description,dosing_instructions,source_url,verification_status').or(`product_name.ilike.%${safe}%,manufacturer.ilike.%${safe}%,description.ilike.%${safe}%`).limit(30);for(const x of data||[])if(matches(x))add({...x,source_name:'Katalóg',confidence:x.verification_status==='verified'?'high':'medium'});
 if(/\bjbl\b/i.test(q)||/\bproscape\b/i.test(q)){for(const x of jblFamily)if(matches(x))add({...x,source_name:'Online zdroj',confidence:x.verification_status==='verified'?'high':'medium',source_url:'https://www.jbl.de/en/proscape/proscape_dosage/1'})}
 const compact=q.replace(/\s+/g,' ').trim();const searches=[...(/\bseachem\b/i.test(q)?[`site:seachem.com ${compact}`,`site:seachem.zendesk.com ${compact}`]:[]),...(/\bjbl\b/i.test(q)||/\bproscape\b/i.test(q)?[`site:jbl.de ${compact}`]:[]),`${compact} aquarium fertilizer composition dosage`,`site:invital.sk ${compact}`,`site:shrimp.sk ${compact}`,`site:aquascaperi.sk ${compact}`];for(const sq of searches){try{const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(sq)}`,{headers:{'User-Agent':'Mozilla/5.0'},cache:'no-store',signal:AbortSignal.timeout(6500)});if(!r.ok)continue;const html=await r.text();const links=[...html.matchAll(/class="result__a"[^>]*href="([^"]+)"/gi)].map(m=>unwrap(m[1])).filter(u=>/^https?:/i.test(u)&&allowed(u)).slice(0,15);for(const u of links){try{const p=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0'},cache:'no-store',signal:AbortSignal.timeout(6500)});if(!p.ok)continue;const item=parsePage(await p.text(),u,q);if(matches(item))add(item)}catch{}}}catch{}}
 out.sort((a,b)=>{const av=a.verification_status==='verified'?0:a.verification_status==='partial'?1:2,bv=b.verification_status==='verified'?0:b.verification_status==='partial'?1:2;return av-bv||String(a.product_name).localeCompare(String(b.product_name))});return NextResponse.json({items:out.slice(0,30),message:out.length?undefined:'Produkt sa nepodarilo automaticky dohľadať. Skús presnejší názov produktu alebo výrobcu.'})}catch(e:any){return NextResponse.json({items:[],error:e.message},{status:500})}}
