import {NextRequest,NextResponse} from "next/server";
import {createServerSupabaseClient} from "@/lib/supabase/server";
type Candidate={scientific_name:string;common_name?:string;difficulty?:string;light_requirement?:string;co2_requirement?:string;growth_rate?:string;placement?:string;ph_min?:number;ph_max?:number;temperature_min?:number;temperature_max?:number;notes?:string;source_url?:string;source_name:string;confidence:"high"|"medium"|"low"};
const strip=(s:string)=>s.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim();
const norm=(s:string)=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
const numRange=(text:string,label:string)=>{const r=new RegExp(`${label}[^0-9]{0,70}([0-9]+(?:[.,][0-9]+)?)\\s*(?:-|–|až|to)\\s*([0-9]+(?:[.,][0-9]+)?)`,`i`).exec(text);return r?[Number(r[1].replace(",",".")),Number(r[2].replace(",","."))] as const:null};
function parsePage(html:string,url:string,fallback:string):Candidate{const text=strip(html);const title=(/<h1[^>]*>([\s\S]*?)<\/h1>/i.exec(html)?.[1]||/<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1]||fallback);const name=strip(title).replace(/\s*[|–].*$/,'').trim()||fallback;const pH=numRange(text,"pH"),temp=numRange(text,"teplot|temperature");const easy=/nenároč|easy|low light|nízk[^.]{0,35}svetl/i.test(text),hard=/náročn|advanced|difficult|high light|vysok[^.]{0,35}svetl/i.test(text);const medium=/medium|stredne nároč|moderate/i.test(text);const co2req=/CO.?2[^.]{0,120}(nutn|vyžad|required|15.?30)/i.test(text),co2rec=/CO.?2[^.]{0,120}(odporúč|doporuč|recommended|10.?15)/i.test(text);const growth=/fast|rýchl/i.test(text)?"fast":/slow|pomal/i.test(text)?"slow":/medium|stred/i.test(text)?"medium":undefined;return{scientific_name:name,difficulty:hard?"hard":medium?"medium":easy?"easy":undefined,light_requirement:hard?"high":medium?"medium":easy?"low":undefined,co2_requirement:co2req?"required":co2rec?"recommended":undefined,growth_rate:growth,ph_min:pH?.[0],ph_max:pH?.[1],temperature_min:temp?.[0],temperature_max:temp?.[1],notes:"Údaje boli dohľadané online; pred potvrdením ich skontroluj.",source_url:url,source_name:"Online zdroj",confidence:(pH||temp||co2req||co2rec||easy||medium||hard)?"medium":"low"}}
function unwrap(raw:string){let u=raw.replace(/&amp;/g,"&");try{const p=new URL(u.startsWith("//")?`https:${u}`:u);const r=p.searchParams.get("uddg")||p.searchParams.get("url");if(r)u=decodeURIComponent(r)}catch{}return u}
function variants(q:string){const a=[q];for(const p of q.split(/[\/;,]+/).map(x=>x.trim()).filter(Boolean))a.push(p);if(/eleocharis\s+parvulus/i.test(q))a.push("Eleocharis parvula");if(/nymphoides.*taiwan/i.test(q))a.push("Nymphoides hydrophylla Taiwan","Nymphoides sp. Taiwan");return [...new Set(a)]}
export async function GET(req:NextRequest){const q=(req.nextUrl.searchParams.get("q")||"").trim();if(q.length<2)return NextResponse.json({items:[]});try{const s=await createServerSupabaseClient();const safe=q.replace(/[%(),]/g,"");const{data}=await s.from("plant_catalog").select("id,scientific_name,common_name,difficulty,light_requirement,co2_requirement,growth_rate,placement,ph_min,ph_max,gh_min,gh_max,kh_min,kh_max,temperature_min,temperature_max,notes,image_url").or(`scientific_name.ilike.%${safe}%,common_name.ilike.%${safe}%`).limit(8);if(data?.length)return NextResponse.json({items:data.map(x=>({...x,source_name:"Katalóg",confidence:"high"}))});
 const candidates:Candidate[]=[];const seen=new Set<string>();const add=(c:Candidate)=>{const k=norm(c.scientific_name);if(!k||seen.has(k))return;seen.add(k);candidates.push(c)};for(const v of variants(q)){const searches=[`site:tropica.com ${v} aquarium plant`,`site:flowgrow.de ${v} aquatic plant`,`site:shrimp.sk ${v} rastlina`,`site:invital.sk ${v} rastlina`,`site:en.wikipedia.org ${v} plant`,`${v} aquarium plant care`];for(const sq of searches){try{const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(sq)}`,{headers:{"User-Agent":"Mozilla/5.0"},cache:"no-store",signal:AbortSignal.timeout(6500)});if(!r.ok)continue;const html=await r.text();const links=[...html.matchAll(/class="result__a"[^>]*href="([^"]+)"/gi)].map(m=>unwrap(m[1])).filter(u=>/^https?:/i.test(u)).slice(0,10);for(const u of links){try{const page=await fetch(u,{headers:{"User-Agent":"Mozilla/5.0"},cache:"no-store",signal:AbortSignal.timeout(6500)});if(page.ok)add(parsePage(await page.text(),u,v));if(candidates.length>=8)break}catch{}}}catch{}if(candidates.length>=8)break}if(candidates.length>=8)break}
 try{const wr=await fetch(`https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(v)}&format=json&origin=*`,{headers:{"User-Agent":"DuoAkvaDiary/1.0"},cache:"no-store",signal:AbortSignal.timeout(5000)});if(wr.ok){const wj=await wr.json();for(const x of (wj?.query?.search||[]).slice(0,3)){const title=String(x.title||"");if(!title)continue;add({scientific_name:title,notes:"Botanická zhoda dohľadaná online; pestovateľské nároky neboli z tohto zdroja odvodené.",source_url:`https://en.wikipedia.org/wiki/${encodeURIComponent(title.replace(/ /g,"_"))}`,source_name:"Online zdroj",confidence:"low"})}}}catch{}}
 if(!candidates.length)return NextResponse.json({items:[],message:"Rastlinu sa nepodarilo automaticky dohľadať. Skús vedecký názov alebo kratšiu časť názvu."});return NextResponse.json({items:candidates.slice(0,8)})}catch(e:any){return NextResponse.json({items:[],error:e.message},{status:500})}}
