import {NextRequest,NextResponse} from "next/server";
import {createServerSupabaseClient} from "@/lib/supabase/server";

type Candidate={scientific_name:string;common_name?:string;difficulty?:string;light_requirement?:string;co2_requirement?:string;growth_rate?:string;placement?:string;ph_min?:number;ph_max?:number;gh_min?:number;gh_max?:number;kh_min?:number;kh_max?:number;temperature_min?:number;temperature_max?:number;notes?:string;source_url?:string;source_name:string;confidence:"high"|"medium"|"low";match_label?:string};
const strip=(s:string)=>s.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim();
const norm=(s:string)=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
const slug=(s:string)=>norm(s).replace(/\s+/g,"-");
const numRange=(text:string,label:string)=>{const r=new RegExp(`${label}[^0-9]{0,90}([0-9]+(?:[.,][0-9]+)?)\\s*(?:-|–|až|to)\\s*([0-9]+(?:[.,][0-9]+)?)`,`i`).exec(text);return r?[Number(r[1].replace(",",".")),Number(r[2].replace(",","."))] as const:null};
function unwrap(raw:string){let u=raw.replace(/&amp;/g,"&");try{const p=new URL(u.startsWith("//")?`https:${u}`:u);const r=p.searchParams.get("uddg")||p.searchParams.get("url");if(r)u=decodeURIComponent(r)}catch{}return u}
function variants(q:string){const out=[q,...q.split(/[\/;,]+/).map(x=>x.trim()).filter(Boolean)];if(/eleocharis\s+parvulus/i.test(q))out.push("Eleocharis parvula");if(/nymphoides.*taiwan/i.test(q))out.push("Nymphoides hydrophylla Taiwan","Nymphoides sp. Taiwan");return [...new Set(out)]}
function relevant(title:string,q:string){const t=norm(title),words=norm(q).split(' ').filter(w=>w.length>=4);if(/\blist of\b|flora of|species epithets|data deficient/i.test(title))return false;if(!words.length)return true;return words.every(w=>t.includes(w))||words.some(w=>t.includes(w))}
function directUrls(v:string){const s=slug(v);return [`https://www.shrimp.sk/${s}-kosik`,`https://www.shrimp.sk/${s}-invitro-100ml`,`https://www.invital.sk/${s}`,`https://www.invitalshop.sk/${s}`]}
function parsePage(html:string,url:string,fallback:string):Candidate|null{const text=strip(html);const rawTitle=(/<h1[^>]*>([\s\S]*?)<\/h1>/i.exec(html)?.[1]||/<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1]||fallback);let name=strip(rawTitle).replace(/\s*[|–].*$/,'').replace(/\s*[-–]\s*(košík|in vitro|invitro).*$/i,'').trim()||fallback;if(!relevant(name,fallback))return null;
 const pH=numRange(text,"pH"),temp=numRange(text,"(?:vhodná )?teplota|temperature"),gh=numRange(text,"GH|tvrdosť vody|hardness"),kh=numRange(text,"KH");
 const explicitLight=(text.match(/(?:úroveň osvetlenia|light demand|lighting|svetlo)[^.:]{0,20}[:\s]+([^.;]{0,80})/i)||[])[1]||"";
 const lightHigh=/vysok|high/i.test(explicitLight),lightLow=/nízk|low/i.test(explicitLight),lightMid=/stred|medium|moderate/i.test(explicitLight);
 const diffText=(text.match(/(?:náročnosť|difficulty)[^.:]{0,20}[:\s]+([^.;]{0,80})/i)||[])[1]||"";
 const hard=/náročn|difficult|advanced/i.test(diffText),easy=/nenároč|easy|low/i.test(diffText),medium=/stred|medium|moderate/i.test(diffText);
 const co2Text=(text.match(/CO.?2[^.:]{0,20}[:\s]+([^.;]{0,100})/i)||[])[1]||"";
 const co2req=/nutn|vyžad|required/i.test(co2Text),co2rec=/odporúč|doporuč|recommended|nie je nutné|not required/i.test(co2Text);
 const growthText=(text.match(/(?:rýchlosť rastu|growth rate)[^.:]{0,20}[:\s]+([^.;]{0,60})/i)||[])[1]||"";
 const growth=/rýchl|fast/i.test(growthText)?"fast":/pomal|slow/i.test(growthText)?"slow":/stred|medium/i.test(growthText)?"medium":undefined;
 const placeText=(text.match(/(?:umiestnenie|placement)[^.:]{0,20}[:\s]+([^.;]{0,80})/i)||[])[1]||"";
 const placement=/popred|foreground/i.test(placeText)?"foreground":/stred|midground/i.test(placeText)?"midground":/pozad|background/i.test(placeText)?"background":/pláv|floating/i.test(placeText)?"floating":undefined;
 const difficulty=hard?"hard":medium?"medium":easy?"easy":undefined;
 const light=lightHigh&&!lightLow&&!lightMid?"high":lightLow&&!lightHigh?"low":lightMid||lightHigh&&lightLow?"medium":undefined;
 const useful=[difficulty,light,co2req||co2rec?"co2":undefined,growth,placement,pH,temp,gh,kh].filter(Boolean).length;
 return{scientific_name:name,difficulty,light_requirement:light,co2_requirement:co2req?"required":co2rec?"recommended":undefined,growth_rate:growth,placement,ph_min:pH?.[0],ph_max:pH?.[1],gh_min:gh?.[0],gh_max:gh?.[1],kh_min:kh?.[0],kh_max:kh?.[1],temperature_min:temp?.[0],temperature_max:temp?.[1],notes:"Údaje boli dohľadané online. Pred uložením ich skontroluj.",source_url:url,source_name:"Online zdroj",confidence:useful>=4?"high":useful>=2?"medium":"low",match_label:useful?"Nájdený pestovateľský profil":"Nájdená možná zhoda"}}
async function fetchCandidate(url:string,v:string){try{const r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0"},cache:"no-store",signal:AbortSignal.timeout(5500),redirect:"follow"});if(!r.ok)return null;return parsePage(await r.text(),r.url||url,v)}catch{return null}}
export async function GET(req:NextRequest){const q=(req.nextUrl.searchParams.get("q")||"").trim();if(q.length<2)return NextResponse.json({items:[]});try{const s=await createServerSupabaseClient();const safe=q.replace(/[%(),]/g,"");const{data}=await s.from("plant_catalog").select("id,scientific_name,common_name,difficulty,light_requirement,co2_requirement,growth_rate,placement,ph_min,ph_max,gh_min,gh_max,kh_min,kh_max,temperature_min,temperature_max,notes,image_url").or(`scientific_name.ilike.%${safe}%,common_name.ilike.%${safe}%`).limit(8);if(data?.length)return NextResponse.json({items:data.map(x=>({...x,source_name:"Katalóg",confidence:"high",match_label:"Zhoda v katalógu"}))});
 const candidates:Candidate[]=[];const seen=new Set<string>();const add=(c:Candidate|null)=>{if(!c)return;const key=norm(c.scientific_name);if(!key||seen.has(key))return;seen.add(key);candidates.push(c)};
 for(const v of variants(q)){for(const u of directUrls(v)){add(await fetchCandidate(u,v));if(candidates.some(c=>c.confidence==='high'))break}if(candidates.some(c=>c.confidence==='high'))break}
 if(candidates.length<4){for(const variant of variants(q)){const searches=[`site:tropica.com ${variant} aquarium plant`,`site:flowgrow.de ${variant} aquatic plant`,`site:shrimp.sk ${variant} rastlina`,`site:invital.sk ${variant} rastlina`,`${variant} aquarium plant care`];for(const sq of searches){try{const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(sq)}`,{headers:{"User-Agent":"Mozilla/5.0"},cache:"no-store",signal:AbortSignal.timeout(5000)});if(!r.ok)continue;const html=await r.text();const links=[...html.matchAll(/class="result__a"[^>]*href="([^"]+)"/gi)].map(m=>unwrap(m[1])).filter(u=>/^https?:/i.test(u)).slice(0,8);for(const u of links){add(await fetchCandidate(u,variant));if(candidates.length>=6)break}}catch{}if(candidates.length>=6)break}if(candidates.length>=6)break}}
 if(!candidates.length)return NextResponse.json({items:[],message:"Nenašla sa dostatočne relevantná zhoda. Skús vedecký názov alebo kratšiu časť názvu."});return NextResponse.json({items:candidates.slice(0,6)})}catch(e:any){return NextResponse.json({items:[],error:e.message},{status:500})}}
